### ISSUE TITLE
The StructureMissingElevationEditorVM incorrectly identifies missing data for all required fields when any data is missing, or when terrain elevations are not available

### ISSUE THREAD

**Issue by AlexRyanUSACE** [HydrologicEngineeringCenter/HEC-FDA#1008]
The StructureMissingDataRowItem object correctly tracks whether or not each row is missing data (null or "") in any of the required columns/rows, but if the validate method fails, in lines 33-46 of the StructureMissingElevationEditorVM all required columns are added to the displayed tab showing missing data, which incorrectly communicates to the user that data is missing in these rows. Instead it should conditionally add these columns to the displayed error message/tab if they contain missing data (and a 5th condition should be added for inventories where elevation is pulled from a terrain grid, when the operation to do this fails).

The constructor for StructureMissingElevationEditorVM is passed a list of StructureMissingDataRowItem as a parameter currently, i would recommend instead passing it the StructuresMissingDataManager directly, and adding a property to that to return whether or not any rows in a given column failed validation (or if terrain data is unavailable for some reason). This property could then be called from the StructureMissingElevationEditorVM to determine which columns to add to the displayed tab/window.

**Comment by Brennan1994** [comment]
The image below is a dataset where I deleted Struct vals out of the SI. 

![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/64556723/b7d133cb-d63d-4de9-be1b-588f3a075020)

**Comment by Brennan1994** [comment]
A more thorough solution might be to abandon the table view all together, and just give a list of structure IDs and their missing attributes, which is doable, and leaves no ambiguity, but is a little less pretty. 

My personal preference is to leave it as is, but if it may come off as ambiguous to users what is meant, I think we'll be best off abandoning the table view, and instead just listing which IDs have which missing values as text. 

This section of the code is pretty confusing and could use a rework as well if we're going to restructure. 
@rnugent3 what are your thoughts?

**Comment by rnugent3** [comment]
"All required attributes are displayed."

**Comment by rnugent3** [comment]
I took the priority label off. This is purely to enhance the user experience - not critical.
