### ISSUE TITLE
Crash in Scenario editor when previewing compute with Non-failure scenario

### ISSUE THREAD

**Issue by AlexRyanUSACE** [HydrologicEngineeringCenter/HEC-FDA#1010]
When attempting to preview compute in the Scenario editor when using a non-fail scenario, an exception is thrown when attempting to draw Y axis labels. This appears to be caused by the fact that in the GraphicalUncertainPairedData object on line 96, the generated pairedData object returned by the SamplePairedData method is not passed the metadata from the GraphicalUncertainPairedData, only y and x values. When this returned paired data is used to label the y axis (on line 23 of the FrequencyRelationshipControl) it throws an exception as pd.Metadata is null. It appears the fix is to simply pass the curvemetadata to the returned paireddata object in the GraphicalUncertainPairedData:

 PairedData expandedPairedData = new PairedData(ExceedanceToNonExceedance(CombinedExceedanceProbabilities), expandedStageOrLogFlowValues, CurveMetaData);

**Comment by rnugent3** [comment]
I am unable to replicate this issue. 

![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/25163165/b4ef0202-857b-4600-8e6c-64b6297f921d)
