### ISSUE TITLE
Crash when previewing compute in scenario editor when not using non-fail scenario

### ISSUE THREAD

**Issue by AlexRyanUSACE** [HydrologicEngineeringCenter/HEC-FDA#1011]
The Scenario editor will also throw an exception when previewing compute without non-fail scenario selected. In this case it appears to be because the simulation creator in line 538 of the SpecificIASEditorVM class is passed NonFailureSelectedStageDamage, when in this use case it is null (the exception is thrown on line 536). A fix for this at least may be to test if this value is null before attempting to pull the aggregated stage damage element from it and pass it to the simulation creator.

**Comment by rnugent3** [comment]
@AlexRyanUSACE I am not able to replicate this issue - neither in debug nor release. Working off of latest, I published a build and can successfully preview the compute. 

![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/25163165/757dc429-1c10-4887-9eae-002f4e57baf8)

**Comment by rnugent3** [comment]
This only happens immediately after creating a new Scenario. After saving the new scenario, closing the editor, and re-opening, preview compute works as expected. 

@Brennan1994 does this ring any bells for you?

**Comment by rnugent3** [comment]
I am following a trail. I don't think that non-fail scenario stuff has been completely hooked up between the IASEditorVM and the SpecificIASEditorVM. I think that this property should probably have at least one reference!

**Comment by rnugent3** [comment]
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/25163165/284b6c09-7fc7-48d1-80f7-0eb92d1d4166)

**Comment by rnugent3** [comment]
why, upon creating a new scenario, should we expect that a non fail stage damage function exists??

**Comment by rnugent3** [comment]
it seems that somewhere we are creating a dummy simulation upon creating a new scenario and we forgot to add non fail stage damage to that dummy
