### ISSUE TITLE
Scenario editor dropdown for damage category duplicates each damage category 4x

### ISSUE THREAD

**Issue by AlexRyanUSACE** [HydrologicEngineeringCenter/HEC-FDA#1012]
When selecting a damage category from the dropdown, each damage category is duplicated four times.

**Comment by rnugent3** [comment]
Here lies the problem.  

![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/25163165/507ebd72-12f1-4934-af18-bd7b18dc235e)

**Comment by rnugent3** [comment]
That needs to be a collection of string damage categories then bind to a selected dam cat, then the selected dam cat and selected asset cat determine the selecteddamagecurve
