### ISSUE TITLE
Incorrect Structure Inventory Import Error Messaging

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#1018]
When we try to retrieve terrain data as part of a structure inventory import and are unsuccessful, the structures missing data widow appears, trying to indicate that terrain data is missing, but the ground elevations column does not populate, so it is not clear that the terrain is the problem.

**Comment by rnugent3** [comment]
I am bumping this issue up to high priority. I've had enough false bug reports as a result of our poor messaging here that I think it is worth fixing ASAP.

**Comment by rnugent3** [comment]
@Brennan1994 would you take a look, please?

**Comment by Brennan1994** [comment]
Is this the thing we're looking at? because It looks to me like it does show ground elevation. Do you have a dataset that reproduces this behavior?

![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/64556723/895b8163-ca8d-49e6-9271-9f1924dbb095)

**Comment by rnugent3** [comment]
You should get the behavior if you use Muncie structures and west sac terrain.

**Comment by rnugent3** [comment]
Or any other combination of non-matching terrain and inventory. 

If the two should be matching, but we get all invalid, that's a projection thing, and we're tracking that on a separate issue.
