### ISSUE TITLE
Deprecate IOrdinate

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/HEC-FDA#104]
https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/c73046d6b7c1e5d67c1db5fb322ae574f8fc5e3d/Functions/Ordinates/IOrdinate.cs#L12

IOrdinate is being replaced by the functionality included in PairedData and UncertainPairedData. There are some interface elements that are not well transcribed yet. There might need to be a refactor to break out the interface into smaller interfaces to shift functionality to the right locations in the code.

**Comment by rnugent3** [comment]
DNE
