### ISSUE TITLE
The Damage Category disappears from the user interface in the Stage-Damage Function

### ISSUE THREAD

**Issue by kevinrrogers** [HydrologicEngineeringCenter/HEC-FDA#1056]
**Steps**
1. Open FDA 2.0
2. Import a Stage-Damage Function
3. Update any Damage Category (NOTE: The "Damage Category" drop-down does not show any selections by default)
4. Click "Save" (NOTE: The "Save" tooltip says "No changes to save")
5. Click "Close"
6. Edit the Stage-Damage Function from Step 2 above.

**Expectation**

- The Damage Category selected in Step 3 and saved in Step 4 appears in the user interface.

**Reality**

- The Damage Category selected in Step 3 and saved in Step 4 does not appear in the user interface.

![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/156859598/5a9864d6-bd50-4bd2-9a1c-8f5f49bd5780)
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/156859598/9275d925-df18-4cc5-8aa8-cffc461d7b53)

**Comment by rnugent3** [comment]
stellar bug report! thanks, @kevinrrogers - we'll get working on it asap
