### ISSUE TITLE
Deprecate IDistributedOrdinate

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/HEC-FDA#106]
https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/c73046d6b7c1e5d67c1db5fb322ae574f8fc5e3d/Functions/Ordinates/IDistributedOrdinate.cs#L11

The Statistics IDistribution closely mirrors this interface, it will satisfy the vast majority of our needs and simplify the duplication of the two closely related interfaces

**Comment by rnugent3** [comment]
this code no longer exists
