### ISSUE TITLE
Threshold Stage resets to 0 if set manually

### ISSUE THREAD

**Issue by kevinrrogers** [HydrologicEngineeringCenter/HEC-FDA#1081]
**Steps**

1. Create a Scenario.
2. Uncheck "Calculate Default Threshold".
3. Enter a non-zero Threshold Stage: ![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/156859598/e4b41623-c2d9-4d4e-ab4a-30bf8c60cf44)
4. Click "Save".
5. Click "Close".
6. Edit the Scenario from Step 1.

**Expectations**

- The "Threshold Stage" value is the same as it was in Step 3.

**Reality**

- The "Threshold Stage" value is "0": 
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/156859598/02fe1ad8-32b0-40f5-b2b1-872686114294)

**Comment by rnugent3** [comment]
Please make sure you have the latest build and re-test. 

https://www.hec.usace.army.mil/confluence/display/FDATutorials/NYC+FY24+Download+HEC-FDA+Version+2.0+Portable+Package

**Comment by jbslaughter** [comment]
Here's an image of the summary results table for my example study which shows that this is still a bug in the latest build I have dated 01-Oct-2024.
![image](https://github.com/user-attachments/assets/466fabf3-0b00-4623-bcca-ea8ec9a31c5f)

**Comment by Brennan1994** [comment]
@jbslaughter and I iterated on this till we got to a reasonable solution. Julia, please reopen if that isn't the case.
