### ISSUE TITLE
Error When Reopening Previously Saved Study

### ISSUE THREAD

**Issue by rtle76** [HydrologicEngineeringCenter/HEC-FDA#1088]
This error is happening again/still: 

![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/67108837/1674ced8-114c-40c4-89b9-9cf3f32390c0)

It doesn't seem to be happening with studies that are 1.4.3 exports to 2.0, and does seem to be happening when it's a full 2.0 model.

**Comment by Brennan1994** [comment]
I hate to see this. @rtle76 , do you have a dataset you can provide that reproduces this issue?

**Comment by rtle76** [comment]
@Brennan1994 I uploaded here: \\share.hec.usace.army.mil\USACE\Nugent\ForJordan\Troubleshooting\20240416\GitHubIssue1088

**Comment by rnugent3** [comment]
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/25163165/387c7aa1-4b1d-41d3-b934-79ced82478bd)
