### ISSUE TITLE
Long number format ignored

### ISSUE THREAD

**Issue by rtle76** [HydrologicEngineeringCenter/HEC-FDA#1094]
The software doesn't appear to accept the Long number format for the foundation height attribute in the structure inventory: Double number format is required. It may be a good idea to allow Long.

Foundation heights with Long number format defaulted to -999. This may also pertain to other attributes in the structure inventory or other imported data. I have only encountered it with foundation height in the structure inventory.

Obviously this isn't critical as one can simply convert to Double number format, which is best practice anyway. But I encountered this when importing a txt file into ArcGIS Pro using XY coordinates and then imported that into FDA. It appears that Arc Pro may default to Long number format for txt files imported this way in some cases. I have done that a lot historically (since FDA generates structure details in txt), so I can imagine this may pop up fairly regularly when the software is released.

**Comment by Brennan1994** [comment]
Tell me more about what you mean by long number format. meaning you can't use decimals?

**Comment by rtle76** [comment]
> Tell me more about what you mean by long number format. meaning you can't use decimals?

Double allows decimals, Long does not (only integers). That's why I say it's best practice to the convert data to Double (because we work in decimals when it comes to foundation heights), which you can do in Arc Pro. 

Another option would be to reject Long numbers with a warning message telling the user to convert to Double.

**Comment by rnugent3** [comment]
this is showing up in multiple studies and causes funny results without good communication about why results are funny, I think we should prioritize this to reduce the amount of user support we'll have to do

**Comment by rnugent3** [comment]
[Crops_Sac39_NAD_1983_StatePlaneCA.zip](https://github.com/user-attachments/files/16445526/Crops_Sac39_NAD_1983_StatePlaneCA.zip)
