### ISSUE TITLE
Gridded hydraulics importing is mixing up the return intervals

### ISSUE THREAD

**Issue by rtle76** [HydrologicEngineeringCenter/HEC-FDA#1097]
When imported gridded hydraulics, I set the return interval to be the correct value. Upon saving, closing, and reopening, it reverts the return interval and AEP to nonsense. See below.

![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/67108837/6a49766b-f4ab-4e26-8116-2465feb2d3f9)

**Comment by rtle76** [comment]
Then this happens when the stage-damage function is generated, which further suggests the AEP/Return Interval are being messed up in the compute: 
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/67108837/f5c56199-fabb-4c44-8d13-2d3057260ba7)

**Comment by rnugent3** [comment]
Replicated. Import gridded hydraulics, save correct parameterization, close, re-open, incorrect parametrization illustrated
Correct, upon save:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/25163165/525ffffb-8507-441b-a4dd-5da73dabd87f)
Incorrect, upon reopen:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/25163165/9a6cde28-0375-4a22-8b4d-661a6c603540)

**Comment by rnugent3** [comment]
appears to be isolated to the UI, when you run stage-damage, we have reasonable looking curves. 

When the probabilities get out of whack, then stage-damage becomes non-monotonic.

**Comment by Brennan1994** [comment]
ouch. this is ugly. on it.
