### ISSUE TITLE
impact area name printed to file incorrect

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#1106]
we print the impact area alongside all the other structure information in our stage damage detail reporting, but the impact area that shows up appears to be the int model ID for that impact area, not the name of the impact area. 

Any study could be used to replicate

**Comment by rnugent3** [comment]
This is preventing me from troubleshooting effectively, and will prevent PDTs just the same.

**Comment by rnugent3** [comment]
This is not a bug, I just haven't written the code in a way that gets the impact area name into the structure detail report. I print the impact area ID, not the name. @Brennan1994 would you mind taking a look?

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/1d1c23380551d20ab0f4ad884c542ccd574ccb40/HEC.FDA.Model/structures/Structure.cs#L286

**Comment by Brennan1994** [comment]
fixed by #1145
