### ISSUE TITLE
.NET 8 Build Imports Occ Types Incorrectly 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#1107]
I have downloaded and am running the build from the .NET 8 build in PR #1103 

All occ types have all four dam cats selected for damage calculation, even if just structure and content are in the occ type data. Any occ type file should show this 

![image](https://github.com/user-attachments/assets/5eea0f66-804b-43ae-9681-97d2977eb063)

**Comment by Brennan1994** [comment]
This lines up with a prior bug report. I'll look into it. Do you know that this didn't occur in a prior build?

**Comment by rnugent3** [comment]
I know that this didn't occur in a prior build. I verified with something that I build locally in May.

**Comment by Brennan1994** [comment]
Is this still the desired behavior @rnugent3 ? Right now I'm seeing the categories are unchecked if they don't have a damage function in them.

**Comment by rnugent3** [comment]
The desired behavior is that the asset category is unchecked if no damage function is imported.
