### ISSUE TITLE
.NET 8 Build Aggregated Stage-Damage Broken

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#1108]
## .NET 8 Branch Artifact
New London Orleans Aggregated Stage-Damage Functions show up weird in the .NET 8 Build:
![image](https://github.com/user-attachments/assets/8288a2b6-28ca-4b42-9b70-784b978d0ee4)

## Main Artifact
Here's the same compute using the [build](https://github.com/HydrologicEngineeringCenter/HEC-FDA/actions/runs/9357450594/artifacts/1564435990) from current main: 
![image](https://github.com/user-attachments/assets/1c280f67-5467-41d2-9edb-ae6886914958)

## May Local Build
The same compute using a software package built locally in May matches the main artifact perfectly 
![image](https://github.com/user-attachments/assets/5bc3d848-4807-4b11-8acc-f6ee7a6c297e)

## Original Calculation
The original calculation has a very small difference in the functions, probably not enough to show up in EAD
![image](https://github.com/user-attachments/assets/ff5f4571-5a61-42d5-81e7-0aa00f2d5552)

**Comment by rnugent3** [comment]
Here's the New London Orleans study data: https://drive.hecdev.net/share/TdXm-UGz

**Comment by Brennan1994** [comment]
Confirmed I can reproduce this between current main and the .NET8 branch
