### ISSUE TITLE
Confidence Limits Not Retained in Flow-Frequency Display

### ISSUE THREAD

**Issue by rtle76** [HydrologicEngineeringCenter/HEC-FDA#1124]
When creating a flow-frequency function, you can select Compute Confidence Limits to show the 2.5% and 97.5% confidence limits. However, when you save the function, close and reopen it, the confidence limits are no longer displayed. This can cause confusion with users that the confidence limits aren't being retained when they are. This ticket was prompted by a user that submitted a ticket in Discourse thinking the confidence limits were being lost.

**Comment by rnugent3** [comment]
A simple response would be to change "compute confidence limits" to "visualize confidence limits"
