### ISSUE TITLE
Values will not import for Stage-Discharge Functions

### ISSUE THREAD

**Issue by cbolt0626** [HydrologicEngineeringCenter/HEC-FDA#1128]
When importing the Stage Discharge functions directly out of 1.43 and into 2.0, the rating curve is not bringing in the flow data. I was able to duplicate the issue several times when trying to import new hydraulics. All of the project files are located here: \\share.hec.usace.army.mil\USACE\Taylor\FDA2.0_Transfer\Issue1128

![2024-08-21 12_55_57-Window](https://github.com/user-attachments/assets/8b8bfa0f-6f9e-4e4d-9cdc-f07c03460863)

**Comment by rnugent3** [comment]
Our importer should handle this 

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/dfb88970ecb9a7b92d3cd1e8e31b7bf28497e51b/HEC.FDA.ViewModel/Utilities/ImportFromFDA1Helper.cs#L122
