### ISSUE TITLE
Bad occupancy type data sneaks into compute

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#1130]
An unhandled exception occurs when you try to compute aggregated stage-damage function using the study below. The unhandled exception occurs because bad occupancy type data is making its way into the compute. I don't know what about the particular occupancy type data causes the issue; I am unable to drill into the stack trace because the unhandled exception occurs in the parallel compute. 

![image](https://github.com/user-attachments/assets/5ac3c2fc-baef-4a7e-8bc6-83ca645b6427)

You can confirm that the compute runs nicely when the workshop occupancy types are used instead of the occupancy type data set that was provided in the study data. 

Could have something to do with the CSVRs, there are means less than mins and such. 

\\share.hec.usace.army.mil\USACE\Corley\Studies\Garden City Targeted DQC\GI_GardenCity_v4

**Comment by Brennan1994** [comment]
confirmed I'm seeing wretched CSVRs. Gonna see if we're doing any validation on that before compute.

**Comment by Brennan1994** [comment]
Do we have the import file these were made from?

**Comment by rnugent3** [comment]
These wretched CSVRs were created in our user interface. The import file does not have the same nonsensical parameterization.
