### ISSUE TITLE
Possible Validation Bug on ViewModel Impact Area

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/HEC-FDA#115]
https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/16885afe9051ea65cd775e7ff7583cff7e856d5f/ViewModel/ImpactArea/ImpactAreaVM.cs#L56

It seems that the validation checks to see if a String backed property is empty string before checking if it is null, that would trigger a null pointer exception - suggest we check if the string is null or empty in one validation check since the message is the same either way. Check for nullness first, and then empty.

**Comment by codymccoy** [comment]
The name validation rule got refactored to a base class. I tested that the impact area editor doesn't throw a NPE for the name.
