### ISSUE TITLE
create new stage damage functions throws unhandled exception 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#1161]
to reproduce, open any study, right click on aggregated stage-damage functions, click create new stage-damage functions

@Brennan1994 would you mind taking a look? this is a very new bug

![image](https://github.com/user-attachments/assets/9cad7601-d69a-4d73-bbb1-0098a239eda1)

**Comment by Brennan1994** [comment]
on it

**Comment by rnugent3** [comment]
nice thank you sir
