### ISSUE TITLE
Dummy occupancy type inventory assignment saves incorrectly 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#1187]
Bug report from the field: 

`I am encountering a bug in 11/18/24 version of FDA 2.0 when using manually entered occupancy types. When I import a structure inventory the Default Occupancy Type Assignment is saving incorrectly. 

They’re importing correctly, as seen in the first screenshot but when I click Finish the inventory is imported but all the occupancy type assignments change to MULTI-PIER, which is the first occupancy type I added to when creating the occupancy type set. This issue has occurred for new and existing inventories, for all created Occupancy Types, and in new projects. Imported Occupancy Types save correctly, is there a way to export my Occupancy Type set to a text file?

I’ll show some of my trouble shooting using a dummy Occupancy Type set.
 

I created a dummy Occupancy Type set, entered Value 1 and Value 2, clicked save on the occupancy type set, entered Value 3, then saved and closed. I edited my inventory to manual assign occupancy types in the order seen below. 
 

When I click finish to import the inventory, then re-open the inventory to edit the screenshot below shows what I see. Value 2’s assignments are replaced by Value 1. For some reason Value 3 is not replaced which was unexpected since this did not happen for my other occupancy type sets. Values 1 and 3 can be moved around and will save correctly, value 2 is always overwritten.
 

Let me know if I can provide any further clarification. I will upload this model to the Study Drop-off folder, its titled “LC205 FDA v2”.`

**Comment by Brennan1994** [comment]
From @rnugent3 via Rocket

Manually entered occ type assignments for a structure inventory are not saving correctly.
assignments made for occ types that were imported save correctly

**Comment by Brennan1994** [comment]
Looks like additional occtypes are being saved with duplicate group /individual IDs  when made from the UI. Investigating more.

**Comment by Brennan1994** [comment]
![image](https://github.com/user-attachments/assets/71dbf647-477e-486e-a99f-800279e3925c)
