### ISSUE TITLE
Fix Bug in Statistics.Histograms.Histogram.Fit() Method

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#124]
I identified the bug with the following unit test, where the min = 0, the max = 5, and the binWidth is 1.

```
 public void Fit_ExpandsHistogram_WithDataOutOfRange(double min, double max, double binWidth)
        {
            double[] data = new double[5] { 1, 2, 3, 4, 5 };
            IData obs = new Data(data);

            IHistogram histogram = new HistogramBinnedData(obs, min, max, binWidth);

            double[] newData = new double[2] { 7, 9 };
            IData newObs = new Data(newData);

            var newHistogram = Histogram.Fit(histogram, newObs);

            double expected = 9.5;
            double actual = newHistogram.Range.Max;
            Assert.Equal(expected, actual);
        }

```
The histogram bins expand as required, but the new observations are not populated into the expanded bins. Actual is returned as 5.5 (one observation in the bin from 5 to 6).

**Comment by rnugent3** [comment]
I am inclined to re-write the FillHistogramBins method because the logic does not make sense to me. It might be quicker to translate the AddObservation/AddObservations method from InlineHistogram rather than make sense of the logic here.  @HenryGeorgist what do you think?

**Comment by HenryGeorgist** [comment]
your call. I have been taking the approach of rewriting, because fixing with all these interfaces at play is frustrating.
