### ISSUE TITLE
Write new histogram classes

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#126]
The approach of the current histogram classes involves a histogram object that is challenging to work with making fixing bugs inefficient. We'll re-write the histogram classes based on inline-histogram.

**Comment by rnugent3** [comment]
Thanks for the input, @HenryGeorgist and @codymccoy.

**Comment by rnugent3** [comment]
The VB is a little hard for me to follow, but it looks like you create a new array made up of the old array plus the additional bins?

**Comment by codymccoy** [comment]
I sometimes find it easiest to convert an array to a list, then do all the adding and what not, and then call ".toArray()" on the list at the end.

**Comment by HenryGeorgist** [comment]
In the vb example we use a private array, and we do some magic to redimension and array buffer copies to deal with it. The important thing is to set something up and then get passing tests. We can make it more efficient later.
