### ISSUE TITLE
Complete IAS reporting 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#134]
There will be five reports:

1. Expected annual damage distribution (please see revision in design document)
2. Expected annual damage by damage category 
3. Performance: distribution of AEP given a user-identified and user-selected threshold 
4. Performance: Long-term risk given a user-identified and user-selected threshold 
5. Performance: Assurance of user-identified and user-selected threshold  (please see revision in design document)

**Comment by codymccoy** [comment]
This is completed.
