### ISSUE TITLE
Alternatives - AAEQ damage

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#142]
A menu item reading "Calculate Average Annual Equivalent Damage" must be added to the alternative child tree node. Using the period of analysis and discount rate defined in the study properties, the average annual equivalent damage should be calculated and be provided according to the reports found in the bottom image below. Users will be able to calculate average annual equivalent damage distributions (using the IDistribution interface in the Statistics.dll) by discounting the future year impact area scenario expected annual damages (defined in the Model.dll IMetric interface) at the user specified discount rate. The average annual equivalent dam age routine should make use of the IFunction interface that allows the user to specify the method of interpolation between future expected annual damage values associated with each impact area scenario (ICondition) element.A menu item reading "Calculate Average Annual Equivalent Damage" must be added to the alternative child tree node. Using the period of analysis and discount rate defined in the study properties, the average annual equivalent damage should be calculated and be provided according to the reports found in the bottom image below. Users will be able to calculate average annual equivalent damage distributions (using the IDistribution interface in the Statistics.dll) by discounting the future year impact area scenario expected annual damages (defined in the Model.dll IMetric interface) at the user specified discount rate. The interpolation of EAD between analysis years will be linear.

**Comment by codymccoy** [comment]
This is completed.
