### ISSUE TITLE
Update Alternative COmparison Report UI

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#146]
The user interface should be updated to reflect the image in the design document. Once the alternative objects exist, the alternatives will get loaded into the combo boxes. There should be two columns of combo boxes, and the number of rows equal to the total number of alternatives minus 1. The first column should have a title "Without-project condition" and the other column should have a title "With-project conditions."

**Comment by codymccoy** [comment]
This is completed.
