### ISSUE TITLE
Alternative Comparison Report Reporting 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#147]
Reporting consists of:

- EAD reduced distribution 
- EAD reduced by impact area
- EAD reduced by damage category 
- EAD summary
- AAEQ damage reduced distribution 
- AAEQ damage reduced by impact area
- AAEQ damage reduced by damage category 
- AAEQ summary 

This also requires a view results menu item

**Comment by codymccoy** [comment]
This is completed.
