### ISSUE TITLE
Updates to the database. Removing the requirement of a "Name" column.

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#164]
We used to not have an ID column in the database. We used to have to find and update items based on their name. Now we have id's but the logic to update still depends on a name column. We talked about changing up the database at some point so i don't want to put in any more time than I have to on this right now. I think it is working fine now, it just isn't ideal. This would be an enhancement not a bug.

**Comment by rnugent3** [comment]
@codymccoy what is the status of this issue?

**Comment by codymccoy** [comment]
I don't want to deal with this under this contract. It isn't really a bad thing to have a name column in the database, it is just not required as far as I can tell. It isn't cognitively complex to do this work, but it might take a while to fix all the issues that it causes. Putting this on the backlog.
