### ISSUE TITLE
Convert PlottingLibraryCore, PlottingLibrary2D, and HecCs to NuGet References. 

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/HEC-FDA#165]
Will need to provide credentials to RAS NuGet Page.

**Comment by Brennan1994** [comment]
Stale. We're using a very specific version of the plotting library. @RyanM-RMA where does the source code for the plotting library we're using exist, or are we back in line with what RAS is using?

**Comment by rnugent3** [comment]
GitHub seems like an ideal location. 

This code is no longer maintained by the RAS team?
