### ISSUE TITLE
Fully implement the compute into the IAS editor 

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#168]
Currently (10/26/21) I am waiting for the new model to get put into FDA. This will include the new compute. Right now when the user clicks the "plot" button, we just fill the 4th plot with dummy data. Once we have the compute we need to actually run it when the user clicks "plot" button and make visible to the user any error messages that come out of the compute.

**Comment by rnugent3** [comment]
all that is left of this issue is some results reporting?

**Comment by rnugent3** [comment]
no. this is jus the IAS editor. I believe this issue has been resolved. @codymccoy please confirm.

**Comment by codymccoy** [comment]
This is resolved. Closing.
