### ISSUE TITLE
Exceptions when removing or renaming an element that is open in the editor and you save the editor.

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#174]
I am not really sure what the solution to this is. One approach would be to disable the element's menu items when it is open for edit. When we turn everything into a window this might not be as big of an issue depending on what we allow to be modal vs non-modal. This needs more investigation. It is possible that i handle this with some of the other elements. I know there was a problem with the IAS element.

**Comment by rnugent3** [comment]
Do we think that this is critical and we handle this now? I don’t have the schedule in front of me now, but I think that the window-handling task is toward the end of the period of performance. 

Or, is there a short-term fix you could do now and we re-evaluate when we get to the window task?

**Comment by rnugent3** [comment]
Thank you. 

Best,

R Nugent III

**Comment by rnugent3** [comment]
I do not see the exception being thrown. Really all we need now is better validation on this weird behavior, but this is not critical.

**Comment by rnugent3** [comment]
@codymccoy I think it would be reasonable to disable the element's menu items when it is open for edit. What is the level of effort to do that?

**Comment by codymccoy** [comment]
I just tested this and I don't get any exceptions. I think the original problem was occuring because we used to use the element's name to handle the database stuff. Now we are using an ID. If you rename the element while the editor is open and then click save, it just updates as you would expect. If you remove the element while the editor is open and then click save on the editor, nothing happens because it tries to find the element to update in the DB and it can't find it. 

@rnugent3 I think we can close this one.

**Comment by codymccoy** [comment]
This should be fixed now. I wrote a method in SavingBase called IDExistsInDB(). When "saving existing" if the id doesn't still exist then i switch it to do a "save new". This should be in main by the end of the day.

**Comment by rnugent3** [comment]
Cool! Thank you.

**Comment by rnugent3** [comment]
This works as expected
