### ISSUE TITLE
Deal with memory leaks from listening to fda cache events

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#179]
Ryan has identified that there are lots of memory leaks by listening to fda cache events using "+=". He says that we either need a "-=" somewhere or need to use weak references. He feels that this could take a couple days to clean it up all over FDA.

**Comment by codymccoy** [comment]
Notes from Ryan's code review of Cody's task 1 code:
Any time I see events added to like this (+=), I get concerned about memory leaks.
I don't see a -= anywhere, and from what I've seen in the code, the added/updated events are not weak event handlers.

This means any BaseEditorVM that gets created and adds itself as a listener is going to stick around until your static StudyCache object is destroyed, and every time those events are called it's going to also call into dead objects which wastes CPU time and can cause some serious and difficult to find bugs.

Probably the best approach to fixing it is turning those Added/Updated events weak, so you don't hold on to direct references, and future added/updated events will be weak.

**Comment by HenryGeorgist** [comment]
can you add a destructor to the baseeditorVM?

**Comment by HenryGeorgist** [comment]
is there a closing event?
