### ISSUE TITLE
The occupancy type editor needs to be looked at. Bug with plots not updating properly

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#181]
The occtype editor is one of the more complicated editors. There are probably several issues in there. I know one is that the plots are not updating correctly when switching between occtypes.

**Comment by rnugent3** [comment]
This issue seems like it comfortably fits within Task 5.

**Comment by rnugent3** [comment]
Let this issue reflect updating the plots only
