### ISSUE TITLE
Cancel looks like it will always be false, why check if it's true?

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/HEC-FDA#183]
https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/9843bc74b18c772ba9b130c52b7cb139ddd8c851/UserControls/CopyPasteDataGrid.vb#L157

It looks like  Cancel will always be false. It's a bool declared on the line above. Do we need to check on the next line if it's true?

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/141153588-44c120d2-a2ed-486c-adea-3b3bd876199e.png)
The cancel variable is passed by reference. The previewDeleteRows event might toggle the value.

**Comment by codymccoy** [comment]
I am unable to debug into the previewDeleteRows so i don't know what that code looks like. My guess is it checks to see if it is ok to delete the row. Like maybe we don't allow the deleting of the last row. It will toggle the Cancel variable and then we can just return instead of deleting the row.

**Comment by HenryGeorgist** [comment]
it is an event being raised - if someone is listening to that event, they can look at the row indices that are about to be deleted, and potentially set cancel to true if they want. it gets set externally based on a listener.

**Comment by HenryGeorgist** [comment]
it isnt a function, it is an event handle, which needs to be handled (by someone doing something).  @Brennan1994  in autogeneratingcolumns when you set the e.Handled = true, it is essentially the same. Someone else's code is changing stuff and the control is behaving based on their request.

**Comment by Brennan1994** [comment]
I understand this now. Thank you both for explaining
