### ISSUE TITLE
Make sure the full suite of tests work to produce deterministic EAD

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/HEC-FDA#19]
https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/main/ModelTests/OutputsTests/ResultTests.cs

**Comment by rnugent3** [comment]
I do not find the inherited class ComputeTestData referenced here: https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/b2751e4bc25c757017e28c9012215cec4fa0dd55/ModelTests/OutputsTests/ResultTests.cs#L12

There are other outdated references that would be easier to resolve than the inherited class, e.g. CreateFrequencyFunction(). 

Seems like I have two choices: (1) dig for this and other outdated references to attempt to make ResultsTests.cs work or (2) rewrite the entire test class from scratch. I am not sure which would take longer or be more useful, although I am leaning toward re-writing but with parsimony. @HenryGeorgist any advice?

**Comment by rnugent3** [comment]
Also - I am not sure what the full suite of tests are? We have in ResultTest.cs one unit test, which happens to be commented out. I originally envisioned only testing the integration of damage-frequency to confirm we get the correct EAD.

However, thinking about full suit of tests, I wonder whether we need to also write unit tests for rating functions, stage-frequency, aggregated stage-damage, and damage-frequency to close this issue?

**Comment by rnugent3** [comment]
I might be getting carried away, but I am also thinking that full suite would include tests of coordinates, coordinate functions, and function composition, among potentially other pieces involved in getting to EAD

**Comment by rnugent3** [comment]
Yes, thank you. I have that information from your instruction above. I am thinking about where to go from here, and what needs to get done to close the issue.

**Comment by HenryGeorgist** [comment]
> Also - I am not sure what the full suite of tests are? We have in ResultTest.cs one unit test, which happens to be commented out. I originally envisioned only testing the integration of damage-frequency to confirm we get the correct EAD.
> 
> However, thinking about full suit of tests, I wonder whether we need to also write unit tests for rating functions, stage-frequency, aggregated stage-damage, and damage-frequency to close this issue?

yes, we may need to tests much more, but it is hard to say. if the tests can work with the one referenced above, it will be a good indication, if not, we will have to test each component part and build up from there.
