### ISSUE TITLE
Error is produced after saving a a new damage curve

### ISSUE THREAD

**Issue by dezidizon** [HydrologicEngineeringCenter/HEC-FDA#190]
The following error was produced when trying to save a damage curve that was created. 

![image](https://user-images.githubusercontent.com/47678178/141806499-13f01596-a217-4e15-98e4-3c3029588e81.png)

In the editor for the Aggregated Stage Damage Relationship, I attempted to create damage curves manually. I added two curves - one for each impact area available in the impact area set of the study. Each curve was set with unique damage categories. The error was produced after the configurations in the editor were made.

![image](https://user-images.githubusercontent.com/47678178/141806881-2598e527-d7a4-405f-bb91-80a61a258a4f.png)

**Comment by codymccoy** [comment]
I encountered the same bug. This should be covered in Task 4: Aggregated stage-damage compute.

**Comment by codymccoy** [comment]
this should be fixed. Ready for testing.

**Comment by dezidizon** [comment]
Tested and verified fixed in HEC-FDA-2.0-Snapshot task4 1_6_22.
