### ISSUE TITLE
Damage Category options do not correspond to selected alternate option of stage damage

### ISSUE THREAD

**Issue by dezidizon** [HydrologicEngineeringCenter/HEC-FDA#192]
In the study, there were two stage damage relationships available.
**aaa**
Curve 1 - North Area - Occupancy Type Group -> IND
Curve 2 - South Area - Occupancy Type Group -> AUTOS

**Option A**
Curve 1 - South Area - Occupancy Type Group -> RES
Curve 2 - South Area - Occupancy Type Group -> COM

When selecting the Stage Damage of "Option A" which is the alternate (not first option), the displayed option in the Damage Category drop down would display "Occupancy Type Group -> RES". But when the drop down is expanded, the options for the first stage damage option will be displayed.

![image](https://user-images.githubusercontent.com/47678178/141827804-6b9088df-84cb-450f-8fce-2ac997f98759.png)

**Comment by codymccoy** [comment]
Good find. This is fixed. I needed to switch the "List" to an observable collection so that the UI picks up the change. It doesn't seem possible to create a new stage damage element at this time so I added a second one through the database. I assume that is what you had to do also.
