### ISSUE TITLE
Exception produced when removing Lateral Structure from the Study Tree

### ISSUE THREAD

**Issue by dezidizon** [HydrologicEngineeringCenter/HEC-FDA#193]
After removing a Lateral Structure from the Study Tree, the following exception was produced.
![image](https://user-images.githubusercontent.com/47678178/141832629-93995c56-3c4c-49a1-a02b-1d388a7f6b59.png)

**Comment by codymccoy** [comment]
Fixed.

**Comment by rnugent3** [comment]
issue resolved
