### ISSUE TITLE
Prompt user to save edits to the IAS editor when closing without saving changes

### ISSUE THREAD

**Issue by dezidizon** [HydrologicEngineeringCenter/HEC-FDA#196]
When edits have been made in the Impact Area Scenario editor (either during the creation or editing of an impact area scenario) and then the user closes the editor without saving, the user should be prompted on whether the changes should be saved.

**Comment by rnugent3** [comment]
This is related to #299. Id like to see this built in, but given a moderate level of effort, I would not say is critical.

**Comment by codymccoy** [comment]
This is now complete in the Alternative_Compute_Results branch.
