### ISSUE TITLE
Improve default size of Annual Exceedance Probabilities Threshold window

### ISSUE THREAD

**Issue by dezidizon** [HydrologicEngineeringCenter/HEC-FDA#197]
Improve the size of the Annual Exceedance Probabilities Threshold window when first loaded. Currently, the window is smaller than expected. 
![image](https://user-images.githubusercontent.com/47678178/141872626-48947fc4-a45e-4d7f-938d-634e8d30fc8f.png)
This should at least allow for displaying the table when first loaded.
![image](https://user-images.githubusercontent.com/47678178/141873055-d476dc32-235e-4793-9ef7-2857e3097d02.png)

**Comment by codymccoy** [comment]
I would prefer to address this in the task that deals with changing everything over to be windows instead of tabs.

**Comment by rnugent3** [comment]
Makes sense to me.

**Comment by rnugent3** [comment]
I think the size is fine, but I would like the title of the window changed from "Annual Exceedance Probabilities Thresholds" to "System Performance Thresholds"
