### ISSUE TITLE
Prevent duplicate Threshold Type and Threshold Value combinations

### ISSUE THREAD

**Issue by dezidizon** [HydrologicEngineeringCenter/HEC-FDA#198]
In the Annual Exceedance Probabilities Thresholds table, entries with the same combination of Threshold Type and Threshold Value are allowed.  During testing, I was able to add a Threshold Type and Threshold Value combination already used by an existing entry. This was successfully saved.
![image](https://user-images.githubusercontent.com/47678178/141873943-7796967f-9ac8-4271-a913-3f8ad730f719.png)

**Comment by codymccoy** [comment]
I added validation that checks to see if all rows are unique pairings.

**Comment by rnugent3** [comment]
this issue has been resolved.
