### ISSUE TITLE
Incorporate SciChart from NuGet instead of binaries

### ISSUE THREAD

**Issue by RyanM-RMA** [HydrologicEngineeringCenter/HEC-FDA#201]
Let's cut over to the newer version of the PlottingLibrary from the RAS team so we can use NuGet instead of holding on to specific binaries.
This will also involve pushing code from the Perforce PlottingLibrary into the RAS PlottingLibrary API, and potentially changing FDA code to use the existing RAS API.

RAS PlottingLibrary code:
https://bitbucket.hecdev.net/projects/RAS/repos/scicharthecplot/browse

**Comment by Brennan1994** [comment]
Have you already discussed pushing changes with Anton, or can I help facilitate that? I want to make sure everybody is on board and cool with that.

**Comment by RyanM-RMA** [comment]
> Have you already discussed pushing changes with Anton, or can I help facilitate that? I want to make sure everybody is on board and cool with that.

I've told him that I'll be making changes, but nothing about the specifics yet.  I want to see what I'll need to change first.  We talked branching strategies, and how I'll be merging code into main via branch + PR's.  Cody will be reviewing my submissions, so we can maintain review standards, and I have access to their rocket chat channel to let them know what I'm submitting and when to submit it.

**Comment by RyanM-RMA** [comment]
@codymccoy I want to say we talked about this a little bit I think, but I'm not sure to what extent.  Can you check to make sure you have access to the PlottingLibrary repos here:
https://bitbucket.hecdev.net/projects/RAS/repos/scicharthecplot/browse

If not, please talk with @Brennan1994 to get added.

**Comment by codymccoy** [comment]
@Brennan1994 I do not have access to the link Ryan provided above. It says 401 access denied with a scull and crossbones.
