### ISSUE TITLE
Figure out how to debug into NuGet Packages

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/HEC-FDA#204]

**Comment by rnugent3** [comment]
@Brennan1994 this is the issue you just resolved, yes?

**Comment by Brennan1994** [comment]
This issue has been resolved. Debugging flags are now embedded into the .dlls, so we don't need pbds. IF you want to debug into something, you'll be prompted to pull up the source code from elsewhere on your computer, or decompile the dll to click through it.
