### ISSUE TITLE
Do we allow renaming the entire study?

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#207]
I have come across some code in the StudyElement and the Study Properties classes trying to rename the study. I remember that we tried to get this to work and failed. It was difficult to rename the study files while the study is in use. I think the files are locked until the program closes. This needs some investigation if we want to be able to rename the study.

**Comment by rnugent3** [comment]
I don’t think we need to worry about being able to rename the study right now. That capability does not exist for FDA 1. I think if users need to update something about the name, that can happen in the study description.

**Comment by codymccoy** [comment]
Ok, sounds good to me. It seems like it would be simple on the surface, but we couldn't figure it out last time we tried to do it.

**Comment by rnugent3** [comment]
I hear you. Thanks for bringing this up.
