### ISSUE TITLE
Investigate Consequences_Assist.DataGridRowItem

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#209]
I saw a few instances of classes that were implementing this data grid row item class. I got rid of the one that I was working with directly. I am not sure what its purpose is, but I am guessing we don't need to be implementing this class anywhere in FDA. If we have time we should search these out and investigate and get rid of them.

**Comment by rnugent3** [comment]
@Brennan1994 @codymccoy you guys mentioned this issue during our meeting yesterday. Do we plan to address this?

**Comment by codymccoy** [comment]
I was able to delete 5 classes that were not being used including the data grid row item mentioned in the title of this issue. 

ConsequencesAssist will still be used in FDA for the file and folder browser.
