### ISSUE TITLE
Occtype Editor "Save All" bug

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#213]
If you click the "Save All" button it displays a report that doesn't even show anything (assuming you haven't changed anything. This needs to be updated. Maybe this UI needs to be changed? It looks to me like the only way to save an occtype group name change is to click the Save All button. This will need to update the group names in the inventory table if want to continue down this road. 
Manager.SaveModifiedGroups() should update the inventory table. Do something similar to what Cody did in Manager.UpdateOccTypeInCache(). 

![image](https://user-images.githubusercontent.com/47757848/146258990-07949657-6400-4c45-a0cc-f28da80f7cec.png)

**Comment by rnugent3** [comment]
@codymccoy was this resolved as part of the occupancy types editor work?

**Comment by codymccoy** [comment]
@rnugent3 Yes, this is no longer an issue.
