### ISSUE TITLE
Unhandled exception produced when importing occupancy type text file with duplicate values

### ISSUE THREAD

**Issue by dezidizon** [HydrologicEngineeringCenter/HEC-FDA#216]
When I attempted to import multiple occupancy type text files with duplicate values, the following unhandled exception is produced after attempting to import all the files.

Steps to reproduce:
1 - Have two occupancy type text files with duplicate values. This could be done by cloning one occupancy text file and renaming the other file. In my case, I used the attached files.
2 - I added both files to the Occupancy Type Import. 
3 - I attempted to access the Occupancy Type Group editor. And the following exception is produced.

![image](https://user-images.githubusercontent.com/47678178/146831605-48db382c-7253-4ebd-85e5-320cda217e99.png)

**Comment by codymccoy** [comment]
This is a bug in the occtype editor. I think that should fall under task 14.
