### ISSUE TITLE
Structure Damage values not displayed in table 

### ISSUE THREAD

**Issue by dezidizon** [HydrologicEngineeringCenter/HEC-FDA#217]
During testing, I observed that values in the Occupancy Type editor's Structure Damage and Content Damage tables were no longer being displayed compared to an FDA build from November 10, 2021. 

Using SQLite, I verified in the study's sqlite file that there are values for occupancy types. However, in the latest release from December 13, 2021, the values are no longer displayed in the Occupancy Type editor. 

Previous Build:
![image](https://user-images.githubusercontent.com/47678178/146852445-36fb4358-c571-417a-b820-4ec93a3218af.png)

Current Build:
![image](https://user-images.githubusercontent.com/47678178/146852467-8b9524e6-01f8-45a2-9b67-647ce5edaffa.png)

**Comment by codymccoy** [comment]
I am not sure what could have caused this. I have made no changes to the occtype editor. Might be something with SciChart. Maybe when we updated to a newer version or something. I don't think these plots ever quite worked correctly. This should be moved to task 14.

**Comment by codymccoy** [comment]
Update: This is definitely a bug. Seems to be affecting normal distributions. I don't think i had anything to do with this change. I think something happened in the model or statistics. This logic routes through Bob's importer and then i translate it into FDA 2.0 curves. It goes through some factories in the model and statistics and I think the median is getting set, but the mean isn't? I think Will made some updates so i should get the latest on stats before debugging further.
![image](https://user-images.githubusercontent.com/47757848/148291739-10a085a0-66fa-476a-94f7-f6cb205e9472.png)

**Comment by rnugent3** [comment]
You're right - looks like IDistributedOrdinateFactory calls on the IDistribution factories which have since been nuked.
