### ISSUE TITLE
Occupancy Type's values are not imported

### ISSUE THREAD

**Issue by dezidizon** [HydrologicEngineeringCenter/HEC-FDA#218]
Values for occupancy types are not imported. This results in no values being displayed in the table. Using SQLite, I verified that no values have been saved for the study for occupancy types. 

Steps to reproduce:
1. I created a new study.
2. I accessed the Import Occupancy Type dialog.
3. I loaded the file "DamCatsAndOcctypes.txt" and committed the new Occupancy Type Group import.
4. I accessed the Occupancy Type Editor.
5. The table values were empty except for the stage.
6. In SQLite, I verified that there were no values saved for the Structure Damage or Content Damage.

**Comment by codymccoy** [comment]
This is an occtype editor bug and should go under task 14.

**Comment by rnugent3** [comment]
In the design document, we put the occupancy type bugs under this task - not task 14. I think most of the known bugs were put under a task other than 14.

**Comment by rnugent3** [comment]
This issue is related to the occupancy type import work so should be completed with Task 5.

**Comment by rnugent3** [comment]
this issue has been resolved.
