### ISSUE TITLE
Validation messages for missing Structure Inventory Shapefile and required attributes in the first page of the Import Structure Inventory panel

### ISSUE THREAD

**Issue by dezidizon** [HydrologicEngineeringCenter/HEC-FDA#219]
When moving to the next page of the Import Structure Inventory panel, the following messages are expected when required files are missing. Currently, the priority of which fields to populate seems to be out of order. The following cases were done while filling out the required attributes with the First Floor Elevation selected.

Current behavior after clicking the "Next" button:
- When the Structure Inventory Shapefile is missing, the user is informed that the First Floor Elevation Value is missing.
  - Expected: The user should be informed that the Structure Inventory Shapefile should be selected.
- When the Structure Inventory Shapefile is missing and the Structure ID is selected, the user is informed that the First Floor Elevation Value is missing.
  - Expected: The user should be informed that the Occupancy Type should be selected.
- When the Structure Inventory Shapefile is selected and the First Floor Elevation Value is selected, the user is informed that the Structure ID is then required.

The expected priority when informing the user that required files and attributes are missing should have a flow from top to bottom.
1. Structure Inventory Shapefile

2. a First Floor Elevation
2.a.i Structure ID
2.a.ii Occupancy Type
2.a.iii First Floor Elevation Value
2.a.iv Structure Value

2.b Ground Elevation and Foundation Height

2.b.i Ground Elevation Source - Terrain File
2.b.i.1 Structure ID
2.b.i.2 Occupancy Type
2.b.i.3 Foundation Height
2.b.i.4 Structure Value

2.b.ii Ground Elevation Source - Structures File
2.b.ii.1 Structure ID
2.b.ii.2 Occupancy Type
2.b.ii.3 Foundation Height
2.b.ii.4 Ground Elevation Value
2.b.ii.5 Structure Value

**Comment by codymccoy** [comment]
I did a total refactor of the validation system. I now display the total list of all the errors in the error message in order from top to bottom. I don't have a check for a missing file. If there isn't a file then the selections will be empty and that will be displayed to the user. This refactor was big enough that you should check all the validation stuff again.

**Comment by dezidizon** [comment]
Tested and verified fixed in HEC-FDA-2.0-Snapshot 12_22_21
