### ISSUE TITLE
Exception produced when importing terrain files for an FDA study

### ISSUE THREAD

**Issue by dezidizon** [HydrologicEngineeringCenter/HEC-FDA#220]
When I attempted to import a terrain, the following exception was produced. 

Steps to reproduce:
1. Access the Import Terrain file
2. Select a .tif file to import
3. Click the OK button in the Import Terrain panel.
4. The exception is produced.
![image](https://user-images.githubusercontent.com/47678178/146966000-ccfdadaf-86c5-4765-9425-b6fa6d1d1e77.png)

**Comment by codymccoy** [comment]
This was a change we made that we thought was an improvement but caused this error and probably others. I reverted it back to the way it was. Fixed.

**Comment by dezidizon** [comment]
Tested and verified fixed in HEC-FDA-2.0-Snapshot task4 12_22_21
