### ISSUE TITLE
Duplicate Values for Structure ID are not flagged when importing Structure Inventory

### ISSUE THREAD

**Issue by dezidizon** [HydrologicEngineeringCenter/HEC-FDA#222]
When the values under the Structure ID's attribute are duplicated in the source structure inventory shapefile, the import process does not catch and prevent the import process because of the duplicated Structure ID values. 

Steps to reproduce:
1. I created a copy of LowerCacheCreekStructures.shp and labeled it LowerCacheCreekStructuresDEZIQA.shp.
2. In QGIS, I edited the attribute table of the shapefile so that the first two rows have the same value under the APN column.
![image](https://user-images.githubusercontent.com/47678178/146982885-20525f8d-dd0b-4e08-b29d-c94c1524c6b5.png)
3. In the Import Structure Inventory panel, I mapped the APN column as the attribute for the Structure ID.
4. I completed the rest of the required attributes for the Structure Inventory and committed the new Structure Inventory.
5. The Structure Inventory was created without any errors produced regarding duplicate values for the Structure ID.

Additionally, I tried assigning HT_Found which had duplicating values in the column. I then mapped this as the Structure ID attribute and I was still able to create the Structure Inventory without any error produced for duplicate values.

**Comment by codymccoy** [comment]
Looks like i just forgot to include that validation check. It is fixed now.

**Comment by dezidizon** [comment]
Tested and verified fixed in HEC-FDA-2.0-Snapshot 12_22_21
