### ISSUE TITLE
Cannot select attributes to map to Optional Attributes of Beginning Damage Depth, Year In Construction, Notes/Metadata, and Other

### ISSUE THREAD

**Issue by dezidizon** [HydrologicEngineeringCenter/HEC-FDA#223]
Optional attributes cannot be mapped for Beginning Damage Depth, Year In Construction, Notes/Metadata, and Other. The dropdown is empty for each of these optional attributes.

![image](https://user-images.githubusercontent.com/47678178/146984698-94ccc32c-4708-4642-b915-a4d80cc6df79.png)

**Comment by codymccoy** [comment]
I just forgot to load those rows. It is fixed now.

**Comment by dezidizon** [comment]
Tested and verified fixed in HEC-FDA-2.0-Snapshot 12_22_21
