### ISSUE TITLE
Finish writing stage damage details file

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#225]
The starting point is AggregatedStageDamageElement.ExportDetails. I wrote several comments outlining how i think this should go. I have a file writing out. I show how to pull some of the desired info from the cache. I create a datatable and write some values out. It basically just needs the correct details added to the datatable. Talk to Cody if you need any help getting the data you need.

**Comment by rnugent3** [comment]
@Brennan1994 I don't see this work in the commit. We now have the capability to write the equivalent of the FDA_StructDetail.out file?
