### ISSUE TITLE
Curve numbers do not update to expected order when removing a stage-damage curve

### ISSUE THREAD

**Issue by dezidizon** [HydrologicEngineeringCenter/HEC-FDA#226]
When removing a curve from the Stage-Damage Curves table, the Curve number(s) do not update as expected when a curve is removed in between two curves. When I removed the fourth curve from the table, the 5th curve does not update to be the 4th curve. When editing the Aggregated Stage Damage Relationship, the Curve numbers are as expected.

![image](https://user-images.githubusercontent.com/47678178/147263919-c52fdad2-ca41-44fe-bac1-82e6d1b99f41.png)

**Comment by codymccoy** [comment]
This was by design. The curve number is simply an ID so that we can message the user and tell them which curve is in error. What does @rnugent3 think?

**Comment by rnugent3** [comment]
I agree - this is by design. We might make this more clear to the user by labeling the column “Curve ID” … what do you guys think? 

Best,

R Nugent III
