### ISSUE TITLE
Stage-Damage Curves table displays default Impact Area when editing an existing Aggregated Stage Damage Relationship

### ISSUE THREAD

**Issue by dezidizon** [HydrologicEngineeringCenter/HEC-FDA#227]
When creating an Aggregated Stage Damage Relationship, the Stage Damage Curves table defaults to the first available Impact Area. After selecting other values for the impact area and damage category, saving, then editing the created Aggregated Stage Damage Relationship, the first row in the Stage-Damage Curves table reverts to the default value.

Default selections for Impact Area and Damage Category when beginning creation:
![image](https://user-images.githubusercontent.com/47678178/147266486-14d96b1a-21ea-47e0-950b-257eae3d254d.png)

Created Stage-Damage Curves:
![image](https://user-images.githubusercontent.com/47678178/147266564-5abeb2e9-ef2f-4e5d-8b3b-cb8a5af44a5b.png)

Stage-Damage Curves when editing:
![image](https://user-images.githubusercontent.com/47678178/147266634-79e36ebb-30d2-4b33-a534-f9c860ca35a1.png)

When I looked at the Study through SQLite, it looks like the selected impact area is "-1". 
![image](https://user-images.githubusercontent.com/47678178/147266965-7cccf69a-4c4b-476a-a337-0b99317a5278.png)

**Comment by dezidizon** [comment]
This does not seem to be an issue when the stage-damage rating table data is configured for each curve. The issue occurs when adding stage-damage curves then saving without configuring the rating data first.

**Comment by codymccoy** [comment]
[3:23 PM] Deziree Dizon
it's when it's the first Aggregated Stage Damage Relationship I create

[3:23 PM] Deziree Dizon
I had to make a new study, import an impact area and Occupancy types

[3:23 PM] Deziree Dizon
then create the new Aggregated Stage Damage Relationship

[3:24 PM] Cody McCoy
and then just switch the impact area and dam cat and click save

[3:24 PM] Cody McCoy
and then open it back up

**Comment by codymccoy** [comment]
Ok, this was an interesting one. The issue ultimately was not with the stage damages but with the way the impact areas were being saved the very first time they were imported. This is why we only see this when making a new study. You will see it if you just delete the impact area and import a new one also. It is now fixed.

**Comment by dezidizon** [comment]
Tested and verified fixed in HEC-FDA-2.0-Snapshot task4 1_6_22.
