### ISSUE TITLE
Stage-Damage rating data table does not check for monotonically increasing data

### ISSUE THREAD

**Issue by dezidizon** [HydrologicEngineeringCenter/HEC-FDA#228]
When configuring then saving the stage-damage rating data, the editor does not prevent creating a non-monotonically  increasing stage-damage rating. 

In the stage-damage rating data table, I entered the following points. The data was still allowed.
![image](https://user-images.githubusercontent.com/47678178/147272886-4028f3c1-c8b3-493e-93b6-ca9f7fe0005f.png)

**Comment by codymccoy** [comment]
I think this should be addressed in task 3 which deals with updating this table control.

**Comment by rnugent3** [comment]
Based on our discussion regarding the plotting of depth-percent damage functions within the occupancy type editor, this work should fall under the stage-damage task.

**Comment by rnugent3** [comment]
this issue has been resolved.
