### ISSUE TITLE
Creating a Stage-damage curve with a single point not prevented

### ISSUE THREAD

**Issue by dezidizon** [HydrologicEngineeringCenter/HEC-FDA#230]
Creating a stage-damage curve with a single point of rating data is allowed in the editor. I created a curve with only one point of rating data and this was still added to the study after saving. 

One of the minimum requirements for a stage-damage curve is to have at least two points of data.

**Comment by codymccoy** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/47757848/147294144-a78f36ff-9281-4bb3-bf24-ecc1bf541964.png)

**Comment by dezidizon** [comment]
Tested and verified fixed in HEC-FDA-2.0-Snapshot task4 1_6_22.
