### ISSUE TITLE
Cannot import files for Water Surface Elevation in FDA study

### ISSUE THREAD

**Issue by dezidizon** [HydrologicEngineeringCenter/HEC-FDA#231]
When attempting to import files for the Water Surface Elevation, the file selector does not show the available .tif files to use for the Water Surface Elevation. 

![image](https://user-images.githubusercontent.com/47678178/147280999-5cccc86c-969e-4ad3-bef7-9e838845649a.png)

**Comment by codymccoy** [comment]
Yes, there is a bug here. The validation for this form is in the WaterSurfaceElevationImporterVM.RunSpecialValidation(). It is supposed to pop up a message box. It is using "customMessageBox" which was something we were starting to do but abandoned. I think in one of the tasks we are going to change some of the rules of what is valid to import so i don't want to work on this bug at this time.

**Comment by codymccoy** [comment]
You can always import the B8 files. The reason the b3 files didn't work is because there was less than 8 files in the folder.

**Comment by rnugent3** [comment]
I am agreeable. Polishing the validation rules falls under Task 13.
