### ISSUE TITLE
Warn user when existing Calculated Aggregated Stage Damage Relationship is now missing water surface elevation or structure inventory

### ISSUE THREAD

**Issue by dezidizon** [HydrologicEngineeringCenter/HEC-FDA#232]
Given a calculated aggregated stage damage relationship has already been created using an existing water surface elevation and structure inventory. When the water surface elevation or structure inventory used is deleted and then the calculated aggregated stage damage relationship is edited, the user should be notified of the missing water surface elevation or structure inventory and ask the user to reselect and recompute for the stage damage relationships.

**Comment by rnugent3** [comment]
@codymccoy any thoughts on this? seems like relevant messaging to me.

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/171284627-719091a6-522d-488e-967d-d2c4ce18fa6c.png)

![image](https://user-images.githubusercontent.com/47757848/171284649-e94b5a2c-da61-4b7a-81f1-addcc17bc1e8.png)

These are the messages that i am popping up. Let me know if you want the wording changed.

**Comment by codymccoy** [comment]
@rnugent3 can you just verify that the wording of these messages in the pics above are adequate? If so, we can close this one out.

**Comment by rnugent3** [comment]
Please use the following wording:

The previously selected hydraulics data set used in the compute of these aggregated stage-damage functions was deleted. Please select a new hydraulics data set and recompute. 

Best,

R Nugent III

**Comment by codymccoy** [comment]
I updated the missing inventory message to this:
"The previously selected inventory used in the compute of these aggregated stage-damage functions was deleted. Please select a new inventory and recompute."

And updated the missing hydros to be the message you included above.

This fix is in Github_Bug_Fixes

**Comment by rnugent3** [comment]
behaves as expected
