### ISSUE TITLE
Structure Detail is exported for manually created Aggregated Stage Damage Relationship

### ISSUE THREAD

**Issue by dezidizon** [HydrologicEngineeringCenter/HEC-FDA#233]
Structure Detail is exported for manually created Aggregated Stage Damage Relationship. This is only expected for computed aggregated stage damage relationship.

**Comment by codymccoy** [comment]
Fixed.

**Comment by dezidizon** [comment]
Tested and verified fixed in HEC-FDA-2.0-Snapshot task4 1_6_22.
