### ISSUE TITLE
Exception is produced when attempting to rename Aggregated Stage Damage Relationship

### ISSUE THREAD

**Issue by dezidizon** [HydrologicEngineeringCenter/HEC-FDA#234]
When attempting to rename an existing Aggregated Stage Damage Relationship, the following exception is produced.

Steps to reproduce:
1. Select an existing Aggregated Stage Damage Relationship.
2. Click the "Rename" option from the selected Aggregated Stage Damage Relationship.
3. In the Rename dialog, update the name of the Aggregated Stage Damage Relationship.
4. Click the "OK" button.
5. The following exception will be produced.
![image](https://user-images.githubusercontent.com/47678178/147292365-26e39b1d-06b4-4b78-bba3-d46da37b952a.png)

**Comment by codymccoy** [comment]
Fixed.

**Comment by dezidizon** [comment]
Tested and verified fixed in HEC-FDA-2.0-Snapshot task4 1_6_22.
