### ISSUE TITLE
Ground Elevation not imported for Structure Inventory when using Terrain File

### ISSUE THREAD

**Issue by dezidizon** [HydrologicEngineeringCenter/HEC-FDA#239]
When using a Terrain File to determine the Ground Elevation for a structure inventory, the ground elevation value is not imported. 

To verify that the Ground Elevation is imported for a Structure Inventory, I used SQLite to access the database file. I also used the following files from the Sample Data\LCC folder
Terrain File: LCC\Terrain\TGrid.tif
Impact Area: LCC\DamageReaches\Econ_Impact_Areas.shp
Structure file: LCC\Economics\LowerCacheCreekStructures.shp

In QGis, I have the terrain file and structure file overlaid and the terrain file covers all the structures in the map.

![image](https://user-images.githubusercontent.com/47678178/148583624-ad868af8-d415-45f3-910d-03ba6e2b6c29.png)

**Comment by codymccoy** [comment]
This should be fixed now.

**Comment by dezidizon** [comment]
Tested and verified fixed using HEC-FDA-2.0-Snapshot task4 1_10_22.
