### ISSUE TITLE
Cannot import Water Surface Elevation in FDA v2.0 build produced on January 6, 2022

### ISSUE THREAD

**Issue by dezidizon** [HydrologicEngineeringCenter/HEC-FDA#240]
Using the build generated from January 6, 2022, I was unable to import tif files for Water Surface Elevations. This was previously working.

After selecting a source directory and loading the tif files to import for water surface elevation then clicking the OK button, there is no feedback in the FDA application.

**Comment by codymccoy** [comment]
Dez was trying to import from the "B3" folder which only has 6 files in it. There is logic that only allows folders that have 8 files. The "rules" for importing might need to be thought out more. I think they are defined more in the clean document. There needs to be messaging to the user when we do not allow an import.

**Comment by rnugent3** [comment]
The logic requiring 8 is good. Some messaging sounds important. 

In the design document, we discuss modifying the import logic to look for 8 folders for a given set of hydraulics - to accommodate RAS output - is this how we are working now?

**Comment by rnugent3** [comment]
has this issue not been resolved?

**Comment by codymccoy** [comment]
This issue is fixed. We have good messaging and hydraulics import successfully.
