### ISSUE TITLE
Document build process

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#244]
Please add some information about how to build the HEC-FDA software to the README

**Comment by rnugent3** [comment]
I think in addition to the build process we should have some help on getting set up with the dependencies in the README, too. Similar to the discussion here: https://github.com/HydrologicEngineeringCenter/HEC-FDA/discussions/170

We see folks across the agency having trouble getting set up with the FDA repositories, and I am struggling with go-consequences, because getting set up is not exactly easy, except perhaps for the whiz kids. 

After all, if the code is relatively inaccessible for use, is it really open source?

**Comment by rnugent3** [comment]
@Brennan1994 FYSA this is one of our very few remaining incomplete DevOps goals. We should make sure to target getting this issue resolved by August, please.

**Comment by Brennan1994** [comment]
Done

**Comment by rnugent3** [comment]
Thank you! This was one of our last FY22 DevOps goals yet to complete. I think there is just one left. WOoHOo!
