### ISSUE TITLE
Description pop out window can stay popped out after closing

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#246]
If you pop the description window out and then close the parent form, the description window stays open. If you then try to pop it back in it throws an exception.
Keep in mind that the plan is to get rid of the tabs and move everything into its own window. That might make a difference in how this problem is solved.

**Comment by HenryGeorgist** [comment]
good catch. is there an event fired when a tab or window is closed that the description window can listen to? if not we may need to figure out the right place to make (and throw) that event.

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/149389970-91b87c54-a52e-42bc-87ac-b17e4db3d135.png)

**Comment by codymccoy** [comment]
The tabs are going away as per task 11:
![image](https://user-images.githubusercontent.com/47757848/149390189-4e1cf2c0-308b-4d62-9b61-8df086f2ecd3.png)
We probably don't want to spend much time making this work for tabs, if we are going to remove the tabs in the future.

**Comment by codymccoy** [comment]
oops, second pic was supposed to be this:
![image](https://user-images.githubusercontent.com/47757848/149390329-20d0fc16-9c0d-4544-b1ec-8dbbc3cd6775.png)

**Comment by codymccoy** [comment]
The simplest solution is probably to just get rid of the pop out functionality, but then it is less cool.

**Comment by rnugent3** [comment]
I think that the description box is plenty long enough. Let's just get rid
of the pop out functionality.

**Comment by codymccoy** [comment]
I commented out the arrow button so that the description will not be able to pop out.

**Comment by rnugent3** [comment]
this issue is resolved, we're not popping out description, the box is plenty long enough
