### ISSUE TITLE
Default levee curve

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#248]
if user selects the default levee curve, then within the VM a levee curve needs to be created with two points:

(stage  = lowest stage of stage frequency or rating curve, prob of failure = 0 as a deterministic distribution) 
(stage = top of levee elevation, prob of failure = 1 as a deterministic distribution)

**Comment by rnugent3** [comment]
there must also be a coordinate with stage = (top of levee elevation) - epsilon (where epsilon is a very small number) and the probability of failure = 0. 

We don't want the model interpolating the probability of failure between the two coordinates. There should be a discontinuous relationship between stage and probability for the default curve.

**Comment by rnugent3** [comment]
I thought to include this in the model, but it sounds like that is not the appropriate place. I am taking the default levee out of the model, but I'll include the default levee code I wrote here in this issue for reference.

**Comment by rnugent3** [comment]
```            public SimulationBuilder withLevee(bool useDefaultFunction, double topOfLeveeElevation)
            {
                double epsilon = 0.0001;
                //TODO: What do we think about this? My main concern is hard-wiring the lowest stage
                //also need to think about the ID
                double[] leveestages = new double[] { 0.0d, topOfLeveeElevation - epsilon, topOfLeveeElevation };
                IDistribution[] leveefailprobs = new IDistribution[3];
                for (int i = 0; i < 2; i++)
                {
                    leveefailprobs[i] = new Statistics.Distributions.Deterministic(0); //probability at the top must be 1
                }
                leveefailprobs[2] = new Statistics.Distributions.Deterministic(1);
                UncertainPairedData levee = new UncertainPairedData(leveestages, leveefailprobs, "stages", "failure probabilities", "default function", "internally configured default function", 0);
                _sim._levee_curve = levee;
                _sim._topOfLeveeElevation = topOfLeveeElevation;
                return new SimulationBuilder(_sim);
            }```

**Comment by rnugent3** [comment]
this code has been revised for use in the ComputeMeanEADAndPerformanceWithIterationsAndLevee_Test() in StudyDataResultsTests.cs within fda-model-test

**Comment by codymccoy** [comment]
We are already doing something similar. When creating a levee, if the user doesn't define a failure function with it, we create one with two points. The first point is at the top of levee and has a zero probability of failure. The second point is epsilon above top of levee and has a 100% failure.
![image](https://user-images.githubusercontent.com/47757848/150601861-cfaadd88-6439-4dee-9267-816d32fffbc7.png)

**Comment by rnugent3** [comment]
this works for me.
