### ISSUE TITLE
Investigate LP3 Synthetic Sample

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#250]
Can users rely on SSP to come up with the LP3 moments using a synthetic sample? (i.e. 3 exceedance probabilities and their 3 flow values).

**Comment by HenryGeorgist** [comment]
im not sure, do we really want to allow that?

**Comment by HenryGeorgist** [comment]
can we just rely on people telling us the mean standard deviation and skew and equivalent years of record?
No data fitting, no anything else, just give us that.
We can be completely agnostic to how it is derived.

**Comment by rnugent3** [comment]
I don't think we want to do this for new studies - this was a feature of 1.X.x that was helpful for users because they could take flows and their exceedance probabilities from the WSP and generate an LP3. We won't have flows in our hydraulics data so it does not seem helpful to have this capability. 

This comes up for us when importing LP3 from V. 1.4.3 - in some cases, the users will have LP3 functions created as described above, and we won't be able to take that study data and create an LP3 for them

**Comment by rnugent3** [comment]
Ideally, we would not leave users in a situation where they could develop an LP3 before but can't anymore

**Comment by HenryGeorgist** [comment]
ah. does fda store the derived parameters for the lp3?

**Comment by rnugent3** [comment]
doesn't look like it, based on what I saw form the import logic, only the exceedance probabilities and flows are stored. I think the user could see the derived parameters in the UI, depending on the UI being accessible.

**Comment by rnugent3** [comment]
FDA stores the derived parameters and @HenryGeorgist wrote some logic to get access to the parameters in the dbf. This issue can be closed - but we'll need to do some work on the front end to make use of the logic.
