### ISSUE TITLE
Rules for uncertainty parameters

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#254]
We need to write down the way that FDA 1.4.3. uses uncertainty parameters and therein how to import the parameter values for each distribution type and parameter. 

Relevant references include Appendix D of the user's manual and the attached uncertainty parameter report. 

I plan to assign this to Jordan.

**Comment by rnugent3** [comment]
[Structure Parameter Test.pdf](https://github.com/HydrologicEngineeringCenter/HEC-FDA/files/7954629/Structure.Parameter.Test.pdf)

**Comment by rnugent3** [comment]
it would be best to write the rules in consideration of the fda-statistics distribution constructors.

**Comment by HenryGeorgist** [comment]
maybe also based on the fda-statistics validation rules for each distribution type?

**Comment by rnugent3** [comment]
hmmmm. I like it, but enforcing the validation on the imported data makes me feel a little uncomfortable because that would be getting close to again telling the user: we accepted your data before, but we do not accept the data anymore, which brings me to the same question, what do we do with a 1998 fda study where the H&H no longer exists?

**Comment by rnugent3** [comment]
who's problem would be to come up with new H&H modeling to accommodate our new validation? who will pay for it?

**Comment by HenryGeorgist** [comment]
fair enough - though ultimately in simulation we check validation on the objects, completely unaware of where they come from...

**Comment by HenryGeorgist** [comment]
in CWMS and WAT we use CTRL+ click to "force" a compute. i suppose we could probably make some sort of form "perform an unsafe compute and acknowledge that you are doing something we generally frown upon...."

**Comment by rnugent3** [comment]
if we sample a normal distribution using a random number between 0 and 1 as an input to inverse CDF, do we get the same result  with (1) multiplying the mean (100%) and standard deviation (CV) by the structure value and then calling the inverse CDF and (2) using the mean 100% and standard deviation (CV) then multiplying the result by the structure value

**Comment by rnugent3** [comment]
use uncertainty parameters of an occupancy type: structure value, FFE, CSVR or content value, OSVR or other value

**Comment by rtle76** [comment]
> if we sample a normal distribution using a random number between 0 and 1 as an input to inverse CDF, do we get the same result with (1) multiplying the mean (100%) and standard deviation (CV) by the structure value and then calling the inverse CDF and (2) using the mean 100% and standard deviation (CV) then multiplying the result by the structure value

Can you give me some context on this? I'm not sure what you're asking

**Comment by HenryGeorgist** [comment]
You need a structure value as a parameter.
A coefficent of variation, which describes the uncertainty in the value. 

Then you need to constuct a normal distribution with the structure value as the mean and compute a standard deviation with the value and the cv.

run an alternative formulation with a mean of 1 or 100 and the cv as the standard deviation. Take the sampled value and multipy it by the structure value.  

The results should bethe same. The benefit is where we store and how we load data in the structure inventory. Id like to save the second formula in the occupancy type.

**Comment by rtle76** [comment]
Thanks Will. That's clearer. I'll take a crack at it tomorrow and let you know if I have any other questions

**Comment by rtle76** [comment]
[Math.xlsx](https://github.com/HydrologicEngineeringCenter/HEC-FDA/files/8000126/Math.xlsx)
If I understand correctly, I think the attached proves what you're saying. Let me know if that's not what you're talking about

**Comment by HenryGeorgist** [comment]
yep thats it.

**Comment by rnugent3** [comment]
I concur.
