### ISSUE TITLE
Prompt user when closing with unsaved changes on editors.

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#272]
We tried this before using HasChanges in the baseviewmodel that gets triggered by notify property changed. One problem was that it seemed to always be changed when loading the editor. We might just have to clear it after all the loading by doing HasChanges = false;

**Comment by rnugent3** [comment]
I think this issue is worth prioritizing

**Comment by codymccoy** [comment]
[Prompting the user when closing with unsaved changes.docx](https://github.com/HydrologicEngineeringCenter/HEC-FDA/files/8800796/Prompting.the.user.when.closing.with.unsaved.changes.docx)

**Comment by codymccoy** [comment]
Above I attached a document outlining the architecture i used to implement this. This could use some more testing, but it seems to be working pretty well right now.

**Comment by codymccoy** [comment]
Updated document:
[Prompting the user when closing with unsaved changes.docx](https://github.com/HydrologicEngineeringCenter/HEC-FDA/files/8815967/Prompting.the.user.when.closing.with.unsaved.changes.docx)

**Comment by codymccoy** [comment]
Updated document:
[Prompting the user when closing with unsaved changes.docx](https://github.com/HydrologicEngineeringCenter/HEC-FDA/files/8835681/Prompting.the.user.when.closing.with.unsaved.changes.docx)

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/171952478-ac7fdff1-463e-4ca0-b7b1-cd64cb156568.png)

I believe this is complete.

**Comment by codymccoy** [comment]
Updated document:
[Prompting the user when closing with unsaved changes.docx](https://github.com/HydrologicEngineeringCenter/HEC-FDA/files/8865279/Prompting.the.user.when.closing.with.unsaved.changes.docx)
