### ISSUE TITLE
Class titled Mock Up

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/HEC-FDA#284]
https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/0c0e82868f7b7f9aa0a6e7aeb857b48f4f6dcad0/View/AggregatedStageDamage/DepthGridsMockUp.xaml#L1

Suspected unused class, or improperly named. I'm thinking this is either a temporary mock up that accidently got committed, or a mock up that got incorporated as more than a mockup and needs renamed to be less ambiguious.

**Comment by codymccoy** [comment]
I deleted it.
