### ISSUE TITLE
Unused User Control 

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/HEC-FDA#286]
https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/0c0e82868f7b7f9aa0a6e7aeb857b48f4f6dcad0/View/AggregatedStageDamage/UserControl1.xaml#L1

Unused Class. Talked with @codymccoy about it, and it was just an abandoned mock up that got accidently commited. Just need to delete.

**Comment by codymccoy** [comment]
Deleted
