### ISSUE TITLE
Empty Regions

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/HEC-FDA#287]
https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/3ff04fd7f509d3507ab115c8a809631003587347/ViewModel/WaterSurfaceElevation/PathAndProbability.cs#L10

This isn't a big deal, and I'd reconsider if you felt strongly the other direction, but I always find myself opening up every empty region while I'm reviewing code, and being frustrated there's nothing there.  

I also find it frustrating when someone enforces a strict file structure on their computer, but then has a bunch of empty directories because the didn't apply to that project. 

I'm not gung ho about going in and doing a sweep of these, but if you have no objections, lets not create regions unless we have something to put in them. That's not part of our contributing guide, and I don't really think it ought to be.

**Comment by codymccoy** [comment]
RMA totally agrees with you. I have not been creating regions in new classes unless i thought they would be helpful. Ryan usually calls them out when doing code review if he sees a region with nothing in it. I have been trying to remove them when i see them.

**Comment by Brennan1994** [comment]
sweet. resolved
