### ISSUE TITLE
Possible Unnecessary Object

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/HEC-FDA#288]
As far as I can tell, this object just stores a string and a related double value. Could we not just replace it entirely with a dictionary everywhere we use it? 

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/0c0e82868f7b7f9aa0a6e7aeb857b48f4f6dcad0/ViewModel/WaterSurfaceElevation/PathAndProbability.cs#L4

**Comment by codymccoy** [comment]
Probably. I like having the custom object. I think it makes it clearer what the thing is. It is a path and a probability. Dictionaries are can be a bit more confusing because you have to know the keys. I vote we leave this one alone.

**Comment by Brennan1994** [comment]
understood, I'll defer to your judgement on that.

**Comment by rnugent3** [comment]
Sounds like an opportunity to refactor the way we’re storing results from the compute. Duly noted.
