### ISSUE TITLE
Two LogPearsonIII classes - need to pick one

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/HEC-FDA#29]
https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/90a22d6a3a3bcb2fbf731b383dea8268e7b3fdf9/LogPearsonIII/LogPearsonIII.vb#L5

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/90a22d6a3a3bcb2fbf731b383dea8268e7b3fdf9/Statistics/Distributions/LogPearson3.cs#L12

**Comment by HenryGeorgist** [comment]
i think we can delete LogPearsonIII.vb, can we delete it and close out this issue now?

**Comment by rnugent3** [comment]
I think I deleted the whole project? 

Best,

R Nugent III

**Comment by HenryGeorgist** [comment]
it seems that there is a branch for that, the project still exists (and the class it seems) maybe you havent pushed latest on that branch. Either way, lets get it completed and remove that dependency!
