### ISSUE TITLE
Commented out code

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/HEC-FDA#290]
private strings _Name and _Description also appear unused, as well as _TableConstant

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/0c0e82868f7b7f9aa0a6e7aeb857b48f4f6dcad0/ViewModel/WaterSurfaceElevation/WaterSurfaceElevationElement.cs#L26

**Comment by codymccoy** [comment]
Good find, those are no longer needed after recent changes. I deleted them.
