### ISSUE TITLE
Commented out code in XAML

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/HEC-FDA#294]
https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/658407637c86cdde115530e88a5714ca0da03a85/View/Inventory/ImportFromNSI.xaml#L21

**Comment by codymccoy** [comment]
This class is not being used in FDA. Just an old relic of a bygone era.
I deleted:
![image](https://user-images.githubusercontent.com/47757848/155751717-0ea24693-2972-4603-8aa7-bc7fb1cc01a5.png)
