### ISSUE TITLE
Logic in Code behind ImportStructuresFromShapefile

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/HEC-FDA#295]
https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/658407637c86cdde115530e88a5714ca0da03a85/View/Inventory/ImportStructuresFromShapefile.xaml.cs#L12

Significant logic in code behind

**Comment by codymccoy** [comment]
Ideally some of this logic would get moved to the view model. I took a look and this is kind of a complicated editor. Most of the code behind methods are doing UI work as well as calling the view model. Things like changing the button name and changing visibility. It would be possible to do most of this through binding. If Richard wants that done I would say that should be task 14 work.

**Comment by rnugent3** [comment]
Sounds like something we should talk about. Let’s table this for our next biweekly. 

Best,

R Nugent III
