### ISSUE TITLE
Consequence_Assist dependency TextBoxWithDescription maintained locally

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/HEC-FDA#30]
https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/90a22d6a3a3bcb2fbf731b383dea8268e7b3fdf9/UserControls/TextBoxDescription.xaml.vb#L1

I found this code - this is textbox with description, it looks like the code was copied out of consequences_assist and stored in the code here. It is still in VB, but it doesn't seem to be referenced throughout the view. It might be pretty simple to just change our references to this project instead of consequences assist.

**Comment by codymccoy** [comment]
I found a few remaining editors that were using CA.textboxdescription, I switched those over to use the UserControls.textboxdescription.
