### ISSUE TITLE
LP3 Derived Parameters from DBF

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#306]
FDA 1.4.3 stores the derived parameters and @HenryGeorgist wrote some logic to get access to the parameters in the dbf. We need some logic in the view/view model to allow the users to get the parameters from the dbf and to construct an LP3 distribution 

_Originally posted by @rnugent3 in https://github.com/HydrologicEngineeringCenter/HEC-FDA/issues/250#issuecomment-1067305519_

**Comment by rnugent3** [comment]
There should be a menu item on frequency relationships "Import Synthetic Analytical Frequency Function from HEC-FDA Version 1.4.3 DBF." Access the LP3 parameters in the DBF to construct the analytical frequency function.

**Comment by rnugent3** [comment]
Obtain the .dbf example file here: https://drive.hecdev.net/share/8X0HuO8F

**Comment by rnugent3** [comment]
This is an image of the data you're looking for. See row 2. The requisite fields are REC_LENGTH, LOG_MEAN, STD_DEV, SKEW
![image](https://user-images.githubusercontent.com/25163165/179101190-04ba82f4-2812-4688-a532-f240bdc33581.png)
I am not sure what is the best way to identify whether a curve is synthetic. Probably by looking at any of the Q fields (e.g. Q_01) if the field has -901.00 then the row represents an analytical frequency function by parameters. If there is a positive value, then that is a synthetic analytical frequency function.

**Comment by rnugent3** [comment]
@HenryGeorgist wrote a test demonstrating how to do this: https://github.com/HydrologicEngineeringCenter/fda-model/blob/main/fda-model-test/integrationtests/dbftests.cs

**Comment by codymccoy** [comment]
This is completed and is ready for test:
![image](https://user-images.githubusercontent.com/47757848/181333471-f8f43dbc-01ca-4bcd-b28f-9bfd22f7fee1.png)

**Comment by rnugent3** [comment]
Looks good.
