### ISSUE TITLE
Table with plot exclamation point hangs around

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#315]
If you put a row in an error state and then get rid of the error, the red exclamation point still hangs around.
![image](https://user-images.githubusercontent.com/47757848/161863099-f0ca9db2-2e6f-4b3a-8b68-3e2a4502d381.png)

**Comment by HenryGeorgist** [comment]
there should be a property to remove the exclamation point all together from the error handling of the datagrid in the xaml. not sure what the property is, but that will fix it. the exclamation point is not necessary at all, the red cells do the work we want.

**Comment by HenryGeorgist** [comment]
<DataGrid.RowValidationErrorTemplate><ControlTemplate/></DataGrid.RowValidationErrorTemplate>

https://stackoverflow.com/questions/8394829/hide-wpf-datagrid-row-error
