### ISSUE TITLE
Table with plot normal distribution error message

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#316]
I commonly get the following error message:
![image](https://user-images.githubusercontent.com/47757848/161864353-e35cf27c-f843-4314-8fd9-3d5e287d81d6.png)
None of my values are ".01". I am not sure what it is trying to tell me. Can we make the message more descriptive?

**Comment by HenryGeorgist** [comment]
"The lower confidence limit of .01 yeilded a non monotonic extreme for the uncertainty in this relationship."
