### ISSUE TITLE
Table with plot: pasting values has issues

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#317]
We ran into several issues pasting into the table. In deterministic, pasting into the x column would put the values in the y column and vice versa. 

In FdaDataGrid.PasteClipboard() I added the following logic. This seemed to help, but doesn't solve all our problems.
![image](https://user-images.githubusercontent.com/47757848/161864919-7f78c205-a279-4ac0-9906-a4c51ad63fa4.png)
I added an abstract method to sequential row called "UpdateRow()". Each row can update its values. The issue that i was seeing was that "PropertyInfo y ..." line was not getting the correct property. 

There are two main paths in the PasteClipboard() method. The first is if the selected cell count is one. I think this is now working. The other branch is if there are multiple cells selected. I tried to make a similar change to that logic, but not sure how well it is working. I often get the following message when trying to paste into a group of selected cells:
![image](https://user-images.githubusercontent.com/47757848/161865316-d63efaf5-a08d-48b9-908b-17b68aafa152.png)

**Comment by HenryGeorgist** [comment]
copy and paste datagrid should not be tightly bound to the type of sequential row. This creates a dependency we do not want. Some other solution needs to be identified, and the true issue needs to be uncovered.

**Comment by dezidizon** [comment]
Attached a video exhibiting the issue with pasting a table from a spreadsheet into the FDA's table. The data is pasted in the column to the right of the expected column.

https://user-images.githubusercontent.com/47678178/161868859-46865478-3c9f-4a49-b90c-eec8470f54bf.mp4
