### ISSUE TITLE
Update column label for TableWithPlots

### ISSUE THREAD

**Issue by RyanM-RMA** [HydrologicEngineeringCenter/HEC-FDA#328]
Cody found that the labels for certain fields are fixed as X Value and Y Value.

After investigating the issue, I believe that the DisplayAsColumn and DisplayAsLine Attributes can be updated to use a key instead of a display name (just a variable rename).  The key would be used to query the DataContext of the view to get the appropriate label.

The query in IDataProvider would be:  string GetColumnLabel(string key); and string GetLineLabel(string key);

In the FdaDataGrid at line 450 in the column auto generation code, we can use the attribute's key and query the DataContext, which is an IDataProvider, for its column label given the key.

In TableWithPlotVM at line 175 and 176, we can use the attribute's key and query _computeComponentVM.SelectedItem, which is an IDataProvider, for its line label given the key.

Since the implementations of the IDataProvider know about the specific row implementations it uses, and already contain the labels, we should be able to do this fairly easily be storing the constant keys in the row implementation, and the labels in the IDataProvider.

This is my opinion on how we can resolve this, please let me know if there are any concerns or questions.

**Comment by RyanM-RMA** [comment]
The labels are currently associated with the ComputeComponentVM, and they would need to be pushed into the IDataProvider, probably during construction around line 136 of ComputeComponentVM

**Comment by HenryGeorgist** [comment]
what about making an attribute specific to that like a IHaveALabelKey

**Comment by RyanM-RMA** [comment]
both attributes have label names, and they're both used to create the label, so I think that would only add complexity.  Are you thinking use the original attribute labels as a default label, then IHaveALabelKey as an override?

**Comment by RyanM-RMA** [comment]
I could see that being a viable use case for things like Min/Max.

**Comment by HenryGeorgist** [comment]
im just worried about making something have dual purposes under different conditions

**Comment by RyanM-RMA** [comment]
Can you elaborate some more on that?

**Comment by HenryGeorgist** [comment]
if we plan to use it sometimes as a key lookup and sometimes as the literal value, that would be dual purpose.

If we plan to always use it one way (always as a key) i guess that would also work.

**Comment by RyanM-RMA** [comment]
Ah, ok.  I think that's where documentation, naming, and context comes into play.  We'd want to make it clear it's used as one thing or another, and not both.

**Comment by HenryGeorgist** [comment]
in general im open to the idea - if we can make it work that sounds like a reasonable approach. At the time of the reflection on the attributes we should have access to the resource dictionary that you are identifying.

**Comment by rnugent3** [comment]
HI @RyanM-RMA @HenryGeorgist following up on this issue - do we think we can make this work within a reasonable level of effort?

**Comment by RyanM-RMA** [comment]
After talking with Dez, and Cody about it, we think in total it's about 6-8 hours broken down like this:
* 3-4 hours dev time
* 1-2 hours review back and forth
* 2 hours QA
