### ISSUE TITLE
Structure Inventory table seems to be displaying the wrong value for the occupancy type and the group name

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#33]
The Occupancy_Type column seems to be displaying the occtype description and not the name. The OccTypeGroupName is all "Undefined". My guess is that I changed the table and didn't update the column numbers or something like that.

**Comment by rnugent3** [comment]
cody will test

**Comment by codymccoy** [comment]
Fixed. The saving of occtypes got refactored a while ago. There is a table that saves the occtype groups:
![image](https://user-images.githubusercontent.com/47757848/173629549-4848d9a4-1f18-4ae4-8b4a-0f1c45b06b85.png)

There is a table that saves all the occtypes and links the occtype to the group id:
![image](https://user-images.githubusercontent.com/47757848/173629641-9277d1f0-b623-4a48-8ddd-1dcd0633c195.png)
