### ISSUE TITLE
Base Validation Issues

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#330]
In the branch Tab_Control.

Our BaseViewModel class now extends ValidatingBaseViewModel. I have seen several issues after making that change. 

There have been several UI issues with components having red boxes around them that shouldn't. There are also some potention logic issues.

UI issues:
![image](https://user-images.githubusercontent.com/47757848/165346114-2182bd65-e138-4495-adf4-b320c773414e.png)

![image](https://user-images.githubusercontent.com/47757848/165346144-ad2bb7d1-a3bb-48b2-aabc-5b29a44c9963.png)
![image](https://user-images.githubusercontent.com/47757848/165346185-54adf438-ca5b-49bb-969e-3464af1a901f.png)

Potential Logic Issues:
* When i first open the editors, it doesn't validate my "Name" rules. (name cannot be blank).
* Not updating when going from one error to another. The validate doesn't update the error message if it is already in a "severe" state. Example. If i delete the name characters then tab off of the name field, we get a name cannot be blank error. Then if i type the name of a sibling element it should violate the sibling rule and show that error message tooltip on the save button.
* The list of string errors wasn't getting returned correctly. I think i fixed this, but i don't think i have submitted that code yet.

**Comment by rnugent3** [comment]
I think we backed out of using MVVM base validation, no? Is this issue still relevant?
