### ISSUE TITLE
combine stage-damage types

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#338]
We will want to think about allowing the user to combine stage-damage types into a stage-damage set - so internally calculated and manually entered

**Comment by rnugent3** [comment]
if we make the computed stage-damage functions editable, then this problem is fixed.

**Comment by codymccoy** [comment]
Completed. Computed stage damage functions are editable and I track the status of the curves. A label appears in the ui if the user modifies the computed curve.

**Comment by rnugent3** [comment]
Not able to verify at this time due to #473

**Comment by rnugent3** [comment]
I am not able to edit computed stage damage functions. I wonder if I have to have saved first? I cannot save at this time, see #616
