### ISSUE TITLE
Stage-damage is a function of frequency functions and stage-discharge

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#339]
We need combo boxes in the UI to select a frequency function, and if flow, a stage-discharge, too. The range of stages from the .001 quantile of the lowest coordinate to the .999 quantile of the highest coordinate defines the range of stages of the stage-damage function

**Comment by rnugent3** [comment]
actually this will either just be a stage-discharge or a stage-frequency. a discharge frequency would not be needed.

**Comment by rnugent3** [comment]
also an analysis year

**Comment by codymccoy** [comment]
I did the stage damage work that was defined in this document:
https://www.hec.usace.army.mil/confluence/display/FDA/2022-07-11+Maintenance+Tasks+Discussion
Does that satisfy this issue?

**Comment by rnugent3** [comment]
I am not able to back check this at this time due to #473

**Comment by rnugent3** [comment]
this work is done
