### ISSUE TITLE
Null Reference Exception when saving a condition

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#34]
Original author: Cody McCody

The conditions editor keeps crashing when i try to save a condition. Has something to do with the messages reloading.

![13318_image-2021-06-07-15-29-04-130](https://user-images.githubusercontent.com/25163165/130250437-ec5dabd8-ef97-4e52-9c2d-a827a76b231b.png)
![13319_image-2021-06-07-15-28-38-389](https://user-images.githubusercontent.com/25163165/130250441-4e911296-e43c-4458-ae6b-43ed0058c842.png)

I added a null check in the ReloadMessages() method so this will no longer be thrown, but I should investigate why the current element is null in this case.

**Comment by rnugent3** [comment]
@codymccoy I believe this issue has been resolved. Please confirm.

**Comment by codymccoy** [comment]
@rnugent3 Resolved. Those messaging classes don't even exist anymore.
