### ISSUE TITLE
Junk in the View.csproj

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/HEC-FDA#342]
There's a bunch of Compile Removes and Page Removes etc. In the .csproj file. I think these get added by visual studio sometimes when you remove things from your project through the GUI. It doesn't automatically delete them from the folder, so VS just adds a tag to the proj file to keep them from getting used or showing in your solution tree. 

I think these just need to be reviewed and deleted. The files backing them no longer exist. 

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/b23441b56fe7b5da9950cfb467925fb176ebf06f/View/View.csproj#L36

**Comment by codymccoy** [comment]
Deleted the whole section from the csproj and deleted any files that were excluded and not fully deleted.
