### ISSUE TITLE
Junk in the View Model cs.proj

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/HEC-FDA#343]
Bunch of compile removes, and page removes in the view model proj. Need to be removed and deleted just to clean things up. If the backing files are already gone from the directory, it should just be a matter of deleting the lines from the proj file. 

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/b23441b56fe7b5da9950cfb467925fb176ebf06f/ViewModel/HEC.FDA.ViewModel.csproj#L24

**Comment by codymccoy** [comment]
I removed that whole section from the csproj. A lot of them were files that i had excluded from project but had not deleted. I deleted those files.
