### ISSUE TITLE
Study Importer Name doesn't fit pattern

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/HEC-FDA#344]
Looks like the established naming scheme is "ImportXFromFDA1VM". I'd have expected this to be ImportStudyFromFDA1VM based on that pattern. 

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/b23441b56fe7b5da9950cfb467925fb176ebf06f/ViewModel/Study/ImportFromOldFdaVM.cs#L18

**Comment by codymccoy** [comment]
I agree. I changed the name of the VM and the view to be ImportStudyFromFDA1
