### ISSUE TITLE
Is this appropriate when Terrains are sometimes multiple tifs?

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/HEC-FDA#346]
If we're using a RAS terrain, I'll need to get that .hdf file. If it's not a RAS terrain, but still a multi-piece terrain, I'll typically want to get at the .vrt. 

I can do a more detailed writeup of how terrain files are structured if need be. 

From the RASDocs: "Once the GeoTIFF files are created, RAS Mapper also creates a *.hdf file and a *.vrt file.  The *.hdf (Hierarchical Data Format) file contains information on how the multiple GeoTIFF files are stitched together.  The *.vrt (Virtual Raster Translator) file is an XML file that contains information about all of the raster files (*.tif).  The user can drag and drop the *.vrt file onto an ArcGIS project and ArcGIS will know about all of the raster files that make up the terrain layer. "

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/b23441b56fe7b5da9950cfb467925fb176ebf06f/ViewModel/Watershed/TerrainElement.cs#L67

**Comment by codymccoy** [comment]
That method had zero references. I just deleted it. I agree, there shouldn't be a hard coded ".tif" without at least checking that it is a tif.
