### ISSUE TITLE
Unhandled exceptions in new_model_integration branch

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#356]
I've built HEC-FDA from the new_model_integration branch and am unable to create a new study, blank or imported from 1.4.3. I run into the exceptions in the images below. 

In this image, it seems like an object of type object is being cast to type object[]. Is there something going on in attempting to cast a type object to an array of type object? 
![image](https://user-images.githubusercontent.com/25163165/169704822-ed7c3d80-f6eb-4738-9202-1afb0a729664.png)

I am not sure I understand where the below exception comes from. 
![image](https://user-images.githubusercontent.com/25163165/169704895-5e3cbfdd-60e9-4949-bd44-410a6d513131.png)

**Comment by rnugent3** [comment]
I've confirmed that the problem stems from something in the new_model_branch, and not something happening locally. I can create a new study using the main branch.

**Comment by HenryGeorgist** [comment]
it might be better to include permilinks for those locations in the code so someone can figure out why the FDA.View.ViewWindow is being passed into execute and so on.

It is generally risky buisness to have an argument on a function to be object - it seems like these both expect pretty specalized inputs, and should be done with some sort of safer cast than direct casts.

**Comment by rnugent3** [comment]
when creating a new study, an exception occurs here: https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/d592cd070797f810fc84012ff6daa56d5062cf0f/View/Commands/OkCommand.cs#L21

**Comment by rnugent3** [comment]
I was just able to create a new study using import study from 1.4.3. so an intermittent issue? oh no!

**Comment by rnugent3** [comment]
In an attempt to import impact areas so I can import stage-damage functions and then create a Scenario, I ran into the same exception in OkCommand.

**Comment by HenryGeorgist** [comment]
you need to find the call stack and the calling function. it seems the wrong argument is being passed to the ok command.  This is why i use named actions - it allows me to ensure i have an object that I can interrogate rather than simply cast and hope for the best.
