### ISSUE TITLE
Validation logic on table with plot needs to be changed to be less strict

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/HEC-FDA#360]
Distributions can be weakly monotonically increasing, not necessary strictly, except for the frequency functions, meaning they can either increase, or stay the same.

**Comment by codymccoy** [comment]
I think this is already the case. 
![image](https://user-images.githubusercontent.com/47757848/170287369-3dabe3b8-a6c2-4e8c-a88c-2dd8c15041b3.png)
Weak monotonic means that you can have the same value twice right?

**Comment by rnugent3** [comment]
Yes, that is what weak monotonic means. In sequence, a value must be greater than _or equal to_ the prior value. I saw in some controls this was not the case. Let me double check where.

**Comment by rnugent3** [comment]
this must be on an active branch? the build using main still reflects validation for strict monotonicity. 
![image](https://user-images.githubusercontent.com/25163165/170294947-3bd22efc-0674-4b5d-916c-ceb1592c6216.png)

**Comment by rnugent3** [comment]
Let's put this issue on hold while we resolve the implications of different types of monotonicity

**Comment by codymccoy** [comment]
this is completed.
