### ISSUE TITLE
Triangular Distributions import incorrectly from FDA1.X

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/HEC-FDA#361]
Triangular distributions flip the Min and Most likely values in the table. Mins come in under most likely, and most likelys come in under min.

**Comment by rnugent3** [comment]
@codymccoy please prioritize this ASAP. This should be part of our Task 9 deliverable.

**Comment by codymccoy** [comment]
For rating curves:
![image](https://user-images.githubusercontent.com/47757848/170092832-dcd23c16-e62c-4a48-8587-405f47134b07.png)

for inflow outflow:
![image](https://user-images.githubusercontent.com/47757848/170106056-cf5eab2b-c826-4415-93de-9b1e0b336c95.png)

for occtype:
![image](https://user-images.githubusercontent.com/47757848/170106215-51c188fa-fe09-4a55-be7f-dce14d4868f1.png)

![image](https://user-images.githubusercontent.com/47757848/170106521-363c2adc-b490-407f-ada1-fadccc41b5f8.png)

**Comment by codymccoy** [comment]
There is different logic for different objects. Are we saying that all curve types have this problem? ie: rating, inflow-outflow, ext-int, occtypes, etc.

**Comment by rnugent3** [comment]
I will look.

**Comment by codymccoy** [comment]
looks like stage discharge has this problem:
![image](https://user-images.githubusercontent.com/47757848/170132066-904ea409-d7ad-478d-841d-72b94f8f26a3.png)

**Comment by rnugent3** [comment]
Right this is just stage discharge. 1.4.3 interpolates this uncertainty only. We need to think about whether to support this in 2.0.

**Comment by codymccoy** [comment]
I believe that this is the same issue as another "triangular" github issue. I believe this is resolved now. @rnugent3 Can you test this?

**Comment by rnugent3** [comment]
I will test. 

Best,

R Nugent III

**Comment by rnugent3** [comment]
I agree, this issue is a duplicate, and this issue has been resolved.
