### ISSUE TITLE
Direct dollar damage functions

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#363]
if "uses direct dollar == true" then we should ignore the function. import the occupancy type but let the damage function be all zeros.

**Comment by rnugent3** [comment]
[greenbrookOccTypes.txt](https://github.com/HydrologicEngineeringCenter/HEC-FDA/files/8772390/greenbrookOccTypes.txt)
please test using this data

**Comment by codymccoy** [comment]
@rnugent3 Can you verify that this is fixed? This logic has been merged into main.

**Comment by rnugent3** [comment]
I will test. 

Best,

R Nugent III

**Comment by rnugent3** [comment]
I attempted to import using the file I attached above. I had previously imported bear creek occ types. It looks like there are two occupancy types with the same name. I ran into an unhandled exception. 

![image](https://user-images.githubusercontent.com/25163165/173158302-84211961-69aa-417c-bc0a-9e323af952b6.png)

**Comment by rnugent3** [comment]
Importing occ types with direct damage functions appear to work as we discussed. We could close this issue now and open a new one to handle the above referenced unhandled exception or keep this issue open for the exception. up to you, @codymccoy

**Comment by codymccoy** [comment]
Lets just keep this one open

**Comment by rnugent3** [comment]
cool, thanks

**Comment by codymccoy** [comment]
@rnugent3 I just tried to reproduce this bug and could not. This is actually in Bob's code. It looks like he is using a dictionary with a key value pair. If you can reproduce this bug, hover over the occtype name and see what it is. It sounds like greenbrook must have two occtypes with the same name? How do you want this handled, just ignore any occtypes with a duplicate name? We write out a log when they import, so maybe we could write a message out to the log that the user is seeing.

**Comment by rnugent3** [comment]
The name is aOccType.Name = "PRB_SA1_SA2_SA3"

**Comment by rnugent3** [comment]
The bug mentioned above no longer occurs.
