### ISSUE TITLE
stage discharge triangular distribution bug

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#364]
a triangular distribution of stages for the stage-discharge is importing the distribution for one coordinate for all coordinates. I'd guess this is the result of the fix to the stage-discharge standard deviation import. 

@codymccoy please prioritize this, this is part of Task 9.

**Comment by rnugent3** [comment]
![image](https://user-images.githubusercontent.com/25163165/170134359-1010eaff-f430-4a54-8517-a13ce4f32b8e.png)

**Comment by rnugent3** [comment]
this is another situation where FDA is calculating the bounds

**Comment by rnugent3** [comment]
![image](https://user-images.githubusercontent.com/25163165/170134657-13e08dbe-09f1-4e2f-ae88-85d55936f29a.png)

**Comment by rnugent3** [comment]
the attached workbook replicates the results in the image above
[triangleDistReplication.xlsx](https://github.com/HydrologicEngineeringCenter/HEC-FDA/files/8772236/triangleDistReplication.xlsx)

**Comment by codymccoy** [comment]
This is now fixed. It would be good for someone to double check it. It will be merged into main in the next day or two.
![image](https://user-images.githubusercontent.com/47757848/170366347-459c3a06-50a2-49d4-b77b-00072a374fe4.png)

**Comment by codymccoy** [comment]
This should be in the main branch now. @rnugent3 do you mind verifying that this is working the way that is should?

**Comment by rnugent3** [comment]
This works the way that it should.

**Comment by rnugent3** [comment]
I will test. 

Best,

R Nugent III
