### ISSUE TITLE
move stage damage combo box in Scenario editor

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#367]
I think we should move the stage damage combo box up a level in the Scenario editor because we should choose only 1 set of stage damage functions for a given Scenario. Currently, you can select any set for a specific impact area scenario. We need to at least add validation that the user cannot select different sets of stage damage functions for a given Scenario

**Comment by codymccoy** [comment]
I think this is now completed. @Richard do you want to take a look and see if this behaves the way you want?
These changes are in Alternative_Compute_Results branch.

**Comment by rnugent3** [comment]
I will confirm in the next couple days. 

Best,

R Nugent III

**Comment by rnugent3** [comment]
This does behave the way I expected. Could we move the "Add Additional Thresholds" up to the second row?

**Comment by codymccoy** [comment]
It has now been moved up:
![image](https://user-images.githubusercontent.com/47757848/173257974-a948f5be-e180-48dc-bf71-b3d54dca2cb4.png)

**Comment by rnugent3** [comment]
Looks great! Thanks, @codymccoy

**Comment by rnugent3** [comment]
behaves as expected
