### ISSUE TITLE
Create New Index Points study tree command fails to open dialog (or tab).

### ISSUE THREAD

**Issue by jbslaughter** [HydrologicEngineeringCenter/HEC-FDA#369]
**Build:** CI-CD #41 (Merge pull request #354), dated 2022-05-20

From the Study Tree the command to create new index points fails to open a dialog (nothing happens).

![image](https://user-images.githubusercontent.com/89167848/170358171-00dbe9af-3284-4f30-9668-f40c0dbeddf7.png)

**Comment by rnugent3** [comment]
Good catch. This functionality does not yet exist. Nor will the hdf hydraulics imports, nor graphical frequency functions.

**Comment by Brennan1994** [comment]
This is no longer applicable.
