### ISSUE TITLE
Fit to flows table doesn't report errors when constructing LP3

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#377]
![image](https://user-images.githubusercontent.com/47757848/171747280-af9fd0cc-ea7a-4396-b4f0-a55fd4e7c7aa.png)

We don't want to throw up a message box every time the user enters a value that doesn't produce a valid curve. It might be nice if we could display the errors from the attempt at creating an LP3 to the user. Right now, the VM calls into the model to create an LP3 every time the user types in a new flow value. I am capturing those errors but doing nothing with them other than clearing out the Mean, St. Dev., and Skew and killing the curve in the plot.

![image](https://user-images.githubusercontent.com/47757848/171747537-2d783cbd-4910-46a5-8521-212149205da1.png)

**Comment by rnugent3** [comment]
What if there was a button “Fit” that took the user entered data, created the LP3, then displayed the moments, curve, and messages? 

I do not think this would replace “save” but the user would have to hit “Fit” to be able to save. 

We’d want to change “Fit to Parameters” to “Enter LP3 Parameters” and “Fit to Flows” to “Fit LP3 Parameters to Flows”

Thoughts? 

Best,

R Nugent III

**Comment by codymccoy** [comment]
This has been completed on the Alternative_Compute_Results branch.
![image](https://user-images.githubusercontent.com/47757848/173125079-e50684b5-99bf-4e57-8e25-390daaf02f11.png)

The UI tries to build the lp3 curve when you click the "Fit" button, when you click "Save" or when switching radio buttons. If it can't build the lp3 a popup message is displayed like the one in the image above.

@rnugent3 Can you test this when you get a chance.

**Comment by rnugent3** [comment]
I think this looks good. Is there any easy way to message the user if they edited the data, did not press fit, and attempted to save? In that case, if they did not press fit and they call on this frequency function, it seems like we could be using moments different from their intended moments.

**Comment by rnugent3** [comment]
also - I believe that we wanted to let the user save data despite the error state. I am not able to save when in an error state.

**Comment by codymccoy** [comment]
In the case of "fit to flows" i am saving the flow values and not the moments. So if the user didn't hit "Fit" i would just be saving the flow values that are in the table. The "Fit" button is really just to test if the curve can be created and to view it in the plot. LP3's are a little bit special. I will do a little testing to see what the implications of not having a valid one would be. Since i am just saving the flows there wouldn't be any issue in saving bad flows. I will look into this.

**Comment by rnugent3** [comment]
thank you

**Comment by codymccoy** [comment]
It seems like the implications for lp3 are the same for the other curves. The curve needs to be valid for the preview compute and the compute. UncertainPairedData has a validation method. Both the preview compute and the compute use a class i created called SimulationCreator. In this class I have a method called IsConfigurationValid(). This method should validate that everything is in a state that can run a compute. I had very little validation in this method. I think the path forward is to check that the uncertain paird data objects for each curve is valid. I think this will be pretty straight forward to code, but @rnugent3  let me know if this doesn't seem correct to you.

I am adding this line to my method:
![image](https://user-images.githubusercontent.com/47757848/173257543-0593e0bb-de1b-4367-bf3c-32cc9d372659.png)

I think if this validation fails, a popup gets displayed with the reason why the compute can't run. I will test to make sure.

**Comment by codymccoy** [comment]
To answer the original question, I do not need to validate that the moments create a valid lp3 when saving in the frequency editor.

**Comment by codymccoy** [comment]
We decided to let the compute message out to the UI about changing curves from non-monotonic to monotonic. I will not do any validation for monotonicity before running the compute.

@rnugent3 I think we can close this one, but maybe you want to test it first?

**Comment by rnugent3** [comment]
Just to make sure we're on the same page - you're not doing any validation for monotonicity of the curves after they have been selected for a specific IAS - but you are doing validation on those curves when they're specified through table with plot in their respective editors right?

**Comment by codymccoy** [comment]
That is correct.

**Comment by rnugent3** [comment]
Ok. I will test to double check and then close.

**Comment by rnugent3** [comment]
shall I test on main?

**Comment by rnugent3** [comment]
What happened to the equivalent record length to be entered with LP3 parameters?

**Comment by codymccoy** [comment]
@rnugent3 Could you describe your last comment more? I am not sure what ERL is.

**Comment by codymccoy** [comment]
This is fixed on the Github_Bug_Fixes branch.

**Comment by rnugent3** [comment]
Sounds good, thank you.

**Comment by codymccoy** [comment]
@rnugent3 Everything in here is in main. I think we can close this. Brennan's graphical stuff seems to be working. Do you want to test and close?

**Comment by rnugent3** [comment]
looks good!!!
