### ISSUE TITLE
Old projects were removed from solution but not repo

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/HEC-FDA#379]
Will pointed out to me the other day that all the old projects are still saved in our version control. For example, the functions and functions test project, the model project, etc. 

These were removed from the solution, so we don't see them in VS, but we still see them on GitHub. These should be deleted. To do this, you'll need checkout main, then delete those directories from file explorer. 

I suspect this was accidental, but if not, let me know what the plan is for these.

**Comment by codymccoy** [comment]
Done. Unused projects have been deleted and pushed into main.
