### ISSUE TITLE
New Tabs

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#38]
It would be great if new tabs just opened would be the first tab (top tab?) seen in the UI. This would probably prevent some user frustration and emails.

**Comment by rnugent3** [comment]
@codymccoy I think this is now the default behavior, please confirm.

**Comment by codymccoy** [comment]
@rnugent3 When you open a new tab it gets added to the right of the other tabs and is selected.
![image](https://user-images.githubusercontent.com/47757848/172906437-a14355ff-6547-4ed0-8d74-d9e56f78a1d1.png)


This is consistent with things like OneNote:
![image](https://user-images.githubusercontent.com/47757848/172906422-349ae5dc-fc76-43c3-b62e-9583f5f6d399.png)
