### ISSUE TITLE
Better Compute Messaging

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#388]
This is the new compute log:
![image](https://user-images.githubusercontent.com/47757848/173441583-a9ebf1cd-55a8-4315-a5d3-229db697772d.png)

Do we even want to have so  many EAD messages? 
Add "Compute Complete" to the end. 

Play around with this new Compute Log and see what features it has.

**Comment by rnugent3** [comment]
we need better messaging coming out of stage-damage, impact area scenario, alternative, and alternative comparison report

**Comment by rnugent3** [comment]
We also need to use information levels consistently so that we can optimize the information that we write to log.
