### ISSUE TITLE
Example where TextBoxDescription is utilized, needs to be migrated from consequences assist.

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/HEC-FDA#4]
https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/b82f0e519ec82075c3f22379df01eb96932cb54e/View/StageTransforms/ExteriorInteriorEditor.xaml#L40

**Comment by rnugent3** [comment]
I don't think these classes exist anymore. @codymccoy please confirm.

**Comment by rnugent3** [comment]
Also this seems related to #30

**Comment by codymccoy** [comment]
Completed.
