### ISSUE TITLE
mean EAD

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#409]
There is something funny going on with mean EAD for a reach that has a regulated-unregulated transform flow function.  In the two images below, you'll find the configuration of a scenario and the results of a scenario - both for the same reach and which use the default data. The mean of EAD is 125.77 for an impact area that has a regulated-unregulated flow transform function. The EAD that I expected - based on results both in 1.4.3 and fda-model - is about half of the mean shown. The particularly curious thing is that damage is higher for the reach with a regulated-unregulated transform function as compared to the reach without the transform function. The transform function reduces peak flows for a range of frequencies so damage should be lower - and this is what I find in testing in fda-model-test. I am finding that the EAD for the reach without the transform function matches what I expect - about 120. The only thing different between the two is the transform function so it seems that is related to 

I thought that regulated and unregulated could be swapped, but I don't think that is the case. The labels are swapped - should be (Unregulated, Regulated) - sorry if I missed that or wrote down the wrong thing. Anyway, I purposefully swapped the data and EAD increased as would be expected if the columns are not swapped so the data seems to be passed in correctly.

**Comment by rnugent3** [comment]
![image](https://user-images.githubusercontent.com/25163165/175793118-7875f7f4-db8a-4fdd-8341-df403f6a36b5.png)
![image](https://user-images.githubusercontent.com/25163165/175793127-12291aff-e346-4927-bd8b-ebd2c45152e9.png)

**Comment by codymccoy** [comment]
@rnugent3 Am I being asked to change the labels around? Everywhere that says "Regulated-Unregulated" should be "Unregulated-Regulated", or do we just want to flip the x and y values when running the compute?
