### ISSUE TITLE
All zeroes in results

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#421]
Scenario/Performance/Assurance of Threshold has all zeroes:
![image](https://user-images.githubusercontent.com/47757848/176459313-d5aa5756-9f5a-4456-9b01-740546c70ef9.png)

Scenario/Performance/AEP has all zeroes:
![image](https://user-images.githubusercontent.com/47757848/176459518-32abedf2-f687-4b7d-9dcb-4c335498170e.png)

**Comment by rnugent3** [comment]
What is the configuration of the scenario?

Judging roughly by the AEP histogram, the assurance of AEP looks plausible. Assurance of AEP reflects the fraction of AEPs that are less than the AEP of interest. It looks like approximately 100% of the AEPs are greater than the largest AEP of interest, 0.1.

**Comment by codymccoy** [comment]
I just sent you my lower cache creek study. The pics above are from the "Multiple Thresholds" scenario. Not sure, but i think i always have all zeros. Maybe check the other scenarios also.

**Comment by rnugent3** [comment]
this no longer happens
