### ISSUE TITLE
Odd histogram when using multiple exterior stage thresholds

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#422]
All of the exterior stages except the default (470.63) show a giant blue square for the histogram.
![image](https://user-images.githubusercontent.com/47757848/176460316-bb32f5ac-74b3-483e-b98d-522dbaaf0428.png)

The default shows a nice histogram:
![image](https://user-images.githubusercontent.com/47757848/176460416-1ac4347d-e70d-4c1d-a5dc-e2cdb314af5d.png)

**Comment by codymccoy** [comment]
@rnugent3  I think this is a bug in my code. Removing you from this issue for now.

**Comment by codymccoy** [comment]
@rnugent3 I see that you commented that you were assigning this issue to yourself but it is still assigned to me. Is there any action that you would like me to take on this issue?

**Comment by rnugent3** [comment]
Let's close this issue. I am confident that the blue square problem has been fixed. With the thresholds of 0 and 999, you were getting back single-valued histograms. All 1s and all 0s. The interior threshold type has not yet been handled, which is why you get back bad results for that threshold.
