### ISSUE TITLE
Can't Copy the last column of the summary tables

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#435]
![image](https://user-images.githubusercontent.com/47757848/178028048-36865b0f-35ad-48fe-a942-23f1ba3995a7.png)

The last column is a bit weird because of the three values. You can copy all the cells except this last column.

**Comment by rnugent3** [comment]
what's the dependency for this table?

**Comment by Brennan1994** [comment]
@rnugent3 Richard to test by pasting into notepad

**Comment by Brennan1994** [comment]
@codymccoy confirm this issue persist using FdaDataGrid rather than CopyPasteDataGrid

**Comment by rnugent3** [comment]
somebody might have already tested this but documenting here: we do not copy anything from the last column of the table

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/179574272-bd73c7c6-3de1-4901-a601-c97676402362.png)

Issue still exists in FdaDataGrid. I tested pasting the values into notepad and the final column still doesn't show up. This means that the issue is not with pasting into excel.

I modified the last column to bind to a string instead of three different doubles. The copy now picks up the last column. When i paste into notepad you can see the three values. Pasting into excel doesn't work well because it seems to automatically add the three values together!

![image](https://user-images.githubusercontent.com/47757848/179578530-9fc2e403-c8f6-4c80-a400-46853322f5ab.png)

![image](https://user-images.githubusercontent.com/47757848/179578583-811dae84-b5bf-4e1f-89a2-18204ddde8fc.png)

I think the easiest solution is to make the last column 3 columns. @rnugent3 can you come up with three column titles that would be acceptable? "EAD Reduced Exceeds 0.75", "EAD Reduced Exceeds 0.5", etc

**Comment by codymccoy** [comment]
@rnugent3  is Q1 the .75 value or the .25 value?

**Comment by rnugent3** [comment]
Q1 is the .75 value 

Confusing, I know

**Comment by codymccoy** [comment]
Updated ead summary table:
![image](https://user-images.githubusercontent.com/47757848/179783302-d253885e-3e9f-4ade-a8a9-e1114c415455.png)

Updated the AAEQ summary table. I added "Mean" to the AAEQ damage reduced column. Is that correct?
![image](https://user-images.githubusercontent.com/47757848/179783841-7a486ff9-6059-401d-a86e-3a23ec958d35.png)

**Comment by codymccoy** [comment]
@rnugent3  You mentioned changing every table with "indicated value". Change them to what?
![image](https://user-images.githubusercontent.com/47757848/179784686-4c74e242-9add-4127-b893-ae494088b9d8.png)

**Comment by codymccoy** [comment]
I confirmed that the summary table now copies correctly. The values can be pasted into Excel.

**Comment by rnugent3** [comment]
> Updated ead summary table: ![image](https://user-images.githubusercontent.com/47757848/179783302-d253885e-3e9f-4ade-a8a9-e1114c415455.png)
> 
> Updated the AAEQ summary table. I added "Mean" to the AAEQ damage reduced column. Is that correct? ![image](https://user-images.githubusercontent.com/47757848/179783841-7a486ff9-6059-401d-a86e-3a23ec958d35.png)

For the AAEQ table. Let's do "Mean AAEQ Damage Reduced" and then "Qx AAEQ Damage Reduced" for the following three

**Comment by rnugent3** [comment]
> @rnugent3 You mentioned changing every table with "indicated value". Change them to what? ![image](https://user-images.githubusercontent.com/47757848/179784686-4c74e242-9add-4127-b893-ae494088b9d8.png)

Let's label Column 1 "Quartile" and populate each row with Qx where x = {1, 2, 3} and label Column 2 "Quartile Value"

**Comment by codymccoy** [comment]
@rnugent3 For the table, you want "Quartile" for the first column. For the alternatives we were using a different label for aaeq which had the word "reduced" added. To I need to do something similar or is "Quartile" ok for both ead and aaeq?
![image](https://user-images.githubusercontent.com/47757848/179793297-204dbbb7-40a4-4786-ad9c-ee375f60c960.png)

**Comment by rnugent3** [comment]
> @rnugent3 Is a subscript important to you. There is a way to do it. It is a little complicated and seems very small. Kind of hard to see it. ![image](https://user-images.githubusercontent.com/47757848/179792252-702b25ac-afe0-4b40-81a7-0d7d0aa6a5f8.png)

My concern with not using the subscript is that Q1 looks like "First Quarter" e.g. of the fiscal year. I'd rather have "First Quartile" written out if the subscript is tricky/messy

**Comment by rnugent3** [comment]
> @rnugent3 For the table, you want "Quartile" for the first column. For the alternatives we were using a different label for aaeq which had the word "reduced" added. To I need to do something similar or is "Quartile" ok for both ead and aaeq? ![image](https://user-images.githubusercontent.com/47757848/179793297-204dbbb7-40a4-4786-ad9c-ee375f60c960.png)

Good point. We want helpful labels. So lets use "Quartile of EAD (Reduced) Distribution" "Quartile of AAEQ Damage (Reduced) Distribution" then in the rows you can just write First, Second, Third. Does that make sense?

**Comment by codymccoy** [comment]
Subscripts:
![image](https://user-images.githubusercontent.com/47757848/179819154-7815b518-7c00-419b-bf61-34fc4f7af347.png)

**Comment by rnugent3** [comment]
Looks great!

**Comment by codymccoy** [comment]
Alt comp report, damage with uncertainty, ead
![image](https://user-images.githubusercontent.com/47757848/179845671-0d98e417-f524-45b2-87c6-f6c77e6f45bd.png)

**Comment by codymccoy** [comment]
alt comp report, aaeq
![image](https://user-images.githubusercontent.com/47757848/179845807-80159d53-29e5-444d-854b-071b059fb1ce.png)

**Comment by codymccoy** [comment]
Yes

**Comment by codymccoy** [comment]
alt comp report aaeq:
![image](https://user-images.githubusercontent.com/47757848/179846859-cfa5934f-9039-4242-8658-d0745492735e.png)

alt comp report ead:
![image](https://user-images.githubusercontent.com/47757848/179846921-02ac38a7-600b-4dab-b6b8-909e4750020b.png)

Alternative ead:
![image](https://user-images.githubusercontent.com/47757848/179846978-5c5a65bb-958e-4aea-b33f-452821a314de.png)

Alternative aaeq:
![image](https://user-images.githubusercontent.com/47757848/179847061-866aec81-8910-42d3-bab7-f4ecebab1b61.png)

scenarios:
![image](https://user-images.githubusercontent.com/47757848/179847461-e6919423-48e8-4468-8747-dd524dd2f0ae.png)

**Comment by rnugent3** [comment]
we're almost there. Alternative AAEQ should not have the word "Reduced"

**Comment by rnugent3** [comment]
I am happy we ended up with this language. Much cleaner.

**Comment by codymccoy** [comment]
I removed the word reduced from the aaeq alternative.

**Comment by codymccoy** [comment]
I think this is all completed and can be closed.

**Comment by rnugent3** [comment]
Unable to confirm at this time due to #470 and #471.

**Comment by Brennan1994** [comment]
Would like confirmation on this before closing. Seems like it's complete though.

**Comment by rnugent3** [comment]
Ok. I'll test when we have the user controls stuff fixed.

**Comment by rnugent3** [comment]
behaves as expected.
