### ISSUE TITLE
Stage Damage: Compute button needs to actually compute the stage damages

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#44]
This involves work on the view, view model, and model side.

**Comment by codymccoy** [comment]
As per our meeting yesterday, I have created a "configuration" object that should have all the data that you need to compute the stage damage curves. The object is called StageDamageConfiguration. 
![image](https://user-images.githubusercontent.com/47757848/183099325-d5d4e114-6ff0-452b-aa54-530453667a67.png)
As you can see in the image above, the config is created, then we call validate on it. If it is valid, then we should pass it into the compute method that has yet to be written.

**Comment by rnugent3** [comment]
this work is done! stage-damage functions are being computed (although are being returned funky - there is a separate issue up for that)
