### ISSUE TITLE
Convergence criteria control

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#441]
We need the convergence criteria control that @Brennan1994 developed plugged into the HEC-FDA repository. Convergence criteria is a menu item among the study properties. 

@codymccoy please chat with @Brennan1994 about his control.

**Comment by Brennan1994** [comment]
[ConvergenceCriteriaControl.zip](https://github.com/HydrologicEngineeringCenter/HEC-FDA/files/9122671/ConvergenceCriteriaControl.zip)

Control and VM here

**Comment by codymccoy** [comment]
This work is completed. The properties UI has been updated and all places that use convergence criteria pulls the values from the properties element. Default values are in the default curve data class.

**Comment by rnugent3** [comment]
This appears to work as expected.
