### ISSUE TITLE
alt comparison report header

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#443]
Please remove the word "Damage" from the header of the summary table 

![image](https://user-images.githubusercontent.com/25163165/179423598-539235af-0599-425a-bb57-d88311c4473e.png)

**Comment by codymccoy** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/47757848/179557269-59f33494-18d7-4976-b7cf-a70b709f5905.png)
