### ISSUE TITLE
multiple year attributes 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#446]
There are two "year" attributes among structure attributes. Let's drop "Year"

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/179580655-0885ab0c-f753-421c-a839-b6fa9600ceee.png)

I removed the "Year" row.

![image](https://user-images.githubusercontent.com/47757848/179580628-4279ccd1-f24a-4157-bf4f-e89559fe0547.png)


This will be pushed to Task_Review_Fixes by the end of the day.

**Comment by rnugent3** [comment]
Looks great. Thank you.
