### ISSUE TITLE
statistics don't match 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#448]
the means indicated in the attached photos should match. the quartiles match. 

![image](https://user-images.githubusercontent.com/25163165/179425537-4e9c9d07-e62c-42d4-b8c6-0f89ac4d3086.png)
![image](https://user-images.githubusercontent.com/25163165/179425541-15208419-d0b8-47e5-a4d4-9fa175a0437d.png)

**Comment by codymccoy** [comment]
This is the call i am making to get the aaeq summary table damage reduced:
![image](https://user-images.githubusercontent.com/47757848/179599926-98ac9f2a-5a2e-47f4-8435-a903398a4388.png)

This is the call to get the AAEQ damage with uncertainty value. I was doing the top line, but i see that there is a damage reduced call (the bottom red arrow). @rnugent3  Should I be using the damage reduced call here?
![image](https://user-images.githubusercontent.com/47757848/179600492-01739f24-a959-4712-ae5c-fc106f578108.png)

**Comment by codymccoy** [comment]
Looks like this is the same issue as #449

**Comment by codymccoy** [comment]
This "Mean" value should be the damage reduced call.

**Comment by rnugent3** [comment]
correct

**Comment by rnugent3** [comment]
> Looks like this is the same issue as #449

I think that is right.
