### ISSUE TITLE
statistics match but shouldn't 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#449]
the alternative comparison report mean incorrectly displays alternative results mean. the alternative comparison report should display damage reduced. it is curious that the mean is the same but the quartiles are not. 

![image](https://user-images.githubusercontent.com/25163165/179425655-df3297b4-2d56-41c3-af61-717771749853.png)

**Comment by rnugent3** [comment]
this is the case for both EAD and AAEQ 

![image](https://user-images.githubusercontent.com/25163165/179425712-141b18a6-e24d-4db2-a58e-a53bc7a49df5.png)

**Comment by rnugent3** [comment]
![image](https://user-images.githubusercontent.com/25163165/179425864-c735eb91-5014-46dc-a660-c39449aa219a.png)
match but shouldn't

**Comment by rnugent3** [comment]
![image](https://user-images.githubusercontent.com/25163165/180091445-bcdbd50b-c847-4faf-a30d-ce49d7809c54.png)
Mean EAD is still the same between alternative and alternative comparison report. We should have mean EAD and mean EAD reduced.

**Comment by codymccoy** [comment]
This was the alt comp report mean calls:
![image](https://user-images.githubusercontent.com/47757848/180238142-5950daad-1348-4541-84a2-1d9685bf4181.png)

I replaced them to be this:
![image](https://user-images.githubusercontent.com/47757848/180238211-cce16889-66ed-4511-8e55-9d214a6d7a07.png)

**Comment by rnugent3** [comment]
looks right. I'll backcheck and close this issue when in main.

**Comment by rnugent3** [comment]
this is fixed
