### ISSUE TITLE
table headers should be consistent 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#450]
![image](https://user-images.githubusercontent.com/25163165/179425822-bc13a74d-e3a7-4446-a27a-87031fcdf49b.png)

**Comment by codymccoy** [comment]
ProbabilityExceedsValueLabel = "Probability that damage reduced exceeds indicated value";
The above label was only showing for AAEQ and I was removing the "reduced" when it was EAD. That is what I am doing for Alternatives also. I am now using the "reduced" word in both ead and aaeq damage with uncertainty table for alt comp reports.

This will be in Task_Review_Fixes by the end of the day.

**Comment by rnugent3** [comment]
Looks great. Thank you.
