### ISSUE TITLE
uncaught exception with the aggregated stage-damage function tab to pop-out window command

### ISSUE THREAD

**Issue by jbslaughter** [HydrologicEngineeringCenter/HEC-FDA#462]
CI-CD # Build date 2022-05-20.

Exception occurred with an Existing study - opened in the same build the study was created in when the Aggregated Stage-Damage Function tab (opened by clicking the edit command from the study tree) pop-out window icon/command was clicked. The attached video displays the steps. The attached text file gives the exception text.

https://user-images.githubusercontent.com/89167848/181049634-5deed632-b63c-44da-a7db-107ee5f90377.mp4

[Aggregated_Stage-Damage_Fun_pop-out_cmd_2022-07-20.txt](https://github.com/HydrologicEngineeringCenter/HEC-FDA/files/9191220/Aggregated_Stage-Damage_Fun_pop-out_cmd_2022-07-20.txt)

**Comment by rnugent3** [comment]
the data Julia used is the bear creek mix all data

**Comment by codymccoy** [comment]
This must be from an old build. The stage damage editor is one of the ones that we disabled the pop out feature because of this bug.

![image](https://user-images.githubusercontent.com/47757848/181588424-3a311afe-226d-4961-b97c-2f40a9cf0c18.png)

This fix (workaround) is in the main branch.

**Comment by jbslaughter** [comment]
So did I download the wrong snapshot from CI-CD?

**Comment by rnugent3** [comment]
Julia, you were using a build from May, right?

**Comment by jbslaughter** [comment]
Yes that's correct. I was thinking about the exception I encountered yesterday with opening an old study with a new build... guess I need more coffee this morning...

**Comment by rnugent3** [comment]
Haha! Grab a fresh cup :) 

If you encounter this with the latest build, we'll tackle it right away.
