### ISSUE TITLE
Exception if you try to open the same study twice

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#463]
![image](https://user-images.githubusercontent.com/47757848/181379773-12a28440-485f-498e-adeb-35e46848da74.png)

I opened lower cache creek and then opened lower cache creek again.

**Comment by rnugent3** [comment]
so the problem we thought was fixed was not actually fixed?

 I'd like to get this fixed before we send out the beta.

**Comment by codymccoy** [comment]
I think this is a new issue. It is maybe related to the other file locked issue, but we should not allow the same study to open twice. I will check for this. Should be as easy fix.

**Comment by rnugent3** [comment]
ohhhhhhhhhhhhhhhh I misunderstood. you have one LCC instance open, and attempt to open another LCC instance (same sqlite file) right?

**Comment by codymccoy** [comment]
correct.

**Comment by codymccoy** [comment]
This is now fixed in the stage_damage_edited branch. I added logic to check if the selected path is the same as the current study path. I added this logic in two places. One is for the "recents" list and the other is for the "open" menu item.
![image](https://user-images.githubusercontent.com/47757848/181586187-bd5832de-4af2-4c12-8741-40b2d69c63b5.png)

![image](https://user-images.githubusercontent.com/47757848/181586218-2edaa0a4-b9d6-459c-aba2-108b4c50290f.png)

![image](https://user-images.githubusercontent.com/47757848/181586254-af0b7616-f979-4007-ad63-41eb897bd65e.png)

**Comment by rnugent3** [comment]
I am on the stage_damage_edited branch, opened the muncie example study, launched another instance of fda, attempted to open the same study from the recents list, and hit the uncaught exception. 
![image](https://user-images.githubusercontent.com/25163165/182042130-49da9ee8-0cbc-41bc-b636-d5d3b6ff46e7.png)

**Comment by rnugent3** [comment]
When I attempt to open the same study twice from the open menu item, nothing happens. I think a message would be helpful. 

https://user-images.githubusercontent.com/25163165/182042302-1bea3d64-ecea-442f-b103-8e6924a81c44.mp4

**Comment by codymccoy** [comment]
I thought about popping up a message but i figured if they are trying to open a study that is already open then we have already succeeded in doing what they wanted. We have opened the study that they selected. It is easy to pop up a message though. Something like "This study is already open." ?

**Comment by codymccoy** [comment]
Not totally sure what the best way to handle multiple instances of fda being open. That is not something i have thought about. I don't see anyway of tracking that other than putting a try-catch around the open study and throwing a nicer message if it throws an exception.

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/182188126-99eede62-cf4a-4d19-a58d-345637624943.png)

**Comment by codymccoy** [comment]
I added a try catch around the open study logic. I display the following message:
![image](https://user-images.githubusercontent.com/47757848/182191419-b67b4378-d3fc-4563-9550-ba8f3409737d.png)

**Comment by rnugent3** [comment]
perfect thank you
