### ISSUE TITLE
File browser shows up skinnier than other controls

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#468]
![image](https://user-images.githubusercontent.com/47757848/181775140-b0eb3a87-d0e1-4d07-adf5-7dd14d708044.png)

Maybe there is a margin on the control. It would look better if it matched other textbox heights.

**Comment by Brennan1994** [comment]
Agreed. This one just doesn't bother me much. Gonna leave it open but unassign it.
