### ISSUE TITLE
Alternative does not compute 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#472]
Unable to view alternative results. Compute progress never goes beyond 0. 

Could be spurious, but this might be related to #471. If we can't load the results, then alternative can't compute. What's more, these two issues surfaced at the same time.

**Comment by rnugent3** [comment]
main branch

**Comment by codymccoy** [comment]
I don't think the progress bar is not connected to anything. I am waiting to capture your progress report events.
I computed an alternative in lower cach creek study 1 and it showed the alternative results.

I opened Peres and computed alternative Without Base - Future and it displayed the results.

I am in branch bug_fixes.

**Comment by codymccoy** [comment]
@rnugent3 I think this one should be tested again. I am guessing that recent updates from Brennan and I have resolved these issues.

**Comment by rnugent3** [comment]
behaves as expected
