### ISSUE TITLE
Exception attempting to create new stage damage functions

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#475]
I am on stage_damage_edited. I have latest and rebuilt. I imported bear creek mix, imported sf8 and sf9 impact areas. I hit "create new stage-damage functions" and ran into the following exception: 

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=HEC.FDA.ViewModel
  StackTrace:
   at HEC.FDA.ViewModel.BaseViewModel.Validate() in C:\Code\C#\FDA\HEC-FDA\ViewModel\BaseViewModel.cs:line 163

**Comment by codymccoy** [comment]
I couldn't replicate this, but the call stack you posted showed me what object must be null. I added a null check that should fix this bug. Fixed in branch bug_fixes

**Comment by rnugent3** [comment]
Confirmed.
