### ISSUE TITLE
How is monotonicity handled?

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#48]
Confirm how FDA handles strict positive monotonicity of functions with uncertainty.

**Comment by HenryGeorgist** [comment]
https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/2ab8cb421432c9b09777eb3620736c089a087dd2/Functions/CoordinatesFunctions/CoordinatesFunctionConstants.cs#L432

the code around this area is where monotinicity tests are stored - they would be called during validate (i am pretty sure)
