### ISSUE TITLE
Backwards compatible database changes

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#480]
It is a general aim for FDA to move toward xml in the database. For all future tables going forward I think we should expect 2 columns: ID, XML. The current style uses tables with lots of columns and some relational tables where one table points at other tables. This becomes difficult to update. If we add a new value to the fda UI then we need to add a new column. This will break the existing structure and make it difficult to have backwards compatibility. If the data is stored in XML, updates become easier. You can just add the new value and then check for it when loading and if it doesn't exist, add a default value for it.

How to add columns to an existing table:
For the best example look at the Load() method on StageDamagePersistenceManager.
I wanted to add a new value which required a new column in the database table. When the load method gets called I check to see how many columns are in the table. This determines if I am dealing with an old study or a new one. If I am dealing with an old study, then I add the column to the table and fill it with default values. It is important to always add any new values at the end of the table. Apparently it is easy to add columns to the table, but not easy to insert them anywhere else.

The general strategy should be to put the backwards compatibility logic in the Load() method of the persistence managers. The load method needs to check the table and see if it needs to be updated. If it does, it should update the data to conform to the newly desired table structure.

How to remove columns from an existing table:
It seems likely that at some point we will want to convert a table from having many columns to one that has only two: ID, XML.
I don't have a good example of this in FDA but I think it would look something like this:
1.) In the load method of the persistence manager you would read the rows from the table (see StageDamagePersistenceManager).
2.) You would then ignore the ID column and combine all the other data in each row into a string of xml data.
3.) Add a method in the Connection class to "DROP" columns. Probably by passing in the column name to drop.
4.) Add the "XML" column and then call "UPDATE" where ID = id for each row. 

Other considerations:
Do we want to move to purely xml? We could have a single txt file in the study folder, or a txt file for each element type? I don't see any reason to do this giant refactor to accomplish this goal but maybe others have an opinion. 

The sqlite tables are constructed in a special way that automatically creates a new id for each row. This is why in my descriptions above, it is easier to modify existing tables as opposed to just grabbing the data, deleting the old table and writing a new one. You would potentially screw up the id's that other elements are counting on. The id's always increment from the highest value. If you created elements 1, 2, 3 and then deleted 2, you would be left with 1, 3. If you delete this table and create a new one you would have id's of 1,2. You could then loop over the rows and update the id column to be the id's that you had before. But this seems a bit convoluted.

**Comment by codymccoy** [comment]
We have decided to convert all the database tables over to two columns: ID and XML. All the backwards compatibility logic will now take place in the reading of the xml. This will take place in the xml ctor on each element.

**Comment by codymccoy** [comment]
This work is being done in "xml_refactor" branch.

**Comment by codymccoy** [comment]
This is completed.

**Comment by rnugent3** [comment]
woohoo! thank you.
