### ISSUE TITLE
change structures storage

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#482]
instead of saving structure data to geo package, just save the shapefile in the study directory. we'll want to save to xml a concordance between the required/optional attributes and the field names in the shapefiles.

**Comment by rnugent3** [comment]
@Brennan1994 please add any details

**Comment by codymccoy** [comment]
This is completed and is in the Main branch. 
example of the xml:
![image](https://user-images.githubusercontent.com/47757848/191111997-8ff4f4af-a1a3-4289-aa3a-b4493a923dc9.png)

example of the shapefile in the study directory:
![image](https://user-images.githubusercontent.com/47757848/191112052-7d565156-c8c0-47c8-a8a6-c2958d118529.png)

**Comment by rnugent3** [comment]
This is great. Thank you.
