### ISSUE TITLE
Create StageDamageConfiguration object

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#484]
This will be the object that gets passed to the model to compute stage damages

**Comment by codymccoy** [comment]
I created this object. This object should hold everything required to run a stage damage compute. It also has the ability to validate itself before attempting the compute.

![image](https://user-images.githubusercontent.com/47757848/183101524-303aaac4-fa3d-4e94-932f-707d0feada0e.png)

**Comment by rnugent3** [comment]
what branch is this on?

**Comment by codymccoy** [comment]
xml_refactor. It probably won't get pushed to main for a few days.

**Comment by rnugent3** [comment]
do we need occupancy types in here, too?

**Comment by codymccoy** [comment]
oh, yeah. I think so. I will add that. We need more structure logic once we do the big structure inventory saving refactor. We also probably need more validation.

**Comment by rnugent3** [comment]
Understood. Thank you.

**Comment by codymccoy** [comment]
Brennan is creating a model object that he will be able to use for the compute. I will need to add a method on the config object that can create this new model object. The VM class will look something like this:
![image](https://user-images.githubusercontent.com/47757848/183128595-9b194779-17b6-4ef0-be4b-ed371ebc77fe.png)

**Comment by Brennan1994** [comment]
We had a discussion on this today, and cody is moving forward.
