### ISSUE TITLE
Improved architecture

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#491]
After a discussion with Brennan I think this would be an improved architecture for FDA. Define a model "Element" for each element type (ie: RatingElement, InflowOutflowElement) instead of having them in the VM. The VM would then have tree elements that hold a model.Element and the other tree related properties. I think we would then move the study cache down to the model, although maybe it could still live in the VM. There is not a huge benefit in doing this refactor, but I think it would be a better design because our current ChildElement class is mixing view items (font, bold, tooltip) with the data items (name, desc, curve, etc).

![image](https://user-images.githubusercontent.com/47757848/184658473-81139300-9581-4b92-b93a-edd922b4247a.png)

**Comment by rnugent3** [comment]
@codymccoy @Brennan1994 is this a relatively urgent refactor or a just a good opportunity to buy down technical debt?

**Comment by codymccoy** [comment]
No urgency at all. We don't ever have to do it and we would be just fine. I think this refactor would just adhere better to a single responsibility principle. The model "Element" we be responsible for the data relating to that element type (rating, ext-int, etc). The VM "TreeElement" would be responsible for tree properties. Right now we have kind of mixed the two into a single "ChildElement" object.

**Comment by codymccoy** [comment]
I probably wouldn't advocate for doing this unless someone has a compelling reason, or we fall into a bunch of money.
