### ISSUE TITLE
Monotonicity check

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#492]
All curves should be weakly monotonically increasing except for the frequency functions which should be strictly monotonically increasing

**Comment by rnugent3** [comment]
And the messages should be consistent

**Comment by Brennan1994** [comment]
This appears to have been fixed. Closing.

**Comment by rnugent3** [comment]
I respectfully disagree. Please see the validation in the image below. If these rows were checking only for weak monotonicity, they would not be highlighted. 

![image](https://user-images.githubusercontent.com/25163165/193887736-5e48a7bc-cc37-4867-aca4-28557c20d9d7.png)

**Comment by Brennan1994** [comment]
Acknowledged.
