### ISSUE TITLE
Need index points and occtype icons

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#493]
These icons should be placed in the resources folder next to the others and then update the path in the class: ImageSources.

**Comment by rnugent3** [comment]
looks like a .png would work, we don't need a .ico?

**Comment by codymccoy** [comment]
Correct. I think any picture format probably works. Looks like all our others are .png. They are in the View.Resources folder. You could even open an existing in paint and modify it to create a new one.

**Comment by codymccoy** [comment]
Or use maintenance money to have Deziree do them. She did the scenario, alternative, alt comp report icons.

**Comment by rnugent3** [comment]
I'll come up with something one afternoon this week when my brain is fried. sounds like fun!!
