### ISSUE TITLE
Occtype editor uncertainty property rules

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#495]
Point the normal, uniform, triangular at the model objects and use those rules where appropriate. There are two styles of uncertainty here: one is relative and doesn't require rules, the other is more concrete and requires rules.

**Comment by codymccoy** [comment]
Uniform:
This uniform should have property rules:
![image](https://user-images.githubusercontent.com/47757848/185240287-6bff917b-45a6-4d13-a770-f3a2bcf4da06.png)

These should not:
![image](https://user-images.githubusercontent.com/47757848/185240407-3e469072-b9d6-4ee0-be74-24b210a2bec6.png)

**Comment by codymccoy** [comment]
Normal:
Uncertainty that shows "mean" should add a rule that it needs to be positive:
![image](https://user-images.githubusercontent.com/47757848/185241364-c2f72d5a-13bc-4021-a3f7-df9b25250d57.png)

The other normal uncertainty has the rules from the model for st. dev.:
![image](https://user-images.githubusercontent.com/47757848/185241565-eef80123-19cd-4950-8291-70f25b6a337d.png)

**Comment by codymccoy** [comment]
Triangular:
The triangular uncertainty that has "Most Likely" should have the property rules from the model:
![image](https://user-images.githubusercontent.com/47757848/185241811-04c3687a-2325-454b-a4eb-00d671f58ed7.png)

The other triangulars should not have rules:
![image](https://user-images.githubusercontent.com/47757848/185241919-b2ed0be5-95ba-4869-a601-5d090bb84215.png)

**Comment by codymccoy** [comment]
This work has been completed on the occtypes_to_xml branch.

**Comment by rnugent3** [comment]
looks great
