### ISSUE TITLE
Move oxy plot toolbar to the right of the plot

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#497]
There is an issue with having the toolbar added to the oxyplot in the "loaded" method:
![image](https://user-images.githubusercontent.com/47757848/185238168-ab596ec1-2ec2-40b3-8480-8625b9bf0fd5.png)
The solution that Richard, Ryan, and Cody have agreed upon is to move the toolbar outside of the oxyplot and place it next to it on the right side.

**Comment by codymccoy** [comment]
Original look of the buttons:
![image](https://user-images.githubusercontent.com/47757848/189450202-af7a49b7-caf9-4ad7-af28-f82fedb5c3ca.png)

The new look of the buttons on the right side of the plot:
![image](https://user-images.githubusercontent.com/47757848/189450230-f4e4d34d-d3d2-4ac9-957f-ca34cd402c9a.png)

**Comment by codymccoy** [comment]
I have all the buttons working as they did before. I still need to do a little code clean up. I will comment out this logic for the time being and finish this up when I get in after my vacation.

**Comment by codymccoy** [comment]
For Cody: this is how to put your new control into the table with plot:
![image](https://user-images.githubusercontent.com/47757848/189450454-398d716c-42b2-4c62-bba0-f04b8fa703dc.png)

**Comment by codymccoy** [comment]
This is now completed in the branch plot_with_toolbar.

**Comment by rnugent3** [comment]
I am not able to open this window in release mode at this time. I will test when the user controls problem is fixed.

**Comment by rnugent3** [comment]
behaves as expected
