### ISSUE TITLE
Occtype Editor UI changes

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#499]
We want to add child occtype elements to the tree just like we do every other child element. Remove the occtype group combobox from the UI. The user will now be editing one occtype element at a time (normal right click menu item). Add name and description fields to the top of the occtype editor.

**Comment by codymccoy** [comment]
This work is completed and has been merged into main.

**Comment by rnugent3** [comment]
confirmed
