### ISSUE TITLE
Unsteady HDF bugs

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#505]
The "Source File:" label should be updated to say "Source Directory:"

I selected a random folder that didn't produce any rows in the table and clicked save and it accepted it. I need to add validation to prevent this.

**Comment by codymccoy** [comment]
I updated the validation logic a bit. I now show the user a warning message box when they select a file (if there are warnings to report):
![image](https://user-images.githubusercontent.com/47757848/186700411-8a1e7e64-3e0b-4e9d-9e79-26a241e5149c.png)

I then show the errors if there are any:
![image](https://user-images.githubusercontent.com/47757848/186700470-df38ecd1-2233-467a-9800-359b1c2001d4.png)

I also added a property rule that will not allow the save button to be clicked if there are no rows in the table:
![image](https://user-images.githubusercontent.com/47757848/186700598-162bab32-fa77-4af7-95f3-de2b85f62b62.png)

I am adding this property rule to steady and gridded hydraulics also.

This is fixed in inventory_xml_refactor

**Comment by codymccoy** [comment]
Property rule on Gridded:
![image](https://user-images.githubusercontent.com/47757848/186701172-5177511b-29c0-48cb-9a52-6ff23df32b73.png)

**Comment by codymccoy** [comment]
Steady:
![image](https://user-images.githubusercontent.com/47757848/186701757-511ad4c2-0b5f-43b9-92c8-eb1e111e3ca6.png)

**Comment by codymccoy** [comment]
This is now fixed in the inventory_xml_refactor branch

**Comment by rnugent3** [comment]
Confirmed.
