### ISSUE TITLE
Testing Cody's Refactor

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#506]
I think it would be good to test all the elements in FDA. Create, rename, edit, delete. The elements that import files should get special attention: terrain, hydros, impact areas, index points, structures. Test that when you create, rename, delete, that the files in the study directory also do what you expect. Occtypes should also get extra attention.

**Comment by codymccoy** [comment]
This testing can commence once the branch inventory_xml_refactor has been merged into main.

**Comment by rnugent3** [comment]
create, rename, and delete work as expected

**Comment by rnugent3** [comment]
edit works as expected

**Comment by rnugent3** [comment]
Anything that arose during testing has been entered on GitHub as dedicated issues
