### ISSUE TITLE
Structure editor bug

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#508]
![image](https://user-images.githubusercontent.com/47757848/186736214-162dac63-81be-426d-98b6-69855ca6f9b9.png)

**Comment by codymccoy** [comment]
This is now fixed in "open_structures_for_edit". To reproduce: one the first page of the structures importer, select an occtype and then go to the second page where you assign occtypes. Go back to the previous page and select a different occtype column header. When this happens I basically reload the second page with the new data.

**Comment by rnugent3** [comment]
Confirmed.
