### ISSUE TITLE
Structure inventory elevations from terrain file bug

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#510]
![image](https://user-images.githubusercontent.com/47757848/186806318-747350fc-e07b-4403-8889-9c8b474f1934.png)

This "getTerrainFile" method was written when the terrains had a different folder structure in the study directory and we were only importing a single file. Now that we support a couple different file types, this method needs to get updated. It currently will never return anything.

**Comment by codymccoy** [comment]
I fixed the one bug. The code now grabs the correct file path. When the file is used, it throws the following GDAL exception.
![image](https://user-images.githubusercontent.com/47757848/186809071-cd00e934-fcc2-4cc4-ab21-25ac1cd60086.png)

@Brennan1994 How should we fix this?

**Comment by Brennan1994** [comment]
Don't do anything here. Not the view model's job. We just need to hand the Terrain to the Model and it'll handle the rest.

**Comment by codymccoy** [comment]
Ok. I commented out the line to get the rasters from lifeSimGis and put a todo statement above the commented out code.

**Comment by Brennan1994** [comment]
I left the design the same as yours, but now you reference a static method in model to get elevations rather than you terrainElevation helper class (which is now gone)

**Comment by Brennan1994** [comment]
Testing still necessary, but the issue as described above is resolved.
