### ISSUE TITLE
blank menu item 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#516]
![image](https://user-images.githubusercontent.com/25163165/187007854-9e299d38-e8be-4805-bb3e-c7e143ceeea9.png)

**Comment by codymccoy** [comment]
This should be fixed. I don't have a study in a state where i can easily create a scenario, so i did not test this. The issue was that I forgot to pass in the string for the "edit" menu item.

fixed on branch bug_fixes.

**Comment by rnugent3** [comment]
Confirmed.
