### ISSUE TITLE
Uncaught exception saving inventory 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#520]
![image](https://user-images.githubusercontent.com/25163165/187045363-759f7435-08fa-4c7a-9c37-a7f6f5008f99.png)
this exception occurred when I hit next, for the muncie NSI example inventory

**Comment by codymccoy** [comment]
Fixed in branch bug_fixes.

I was calling a method that used the _SelectedOcctypeName one line before it was assigned. I just had to flip the order of these lines.

**Comment by rnugent3** [comment]
Confirmed.
