### ISSUE TITLE
histogram display 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#521]
when a histogram is zero valued or single valued, we do not want to display the histogram. there are properties on the histogram to check for this. 

![image](https://user-images.githubusercontent.com/25163165/187045526-11bd3d85-e19d-45e7-b49f-bf44ae66fa20.png)

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/189362243-51741cbd-f1be-4c4e-aa35-8b09b9d80e2e.png)

I believe this issue is completed. It was a little tough for me to test all of them with the study that I have.
This work was completed on branch github_issues

**Comment by rnugent3** [comment]
I'll see about testing this

**Comment by rnugent3** [comment]
#574 prevents me from testing this issue at this time

**Comment by rnugent3** [comment]
#617 now prevents me from testing this issue - we need to be able to compute with zero damage

**Comment by rnugent3** [comment]
behaves as expected
