### ISSUE TITLE
weird study save problem

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#522]
sometimes when I create a study, two study directories are created, and both appear empty. 

![image](https://user-images.githubusercontent.com/25163165/187045856-6f29ea5d-9ade-4f6c-9cce-9f26f761137c.png)

**Comment by rnugent3** [comment]
![image](https://user-images.githubusercontent.com/25163165/187045904-96f43a1a-4a3e-4067-a4be-2de0a8051486.png)

the study opens but the folders appear empty

**Comment by rnugent3** [comment]
opening both folders, I see "This folder is empty" ... I am not sure if this is an FDA problem or a Windows problem?

**Comment by codymccoy** [comment]
@rnugent3 Were you creating a study from scratch or importing from old fda?

**Comment by codymccoy** [comment]
The study folder should have these files and folders by default when creating a new study.
![image](https://user-images.githubusercontent.com/47757848/187449575-60b399a1-be1a-48c0-a1ed-086a14147a66.png)

**Comment by codymccoy** [comment]
I am unable to reproduce this. I am not sure how it would be possible for fda to run without the *.sqlite file being in the folder.

**Comment by rnugent3** [comment]
I was importing from old fda.

**Comment by codymccoy** [comment]
I tried importing from old fda and did not see this behavior.

**Comment by rnugent3** [comment]
I'll attempt to reproduce this at a later time. For now, this is not critical.

**Comment by rnugent3** [comment]
Failed to reproduce. I am going to close this and we can open a new issue in the event that this happens again, hopefully with better steps from me to reproduce.
