### ISSUE TITLE
change foundation height to first floor elevation in occupancy types

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#524]
Please change the label "foundation height uncertainty" in occupancy types to "Uncertainty in First Floor Elevation"

**Comment by codymccoy** [comment]
Fixed in branch bug_fixes

original:
![image](https://user-images.githubusercontent.com/47757848/187447967-e9f52baf-e7d7-4196-a19c-ca2da95243ff.png)

update:
![image](https://user-images.githubusercontent.com/47757848/187448023-64a0d20f-e28f-492a-88f3-7f61d09fe0ed.png)

**Comment by codymccoy** [comment]
This is completed in branch github_issues

**Comment by rnugent3** [comment]
Confirmed.
