### ISSUE TITLE
scenario compute bug.

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#525]
I created a scenario, then deleted the stage damage curve that it relied on, and then tried to compute. This threw a null pointer exception.

**Comment by rnugent3** [comment]
How would you suggest we get around that? 

It seems like if the stage-damage doesn't exist then the scenario should be in a fatal error state and shouldn't be able to compute.

**Comment by codymccoy** [comment]
The validation logic i have, is after the null pointer exception. I basically need to move it up in the order of things.

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/189387735-c63ce299-8a26-433e-8a1b-f60a93ac64c8.png)

This is now completed. I check before running the compute if all the elements assigned in the scenario still exist. 
Fixed in branch github_issues.

**Comment by rnugent3** [comment]
is the github_issues branch something we could PR relatively soon? I think there are some fixes on that branch that would be great to have in the beta

**Comment by codymccoy** [comment]
Is the end of the day ok, or do you want it sooner? Noon?

**Comment by rnugent3** [comment]
End of day, even Monday would be OK.

**Comment by codymccoy** [comment]
I will get it done today. I am off all next week on vacation.

**Comment by codymccoy** [comment]
Completed, ready for testing. Fixed in branch github_issues.

**Comment by rnugent3** [comment]
confirmed.
