### ISSUE TITLE
Assign asset category upon import

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#533]
please assign imported stage-damage functions to the "Total" asset category upon import

**Comment by codymccoy** [comment]
I believe that this is already what happens.
 
![image](https://user-images.githubusercontent.com/47757848/191307296-652bafd4-71dc-4b82-ba20-dedfe0656c3d.png)

![image](https://user-images.githubusercontent.com/47757848/191307320-5859b508-842b-4861-962e-bbc32f538d05.png)

**Comment by rnugent3** [comment]
this hadn't worked with a previous build but I see it working now, thank you
