### ISSUE TITLE
EAD does not show up for preview compute 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#535]

**Comment by codymccoy** [comment]
The ead is shown here:
![image](https://user-images.githubusercontent.com/47757848/191295335-144dd4bc-5abd-4812-bc88-c5208b0cac4b.png)

It gets a little hidden (a lot going on in this UI). Let me know if you want me to draw more attention to it somehow.

In my current study it seems to always be zero. This is the call i am using to get the ead:
![image](https://user-images.githubusercontent.com/47757848/191295790-b1240d35-ebf8-4d74-9f3c-22247ca03c18.png)

Note that the ead will not show up if a damage frequency curve was unable to be created:
![image](https://user-images.githubusercontent.com/47757848/191295983-3398ec52-37d8-43fe-bee0-fb138ed0bf38.png)

**Comment by rnugent3** [comment]
the damage frequency in the image you shared indicates that EAD should not be zero

**Comment by rnugent3** [comment]
I'll attempt to debug. In which class do you have the preview compute in the above image?

**Comment by codymccoy** [comment]
SpecificIASEditorVM line 495

**Comment by codymccoy** [comment]
There are a couple of issues here that i am trying to clean up. You are reporting a message that is usefull, but I am not currently capturing it. I will work on doing that. It looks to me like the reason that a good EAD number is not produced is because there is a mismatch in the dam cats. One is "AUTOS" and the other is "TOTAL". I will look into that more.

**Comment by codymccoy** [comment]
After computing the result, we ask for the mean damage using "Total"
![image](https://user-images.githubusercontent.com/47757848/192602928-8f0e6da8-1c08-4f7e-8d0c-df5fbbbea5bb.png)

The result object only has a value for "Auto"
![image](https://user-images.githubusercontent.com/47757848/192603087-60bc897a-b840-4fc2-9804-e92d85ea112e.png)

**Comment by codymccoy** [comment]
The UI has the damage category selected as "AUTOS"
![image](https://user-images.githubusercontent.com/47757848/192603284-e37b3c41-9525-4ff6-8ad8-cf02506ce563.png)

@rnugent3 For the EAD should we be looking for "Total" or should we just look for the damage category that is selected?

**Comment by rnugent3** [comment]
Very good question. It looks like we're only returning a damage frequency function for total:
https://github.com/HydrologicEngineeringCenter/fda-model/blob/4f017f10dc47fe57b76d29b4b33806f85af63a84/fda-model/compute/ImpactAreaScenarioSimulation.cs#L482
I think the easiest thing then would be to nuke the damage category combo box and show EAD for "Total"

**Comment by codymccoy** [comment]
As a test, i changed this line from total, total to be autos and unassigned and I was able to get an ead.
![image](https://user-images.githubusercontent.com/47757848/192607367-2b000c92-58e5-4721-8604-ae07d80bf85f.png)
![image](https://user-images.githubusercontent.com/47757848/192607384-0cca4e93-ea4c-43ec-bc52-b9ac5f708e45.png)

**Comment by rnugent3** [comment]
oh boy. okay I need to think about this carefully. I will get back to you shortly.

**Comment by codymccoy** [comment]
Wasn't the damage category combo telling us which curve to plot for the stage damage?

**Comment by rnugent3** [comment]
I am not sure, but it seems the only damage frequency curve being returned is the total damage frequency.

**Comment by rnugent3** [comment]
ha! this should have been obvious to me. sorry. YES. You want to pass the selected damage category into the MeanDamage method. We should probably have a combo box for asset category, and then pass the asset category selection into the method, too.

**Comment by codymccoy** [comment]
ok, that makes sense to me.

**Comment by rnugent3** [comment]
Great. Thank you.

**Comment by codymccoy** [comment]
I have added the asset category combo and updated the ead call to pass in the selected dam cat and asset.
![image](https://user-images.githubusercontent.com/47757848/193302489-a4d39e9a-0e20-4a37-898a-a0c2033e3d0a.png)

![image](https://user-images.githubusercontent.com/47757848/193302529-8602e079-4091-43e8-bcd6-e51ac2133787.png)

**Comment by codymccoy** [comment]
I am still getting an ead of 0. In the model, GetConsequenceResult() is returning a dummy object because the _consequenceResultList is empty.

![image](https://user-images.githubusercontent.com/47757848/193303310-6ab9f1ee-d594-4808-ba7a-3a2e3ce5fdbf.png)

**Comment by codymccoy** [comment]
I think the problem i am having now is that when the model goes to calculate the ead, it grabs the dam cat and asset category from the uncertain paired data - curve meta data. I am storing asset category in its own property. I think if i get rid of the separate entry in the xml and assign the UPD asset category this will start working. 
![image](https://user-images.githubusercontent.com/47757848/193306537-ba7b006e-bdfe-47b6-855e-d47a2c3ac235.png)

**Comment by codymccoy** [comment]
This is now fixed and has been merged into main.

![image](https://user-images.githubusercontent.com/47757848/193637403-92492e85-3483-4cc5-a01b-19af128aa268.png)

**Comment by rnugent3** [comment]
behaves as expected
