### ISSUE TITLE
switching b/w unique names for index points adds rows

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#538]
![6BB55A83-9078-455B-A9D6-DE4DC442691D](https://user-images.githubusercontent.com/25163165/191143449-ddc0bc29-52d5-4763-b8db-535a0d41f169.GIF)

**Comment by codymccoy** [comment]
Fixed. I added a line to clear the rows on every selection. I checked the impact areas importer because it is nearly identical and it was clearing the rows every selection.

![image](https://user-images.githubusercontent.com/47757848/191277364-2559b62a-1c84-4134-95f3-ec3407e363ae.png)

**Comment by rnugent3** [comment]
confirmed thank you
