### ISSUE TITLE
Steady HDF Bugs

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#539]
I selected one of the HDFs from the directory of 8 HDFs from the Muncie, IN example study. Two things: the names should be fixed. Second: what has been imported seems odd. This was 1 HDF from an unsteady directory I pretended was steady. 

![image](https://user-images.githubusercontent.com/25163165/191145495-d16d99da-a568-4e40-ba01-1e276136d534.png)

**Comment by Brennan1994** [comment]
@codymccoy  there's a demo of how to do this in the ViewModelTest project under IntegrationTests/RasMapperLibShould.cs

**Comment by codymccoy** [comment]
Using that unit test made this easy. I don't know if exceptions get thrown from that ras mapper call so i threw it in a try-catch.
![image](https://user-images.githubusercontent.com/47757848/193636385-3435548f-c499-4ce6-a304-f016ab236455.png)

This is completed in branch: progress_bar

**Comment by rnugent3** [comment]
@Brennan1994 could you please set us up with some steady HDF test data?

**Comment by Brennan1994** [comment]
Study data has been added to the resources folder of FDA Model Tests. The issue described above has been resolved as well. Testing is ongoing, but this issue as written is resolved

**Comment by rnugent3** [comment]
Thanks, @Brennan1994 !
