### ISSUE TITLE
use import editor for occupancy type import for consistency with other import editors

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#541]
this is a low priority enhancement

**Comment by codymccoy** [comment]
@rnugent3 I am not sure what this means. I have the following import menu item for occtypes:
![image](https://user-images.githubusercontent.com/47757848/191344094-4f789a40-b6d9-4897-baf7-931399878c47.png)

This opens the standard importer like the others. I noticed that it had the wrong title in the tab:
![image](https://user-images.githubusercontent.com/47757848/191344200-96080603-68a4-4f1e-9875-ea7fc979ba00.png)
The tab header is now fixed.

**Comment by rnugent3** [comment]
I was thinking the editor where we can select the file and give the imported object a name

**Comment by codymccoy** [comment]
I don't think any of the importers have a name field except for when importing a whole new study: 
![image](https://user-images.githubusercontent.com/47757848/191599751-30eb1760-5f8a-46c9-ae31-308c441e1033.png)

I don't think it would take long to add a name and a description field to the current importer.

**Comment by rnugent3** [comment]
what about terrain and hydraulics?

**Comment by codymccoy** [comment]
Yes, those have a name and description field. I forgot about those. I will try to match the way that those look when i update the import from old fda UI.

**Comment by rnugent3** [comment]
that would be great, thank you!

**Comment by codymccoy** [comment]
Name and description added to the UI:
![image](https://user-images.githubusercontent.com/47757848/191617744-88407375-a353-4eee-bc68-4f95c342a1e2.png)

**Comment by codymccoy** [comment]
Completed.
![image](https://user-images.githubusercontent.com/47757848/191809637-06e227d6-1ddd-4234-b2f6-0ace817a608b.png)

**Comment by codymccoy** [comment]
I tested a couple of them, but not all. There are several elements that use this importer. A bug arose where clicking close was displaying the "are you sure you want to close with unsaved changes". I have fixed that, but if you test these changes you might also test that clicking close does what you expect.

**Comment by rnugent3** [comment]
I will give this a good test.

**Comment by rnugent3** [comment]
I will test this issue and the other issues recently resolved on the stage damage branch when the user controls bug is fixed.

**Comment by rnugent3** [comment]
I have tested and confirmed that the following behave as expected:

- Frequency functions
- Regulated-unregulated transform flow functions
- Stage-discharge transform functions
- Exterior-interior functions 
- Lateral structures
- Occupancy types
- Stage-damage functions
