### ISSUE TITLE
stage-damage index points

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#542]
please unhook stage-damage from the index points. we went with an alternate approach as part of the stage-damage compute

**Comment by codymccoy** [comment]
@rnugent3 I will remove the index points from the UI:
![image](https://user-images.githubusercontent.com/47757848/191327999-cc6d82c5-6a1b-4ab4-9ab6-bd68ba631437.png)

I will remove the index points from the xml that is being saved out.
I will remove the warning about stage damages when deleting index points.

**Comment by rnugent3** [comment]
perfect thank you

**Comment by codymccoy** [comment]
This is now completed. While testing that the xml was working, i discovered a bug where the stage damage rows were not loading correctly. That is now fixed too.

![image](https://user-images.githubusercontent.com/47757848/191364715-0b31d1f9-14a3-4504-86ca-615683ad388a.png)

**Comment by rnugent3** [comment]
looks great
