### ISSUE TITLE
Index Point Importer Unique Name Does Not Clear Previous Selection

### ISSUE THREAD

**Issue by jbslaughter** [HydrologicEngineeringCenter/HEC-FDA#546]
Build Date: 9/19/2022 (Provided by Richard)

Issue: Create New Index Point tab - the Unique Name selection does not clear previous selection when someone changes the dropdown menu selection (see video). For example, select STATION_NM then select SITE_NO and both unique names are imported for the index point.

https://user-images.githubusercontent.com/89167848/192341076-46b834a6-4c87-4748-9855-a6d5246205c0.mp4

**Comment by jbslaughter** [comment]
Hi Richard, sorry for double-submitting I did a search and didn't see your issue because I didn't look at closed issues.

**Comment by rnugent3** [comment]
all is well :)
