### ISSUE TITLE
Round Hydraulic UI values

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#552]
These long numbers look bad. Let's round to 3 decimal places?
![image](https://user-images.githubusercontent.com/47757848/193629600-d93b0785-9256-46fb-9393-f059dd3da26b.png)

**Comment by codymccoy** [comment]
All three hydro types (gridded, steady, unsteady) all use the same table control. I updated that to round to 3 places.
![image](https://user-images.githubusercontent.com/47757848/193633525-339cb383-e64a-4cad-934b-85058be58e02.png)

![image](https://user-images.githubusercontent.com/47757848/193633550-cac4932f-8abc-420d-83bb-c57587d6718f.png)

**Comment by codymccoy** [comment]
This is completed in branch: progress_bar

**Comment by rnugent3** [comment]
Thanks for taking the initiative, @codymccoy
