### ISSUE TITLE
Impact area id's not returning correct numbers from stage damage compute

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#565]
The impact area id's getting returned were all zero. I think part of the problem is this method:
![image](https://user-images.githubusercontent.com/47757848/194388006-14f503e9-86fc-45e2-ab31-ea1c0815eff4.png)

An impact area id is passed into the method but is not used. I think it needs to replace the consequenceResult.RegionID.
I made this change and then all my impact area ids were 14. Since i was grasping at straws, i changed it back to the original state.

There might be an issue with this method:
![image](https://user-images.githubusercontent.com/47757848/194388361-41dad567-5eeb-4acd-b883-3838a9042b30.png)

It is getting the impact areas from the last y value. That doesn't seem right to me, but i don't understand what all is happening in this code.

**Comment by codymccoy** [comment]
This is where i grab the impact area id to display in the UI:
![image](https://user-images.githubusercontent.com/47757848/194388733-b3690838-6d2c-4a1f-94de-94926ef9a223.png)

Since i don't have good id's, the impact area rows are empty for the impact area name.
![image](https://user-images.githubusercontent.com/47757848/194388826-b5bef353-d515-4eb3-b368-b23480529f54.png)

**Comment by rnugent3** [comment]
GetImpactAreas() works as expected. I just wrote a test to confirm. It can happen on the last ConsequenceDistributionResults object in the array because each ConsequenceDistributionResults object holds a ConsequenceDistributionResult object for each impact area, damage category, asset category combination.

**Comment by codymccoy** [comment]
I think you made these changes on my branch, but I am still not getting impact area id's back. I am trying to diagnose what is going on. I think there is probably an issue in this class:
![image](https://user-images.githubusercontent.com/47757848/194924282-555e74a2-21ce-481e-9831-1d28001d7ce9.png)

The impact area ids and the dam cats are passed into the ctor but they are never used.

**Comment by codymccoy** [comment]
It looks to me like you are getting the impact area id and the dam cat from the "ConsequenceResults" object that is created in the pic above on line 21. Maybe the imp area ids and the dam cats need to be passed into that object? either on line 21 or in the compute on line 27?

**Comment by codymccoy** [comment]
Ok, i think the issue is that the top one is getting called in my case, instead of the bottom one:
![image](https://user-images.githubusercontent.com/47757848/194924811-e6b7ddf3-d9e2-41cd-896f-21963edc0654.png)

I will call the bottom one and see what happens.

**Comment by codymccoy** [comment]
Or maybe the problem is here: The correct impact area ID is being passed in but that value is never used. It looks to me like the impact and dam cat come from the inventory. This inventory doesn't have the correct info in it.
![image](https://user-images.githubusercontent.com/47757848/194928591-354b9baf-92c0-410e-8574-00d61ef3de5b.png)

**Comment by codymccoy** [comment]
The dictionary of impact area id's gets passed into the inventory. This dictionary seems to have the correct values in it. But then the impact area id's get calculated based off the structures in this method:
![image](https://user-images.githubusercontent.com/47757848/194930651-69a2030d-ad2c-49b6-9549-09e51ddd23a1.png)

Maybe we can get rid of that and just use the dictionary?

**Comment by codymccoy** [comment]
I thought that this change might fix the impact areas, but it did not. I am going to revert that change and move on.
![image](https://user-images.githubusercontent.com/47757848/194948453-15d5a6b7-f97f-4d57-93b3-a86145ec18fb.png)

**Comment by rnugent3** [comment]
@codymccoy FYSA I am back working on this today

**Comment by rnugent3** [comment]
Ah! It looks like I forgot to mention explicitly that we can't make progress on this issue until we make progress on #576. I apologize for not communicating that. You're right - the impact area ID and damage category are set by the structure's attributes, but the structure's "impact area ID" is actually the impact area NAME. We need it to be the ID, and I think we need Brennan's help with that.

**Comment by rnugent3** [comment]
Looks like this is resolved 

![image](https://user-images.githubusercontent.com/25163165/212200072-4d46ca88-25e7-4ad6-80d2-756ff0d2f9f2.png)
