### ISSUE TITLE
Change wording of right-click menu option on frequency functions

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#567]
Please change the synthetic frequency function right-click menu item on frequency functions to read "Import Synthetic Analytical Flow-Frequency Function from DBF"

![Uploading image.png…]()

**Comment by codymccoy** [comment]
Original:
![image](https://user-images.githubusercontent.com/47757848/195372847-5957d424-3621-4951-a665-8f3368e4d8e1.png)

Updated version:
![image](https://user-images.githubusercontent.com/47757848/195372897-1f0c586c-d59b-41e5-9e0a-fc78ca03abb0.png)

This is fixed on branch: last_edit_tooltip

**Comment by rnugent3** [comment]
behaves as expected
