### ISSUE TITLE
asset category combo box bug

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#570]
The asset categories found in the scenario editor asset category combo box include duplicates of the actual asset category and erroneous asset categories that do not exist. See the image below. There should be only one option: "Total" 

![image](https://user-images.githubusercontent.com/25163165/194419886-f86c09cd-284a-4fb0-93fa-c6fac481dedf.png)

**Comment by codymccoy** [comment]
I can get rid of the duplicates. I think "USER" and "COMPUTED" is a separate bug that I fixed. Once I fix this, try it with new data.

**Comment by codymccoy** [comment]
This is completed on branch last_edit_tooltip

**Comment by rnugent3** [comment]
Behaves as expected.
