### ISSUE TITLE
table with plot paste improvement

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#572]
I pasted in two columns of zeroes (mean and standard deviation of damage) for the stage-damage function where there were more rows on the clipboard than in the table. Rows were added but the stage for each added row did not increment. See in the image below that each row added has a stage of 479.

**Comment by rnugent3** [comment]
![image](https://user-images.githubusercontent.com/25163165/194431155-b4ec922b-a04c-40c6-84ae-99cd4b27399a.png)

**Comment by Brennan1994** [comment]
This is the behavior I would expect. We could increment based on the difference between the last two cells instead, but I'm not sure if the juice is worth the squeeze. Personally I'd prefer to leave it as is until someone complains about it.

**Comment by Brennan1994** [comment]
Since no action is planned, I'm going to clear assigness. Theoretically this could be anyones task in the future if it's selected for dev.
