### ISSUE TITLE
last edited tooltip

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#573]
the last edited tool tip does not have a last edited date/time for items that were just imported; I think it would be good to have a last edited date/time equal to the time of import for freshly imported items. this is a low priority.

**Comment by codymccoy** [comment]
Looks for some of the items that i import, i am making the last edit date the "CalculationDate":
![image](https://user-images.githubusercontent.com/47757848/195212150-19e52cd9-2740-4b4f-9287-64adcb8eacda.png)

I think this value is coming out of the text file. In my case, and probably yours too, it is an empty string. It sounds like you want me to set it to be the date/time when you import the data. I will make that change.

**Comment by codymccoy** [comment]
This is completed in branch last_edit_tooltip
