### ISSUE TITLE
Cody made changes to hydrology classes

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#575]
As we talked about a couple of days ago, we have a goal of having the VM elements hold on to model objects. This way we don't have to translate from VM data model objects to Model objects. I thought that the HydraulicProfiles class would be a good place to start. It got quite a bit more complicated than I first thought. I will try to outline the changes below. If everyone is good with these changes then we can close this issue. 

1.) Replace the VM PathAndProbability class with the Model HydraulicProfile class. I removed a couple of properties from the HydraulicProfile class so that it only holds the file name and the probability. That class has methods that needed the removed properties so I added them as arguments to the method.

2.) HydraulicDataSet: this class held a list of profiles. I expanded it more to hold a couple of new properties.

3.) The VM HydraulicElement class: I removed all the properties and added a property for HydraulicDataSet. 

4.) One issue I didn't initially anticipate is that profiles were expecting the entire file path but I was only storing the file name with extension. The reason I only want to store the file name is that since the profiles are stored in a folder that is named after the child element, I would have to update all the file paths if the user renames the element. That is a complication I prefer to avoid. To solve this I pass the parent directory path down to any compute method that needs to get the full file path. The method can then concatenate the file name onto the parent path to get the full path.

5.) I changed some of the xml reading and writing so that each piece is responsible for writing itself out. This probably means that any current hydro elements will be broken when this is merged to main.

**Comment by rnugent3** [comment]
I defer to @Brennan1994.

**Comment by Brennan1994** [comment]
This is fine as long as we're still passing tests. Cody and I walked through the changes and I had two comments, 

One: we need to track profile names for steady flow in particular. Thats how we get the correct profile out of the  single HDF file. 

Two: we don't need to track whether it's a depth grid anymore,. We don't use depth girds.

**Comment by Brennan1994** [comment]
We've worked through these issues. Closing
