### ISSUE TITLE
Impact Area Names 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#576]
I think we have completely sorted out tracking impact area names vs impact area IDs, except for one final piece.  

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/0d9b48c253e09087618a0a172c9eb8b96fe57b7f/fda-model/structures/Inventory.cs#L159

At the line at the link above, we are asking for the particular polygon that has a given impact area ID. However, impact area ID is an object that we create and track in the study database. The impact area shapefile does not know about the impact area ID. We need to pass in the impact area name - the unique feature identifier that the user has chosen upon import of the impact area set.  This seems reasonably straightforward to fix, except that it appears that the Polygon method on the PolygonFeatureLayer only accepts an integer. So it appears that we need to either figure out a way to pass in a string to get the required polygon, or only allow the user to have an integer identifier. 

There is one more related issue on impact area names. I think that this hard-coded attribute name will prove problematic:

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/0d9b48c253e09087618a0a172c9eb8b96fe57b7f/fda-model/structures/Inventory.cs#L205

We could track the name of the unique identifier in the view model and pass on to the model. That seems straightforward.

**Comment by Brennan1994** [comment]
I'm not entirely sure how to test this, but I suspect it's now been fixed. I think we should test this and the linked issue, and if the issue remains, look at it together so I can better understand it.

**Comment by rnugent3** [comment]
I will work on tests tomorrow.

**Comment by Brennan1994** [comment]
unassigning myself as I believe this to be fixed. Leaving it open in case you're using it to remind you to test it.

**Comment by rnugent3** [comment]
that's my plan thank you

**Comment by rnugent3** [comment]
@Brennan1994 if you get a chance today, would you mind taking a look at this? I'll do the same this afternoon.

**Comment by rnugent3** [comment]
this appears to be fixed

![image](https://user-images.githubusercontent.com/25163165/212199990-f7e60156-bec2-4aac-b66e-fb8e53997fa3.png)
