### ISSUE TITLE
StageDamageConfiguration Could use more work

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#579]
There is probably more validation that is needed in this class.

**Comment by codymccoy** [comment]
I am working on cleaning up the code in this class and testing the validation logic which I will outline below.

**Comment by codymccoy** [comment]
Is the user doesn't have any occtypes, the create stage damages editor can't even be opened.
![image](https://user-images.githubusercontent.com/47757848/195901202-d73d278d-ea18-48be-8cf3-c9c8b68688aa.png)

//todo: Test what happens when deleting items after they have been selected in the editor?

The first validation upon clicking the compute button is to check to see if all the required comboboxes have selections in them. If not, an error message is displayed:
![image](https://user-images.githubusercontent.com/47757848/195901466-0aef679a-138a-4dd2-8e32-2654f94bac3c.png)

**Comment by codymccoy** [comment]
The structure inventory is pointing at occtypes. It is possible that the user deleted the occtypes that the structures are pointing at. For example: import occtypes_1, create structures that point to occtypes_1, delete occtypes_1, import occtypes_2, open the stage damage editor.

![image](https://user-images.githubusercontent.com/47757848/195902183-f09aeafc-9d12-48a3-91cb-ed802979abe5.png)

**Comment by codymccoy** [comment]
Certain files need to exist. 
During the compute the impact area shapefile will be accessed. We need to make sure that it still exists where we think it exists.
My impact areas are called "my imp2". I changed the folder in the study directory to "my imp2_test" and then tried to compute:
![image](https://user-images.githubusercontent.com/47757848/195904319-c2bc7c5f-1d2e-42f8-972c-2bcad485640c.png)

**Comment by codymccoy** [comment]
I added "_test" to one of my gridded hydro directories and then tried to compute:
![image](https://user-images.githubusercontent.com/47757848/195942762-0cbfaef0-0434-4d71-9018-62f6caa2223b.png)
![image](https://user-images.githubusercontent.com/47757848/195942781-4a7abd51-0220-4df4-a953-b7e9279251f9.png)

**Comment by codymccoy** [comment]
I don't feel like I can validate all possible things that can go wrong in this compute so I put a try-catch around the compute call to capture any errors and display them to the user:
![image](https://user-images.githubusercontent.com/47757848/196220106-5b54b19d-15fa-48fd-b864-204acdb4e0ad.png)
The error above occurred when i used a steady hydraulic.

**Comment by codymccoy** [comment]
I updated the stage damage editor to support "live updating". There are three actions that can modify a child element: Add, Remove, Update. If any of these occur for the hydro, structures, frequency function, stage discharge the UI will update itself.
![image](https://user-images.githubusercontent.com/47757848/197879016-60d69101-56ec-4594-869a-b0254562c754.png)

**Comment by codymccoy** [comment]
Most of the items in this issue is in main. The work i did in the last comment is in the branch file_locking_issue.
@rnugent3 This is ready for you to test.

**Comment by rnugent3** [comment]
Great thank you

**Comment by rnugent3** [comment]
> Is the user doesn't have any occtypes, the create stage damages editor can't even be opened. ![image](https://user-images.githubusercontent.com/47757848/195901202-d73d278d-ea18-48be-8cf3-c9c8b68688aa.png)
> 
> //todo: Test what happens when deleting items after they have been selected in the editor?
> 
> The first validation upon clicking the compute button is to check to see if all the required comboboxes have selections in them. If not, an error message is displayed: ![image](https://user-images.githubusercontent.com/47757848/195901466-0aef679a-138a-4dd2-8e32-2654f94bac3c.png)

I am not getting that validation message. I just see "No curves have been computed. Compute curves to save."
![image](https://user-images.githubusercontent.com/25163165/200048719-b1f2c395-5437-41f9-9f59-af6a9a5d738d.png)

**Comment by rnugent3** [comment]
Behaves as expected.

**Comment by codymccoy** [comment]
ok, i'll take a look.

**Comment by rnugent3** [comment]
please disregard! I hit the wrong button.

**Comment by codymccoy** [comment]
Sounds good.
