### ISSUE TITLE
display all values to three decimal places 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#583]
is there an easy way to display all values in the view to three decimal places?

**Comment by rnugent3** [comment]
for example: 

![image](https://user-images.githubusercontent.com/25163165/195410741-93afc5b5-247c-48d8-8729-000e36c28fe2.png)

**Comment by codymccoy** [comment]
I can make the table with plot have 3 decimal places. I don't think there is any way to globally say that any number in the view should be 3 decimal places. We would have to do it control by control. We could probably define a "style" for textbox and others in the app.xaml to be 3 decimal places. I will look into it.

**Comment by codymccoy** [comment]
I found out how to make the table with plot go to three decimal places:
![image](https://user-images.githubusercontent.com/47757848/195672689-b261df23-3a87-4da0-bc60-881fe79a961a.png)

![image](https://user-images.githubusercontent.com/47757848/195672730-b4d97fe2-3302-4e12-922d-bf96775a47fc.png)

**Comment by codymccoy** [comment]
We have defined a couple of string constants that get referenced by some of the UI controls.
![image](https://user-images.githubusercontent.com/47757848/195716441-55b3ac1c-fa12-4246-9b40-ea932a52c2a1.png)

This was so that if we want to change our precision, we can change it in one place.

**Comment by codymccoy** [comment]
@rnugent3 Do you want me to change the default format to be 3 decimal places (N3 instead of N2)?

**Comment by codymccoy** [comment]
Looks like we are using the "detailed" N4 for some of the AEP results where we wanted 4 decimal places.
![image](https://user-images.githubusercontent.com/47757848/195716737-e09cb7b7-0716-4257-b22c-7625d8632a8f.png)

**Comment by codymccoy** [comment]
I couldn't come up with a fancy way to globally set precision on controls. I thought that maybe i could do something with the styles defined in the App.xaml but I don't think that works for the data formatting. It is easy to do on a control by control basis. You assign the string format when doing the binding like this:
![image](https://user-images.githubusercontent.com/47757848/195717620-47f99123-5041-4459-a54e-59e3677e9a0f.png)

**Comment by codymccoy** [comment]
I can't guarantee that I have all the controls formatting their data. We just need to keep an eye out for ones that aren't formatted and we can change them.

**Comment by rnugent3** [comment]
I think two decimal places is sufficient, except in the places where we are using 4 (should be AEP, LTEP, and Assurance)

**Comment by codymccoy** [comment]
Most values in fda are now defaulted to 2 decimal places except for the results that we want to be 4 decimal places. @rnugent3 This is ready to be tested. This is now in main.

**Comment by rnugent3** [comment]
Sounds good thank you
