### ISSUE TITLE
table with plot validation is not working 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#584]
Take a look at the plot and the data - the input data is not at least weakly monotonically increasing, but there is no indication to the user. 

![image](https://user-images.githubusercontent.com/25163165/195418180-350bc456-f48b-405a-865e-0308adf6ac33.png)

**Comment by Brennan1994** [comment]
I can't reproduce this. Please test with latest build

**Comment by rnugent3** [comment]
I thought about this. I think this happened when the data was loaded bad by default, not when the user entered.
