### ISSUE TITLE
Hydraulic Import Rounds too aggressively

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/HEC-FDA#601]
![image](https://user-images.githubusercontent.com/64556723/198745475-a4c1363f-e0d1-4b64-b850-ec3ab96cb9e5.png)

The last two rows here should be 0.005 and 0.002, but the UI is rounding up.

**Comment by rnugent3** [comment]
This is happening in the graphical user interface control, too. The column of annual exceedance probabilities above and in the graphical table could be set to the same setting as the probability stuff in project performance results (from the scenario compute). I think that setting is to the 4th decimal place.
