### ISSUE TITLE
Cannot clear fields when mapping SI attributes

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/HEC-FDA#610]
Once you've selected something in the combo boxes, theres no way to clear it. I accidentaly selected something for beginning damage depth, but don't actually have a column for that, so I want to clear it and cant. 
![image](https://user-images.githubusercontent.com/64556723/199597329-389215ca-09a4-45e9-9b6f-f8330b190866.png)

**Comment by codymccoy** [comment]
All combos now have an empty first item that can be selected. 
![image](https://user-images.githubusercontent.com/47757848/200378820-b0b2a45a-0484-4534-b0a3-3dd2d9d61cd1.png)

This was completed on branch stage_damage_exception branch.

**Comment by Brennan1994** [comment]
I'd rather do the confirmation test once we've merged into main. As it sits, the issue still remains on main, so I'm going to assign to Cody. We should discuss our workflow a little at our next biweekly. I don't want to review in progress branches, rather review pull requests.

**Comment by codymccoy** [comment]
@Brennan1994 I think this is ready for you to test.
