### ISSUE TITLE
stage-damage functions are coming back incorrect 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#615]
We need to investigate why the stage-damage functions are coming back like this. I am using good data and am getting the same thing. Once we get good stage-damage functions, then we can test this.

_Originally posted by @rnugent3 in https://github.com/HydrologicEngineeringCenter/HEC-FDA/issues/563#issuecomment-1304013858_

**Comment by rnugent3** [comment]
![image](https://user-images.githubusercontent.com/25163165/200054871-3fb85ff2-67cc-4f43-915b-a40649c7f761.png)

**Comment by rnugent3** [comment]
This appears to have to do with the way that we're getting the WSEs. 

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/732500ad8f3f733bbde37b4090450e4a1b61ef8c/fda-model/stageDamage/ImpactAreaStageDamage.cs#L191

At the line above, we're getting the WSEs at the structures for the highest profile (.002 AEP). stagesAtStructuresHighestProfile is an array of zeros.

**Comment by rnugent3** [comment]
@Brennan1994 do you have any thoughts? I know that the method is tested and for WSE grids, it is weird that we're getting back all 0s even for the .002 AEP.

**Comment by rnugent3** [comment]
I have also confirmed that the WSE grids are good, with raster values between about 930 and 950.

**Comment by Brennan1994** [comment]
super weird. It's gotta be a projection thing. What data are you using with this?

**Comment by Brennan1994** [comment]
Unassigning myself.  I believe this to be a projection issue. (the part about WSEs coming back as -9999s.) Still remains to be seen whether that gets as reasonable results.

**Comment by rnugent3** [comment]
we're a step closer....but still so far
![image](https://user-images.githubusercontent.com/25163165/201427370-efcc7144-8542-4e2a-b6d2-e1b0a5b22ded.png)

**Comment by rnugent3** [comment]
Now increasing globally but still jumping around a lot 

![image](https://user-images.githubusercontent.com/25163165/201432823-d877468f-6c16-456c-8237-0faba15216fd.png)

**Comment by rnugent3** [comment]
I am going to call this complete. We are getting stage-damage functions back.
