### ISSUE TITLE
GetWSE returns -9999 when using Unsteady HDF

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#625]
In the screenshot below, the sampled stages at structures are all -9999. This is Muncie data. 

![image](https://user-images.githubusercontent.com/25163165/200446271-6e40dcab-dbc5-49c6-95dd-13db4b99534e.png)

**Comment by rnugent3** [comment]
The structure points appear to be obtained correctly, assuming we don't need the Z and M properties of a PointM:

![image](https://user-images.githubusercontent.com/25163165/200446968-57f460e5-4e6e-4d88-8f8f-9f66db710037.png)

**Comment by ajkennedy-HEC** [comment]
-9999 is our generic NoData value, suggesting that the points are dry or didn't intersect any geometry element. In this case, the structure locations appear to be in lat/lon, so they need to be reprojected to the local projection before you can query the geometry.

**Comment by Brennan1994** [comment]
Right now we're not handling reprojection. The point shapefile will need to be consistent with the projection of the hydraulic data. What's the projection of this point shapefile?

**Comment by Brennan1994** [comment]
Closing this issue because this is really a projection issue.
