### ISSUE TITLE
Stage Damage Compute Bug

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#626]
I got latest on main yesterday morning and now when i try to compute stage damages I get the following error:
![image](https://user-images.githubusercontent.com/47757848/200631123-3d21fd0f-3dcb-4755-b645-2993f08ab253.png)

I started debugging and tracked it into the model compute. 
![image](https://user-images.githubusercontent.com/47757848/200631219-c0e76121-d525-41b1-9004-e6e1f982b123.png)

My structures and wse and from lower cache creek. Looks like the stage discharge is from bear creek.
![image](https://user-images.githubusercontent.com/47757848/200631469-af9bf632-5a89-43bf-9078-4946cbaa5d51.png)

**Comment by rnugent3** [comment]
This looks like the error message is the result of validation that we're doing?

**Comment by codymccoy** [comment]
I put a try catch around that compute in the View model. That is what is catching the exception. So I wouldn't think this is normal validation logic or else the Model should be catching it.

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/200634255-488cada7-5afd-4466-9468-d8bd59a68013.png)

**Comment by rnugent3** [comment]
Ok. I will spend some time troubleshooting today.

**Comment by codymccoy** [comment]
I can't really proceed with #616 until this one is handled. Are you able to get a compute that runs? To diagnose #616 I would like to be able to compute and then save.

**Comment by rnugent3** [comment]
I've had some success using Muncie data.

**Comment by rnugent3** [comment]
The computed curves come back wrong, but curves are returned.

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/200689877-991575ff-2c81-4242-b5bd-72c6d18d61b9.png)
![image](https://user-images.githubusercontent.com/47757848/200689894-336426bb-5672-40da-8e3f-7045e13b5fb4.png)
