### ISSUE TITLE
come up with structure details logic 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#630]
We can use the CsvHelper. 

I will create a class that has one property for each attribute in the structure detail out file. Let's call that class StructureStageDamageDetails. I will then create the class that generates the report. Let's call that class StructureStageDamageReport. 

In the class StructureStageDamageReport, I will create a static method that accepts an inventory and a hydraulic data set and returns a List<StructureStageDamageDetails>. Then, in the view or view model, we can use WriteRecords which will proceed to write the property headers and values. 

I think we should write to a file in the study directory (same place as the sqlite file) that has the name "NAME_StructureStageDamageDetails.csv" where "NAME" is the name of the set of stage-damage functions.

**Comment by codymccoy** [comment]
It looks like I stubbed out some of this a while back. We have a menu item:
![image](https://user-images.githubusercontent.com/47757848/200903059-ad6fdba3-3d9a-4e91-ae98-a400b4f33ac1.png)

And I stubbed out some methods that you might want to take a look at in the AggregatedStageDamageElement class:
![image](https://user-images.githubusercontent.com/47757848/200903149-fbd6a6b4-8d81-4b75-9f0c-bca9897b82c1.png)

**Comment by codymccoy** [comment]
In the WriteStructureTable() method i was thinking that a data table might be a good object to use for this, but you certainly don't have to.
This option is currently writing a test file out to the location you want. 
![image](https://user-images.githubusercontent.com/47757848/200904021-aa3b4913-ae5a-490a-a1de-61ee00b11b28.png)

Here is a look at the file:
![image](https://user-images.githubusercontent.com/47757848/200904069-aae43e0b-b796-4376-b571-7da5b37a370b.png)

**Comment by rnugent3** [comment]
Cool. I am going to have a method on the ScenarioStageDamage object called ProduceStructureDetails() that will return a List<string> - each of which should be a row in the file.

**Comment by rnugent3** [comment]
The List<String> contains 1 row of data per string, where the first string contains the headers. Data is comma separated. 

![image](https://user-images.githubusercontent.com/25163165/200939979-55949925-f026-4011-84a3-7dc772f6a603.png)

**Comment by rnugent3** [comment]
> It looks like I stubbed out some of this a while back. We have a menu item: ![image](https://user-images.githubusercontent.com/47757848/200903059-ad6fdba3-3d9a-4e91-ae98-a400b4f33ac1.png)
> 
> And I stubbed out some methods that you might want to take a look at in the AggregatedStageDamageElement class: ![image](https://user-images.githubusercontent.com/47757848/200903149-fbd6a6b4-8d81-4b75-9f0c-bca9897b82c1.png)

 The name here, we'll want to be the name of the set of stage-damage functions.

**Comment by rnugent3** [comment]
> In the WriteStructureTable() method i was thinking that a data table might be a good object to use for this, but you certainly don't have to. This option is currently writing a test file out to the location you want. ![image](https://user-images.githubusercontent.com/47757848/200904021-aa3b4913-ae5a-490a-a1de-61ee00b11b28.png)
> 
> Here is a look at the file: ![image](https://user-images.githubusercontent.com/47757848/200904069-aae43e0b-b796-4376-b571-7da5b37a370b.png)

Among the first couple rows in the report, we'll want the name of the set of stage-damage functions and the description of the set of stage-damage functions

**Comment by codymccoy** [comment]
@rnugent3 Is this ready for me to work on?

**Comment by rnugent3** [comment]
yessir

**Comment by rnugent3** [comment]
I have some testing in which I confirmed that the list of strings returned looks like what I expect.

**Comment by codymccoy** [comment]
Great. I will take a look tomorrow.

**Comment by codymccoy** [comment]
New strategy: Create "StructureStageDamageDetails" folder and put the details files into it. Need to validate name. Need to write out when user clicks the compute button. Remove the menu item from the element.

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/202580668-cd87ce6d-315e-4943-9ef1-0b76fcb355ce.png)

@rnugent3 It wouldn't be hard to add a checkbox that determines if we write the details out or not. Not sure if that is something the user would want. "Write Details to CSV" or something like that.

**Comment by rnugent3** [comment]
I like that idea because it makes it clear to the user that this feature exists. Yes, please!

**Comment by codymccoy** [comment]
I think a tooltip is helpful. Let me know if you want it worded differently:
![image](https://user-images.githubusercontent.com/47757848/202734188-7e607315-fc23-4699-ae37-6d3a82ef46e8.png)

I will now allow the compute button to run without a name filled out if the checkbox is unchecked.

**Comment by codymccoy** [comment]
If the checkbox is checked a file will be written every time the compute curves button is clicked. If the name is the same, it will overwrite the existing file. If the user changes the name, a new file will be created. I see no way of removing the files other than the user going to the directory and removing them manually. If a user right clicks on the stage damage child tree node and does a rename it will not rename this details file. None of this is necessarily a problem, I am just pointing it out.

If we wanted to only allow one file per stage damage element and make that link stronger, we would need to add a link to it in the database by storing the file name or something like that. But maybe for now we don't need to overcomplicate this.

**Comment by codymccoy** [comment]
@rnugent3 Do you want me to add the boolean checkbox value to the xml read and write? That way we save the state of the checkbox when they re-open the editor. Right now I have the checkbox defaulted to selected.

**Comment by codymccoy** [comment]
This work is mostly completed (depending on the answers to the questions above). Onve the details method stops throwing an exception we just have to delete the dummy "details" and use the real one.
![image](https://user-images.githubusercontent.com/47757848/202748771-ee1e3f89-335c-4a5f-9e07-47e6ba7821ba.png)

This work has been done on branch write_stage_damage_details

**Comment by rnugent3** [comment]
we will come back to this after @rnugent3 fixes the produce structure details bug

**Comment by rnugent3** [comment]
The remaining work on this issue will be merged after PR #688 is complete.

**Comment by rnugent3** [comment]
this is all done
