### ISSUE TITLE
Year in service and number of structures 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#632]
We need to handle year in service and the number of structures in the stage damage compute and in the inventory and structure and deterministic structure yada yada yada

**Comment by rnugent3** [comment]
Street, city, zip, too

**Comment by Brennan1994** [comment]
unassigning myself because I see you're on it. Let me know if you need any assistance over rocket

**Comment by rnugent3** [comment]
6hrs.

**Comment by rnugent3** [comment]
Feedback from Britt: 

-“Total Value” and all damage values in 1.4.3 are the product of the full record incorporating multiples if the number of structures is greater than 1. I was just going to write this up as a difference between the model versions, but one of the practical uses of the SDO is being able to identify records that carry high damages and that maybe need some extra attention. Without having the multiples incorporated into the damage numbers, we aren’t getting a full idea of what is going on with that record and potential issues might be missed. I personally don’t understand why anyone would be using multiples or where doing so would be a best practice, but I know it was used in the past and if we’re giving the option to have multiples then I think we need the SDO to reflect the full weight of that individual record. 

-“Reach” was also really helpful to have, so maybe an “Impact Area” column? It’s very useful to be able to know generally where the record is located when using the SDO.

-In 1.4.3, we have columns for “depth at beginning damage”, “stage at zero damage”, and “depth at zero damage”. It looks like 2.0 has “DepthBeginningDamage” that kind of ran into “StageOf0.5AEP”. The stage and depth at zero damage are kind of redundant, but it would be nice to have one or the other because it informs on what the depth damage function is. If we have a foundation height of 0.5, begin damage depth of -9, and stage at zero damage of -1.5, then we know the depth damage function for that record starts damage 2’ below the first floor elevation. There are times when it’s really useful to not have to cross reference the depth damage function for each occupancy type. This is especially true when we are dealing with nonstructural.

-If content or other is put in as a structure value ratio instead of a dollar value, will the SDO reflect the value or will it be blank? Previously, it returned “-901” for the “content value in database” which is essentially blank, but then reported the CSVR and the calculated content value. Same for the other category.

-Module is also a very important column that is missing. The building of nonstructural measures is done pretty much completely based off of the SDO and QC without the module column would be nearly impossible. Being able to see which module was pulled lets us know if the plan was set up correctly to damage the records we want damaged. It also lets us check occupancy assignments and verify beginning damages associated with those occupancy types.

Side note: I see there isn’t a toggle column for indicating if the model is using first floor elevation or ground & foundation. I’m not sure if this is a missing thing or if this indicates that the model requires all 3. I am a big fan of it requiring all 3 or just going down to ground & foundation. With the Corps moving to more incorporation of nonstructural, I don’t think we should be allowing the use of just first floor elevations. We really need to be able to get to foundation heights for a lot of reasons (I’m in a battle with a NFS right now over this and it’s an absolute nightmare)

Another side note: One of the bugs in 1.4.3 is that the headers in the SDO are set to the default return intervals regardless of what was put into the model. For 1.4.3, that ends up meaning that the headers are incorrect if the user isn’t using data associated with those same default 8 frequencies. I’m not sure if this model would end up having the same issue or if it would be calculating and spitting out the data at those default frequencies. So if I put in H&H data where the 3 most frequent events were the 1 year event, 10 year event, and 25 year event, would the model spit out an SDO with a calculation for what the stage would be at a 2 year and 5 year events and then the damages for those events? Or would it just throw the first given frequency’s data into the 2 year spot without any alteration of the header? If there is an error here and the headers can’t easily be adjusted to pull whatever frequency was given, then maybe moving to naming the frequencies by order would be best. So something like “StageAtFirst”, “StageAtSecond”, etc.

**Comment by rnugent3** [comment]
[SDO Header Questions and Comments.xlsx](https://github.com/HydrologicEngineeringCenter/HEC-FDA/files/12537581/SDO.Header.Questions.and.Comments.xlsx)
