### ISSUE TITLE
alternative messaging does not make it to the user 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#641]
The message at this location does not make it to the user. I think that is because it is probably sent by an object that is not registered to message hub. 

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/167b0e9b4fc22dbd949cad99799580f1681a5acd/fda-model/alternatives/Alternative.cs#L44

@codymccoy @HenryGeorgist @Brennan1994 what do you think?

**Comment by HenryGeorgist** [comment]
yeah that sounds  right. if you do not register then the hub will not send it to any subscriber.  add a line to register nullalternativeresults with the hub on the line after construction.

**Comment by rnugent3** [comment]
this issue requires testing - some work has been done recently
