### ISSUE TITLE
remove module from structure inventory importer

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#645]
please remove the module option here: 

![image](https://user-images.githubusercontent.com/25163165/201409375-2453e91c-2342-464c-a998-4e1acbfa32f5.png)

**Comment by codymccoy** [comment]
Looks like the module is also getting imported from old fda. Do you want me to remove that as well? Basically it is easy to remove the UI module row. Do you want me to do a deep scrub and remove the concept of module everywhere in the fda code?

**Comment by rnugent3** [comment]
Deep scrub, yes, please.

**Comment by codymccoy** [comment]
I'm on it.

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/202043959-f36c6580-5ff3-4c4a-b113-d34d4904f67a.png)

This is completed on branch stage_damage_saving
