### ISSUE TITLE
trim shapefile to polygon does not work 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#646]
The line of code below does not work expected. 

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/94c07a777f3c2615ca0f0c9702925780bf469bbd/fda-model/stageDamage/ImpactAreaStageDamage.cs#L59

the inventory passed into the constructor has 1600+ structures, after getting trimmed, _inventory has 0 structures.

**Comment by Brennan1994** [comment]
What shapefile and impact area are you using for this? I'm suspicious of a projection issue again.
