### ISSUE TITLE
Also Missing the file from the Unit test for dbfreader ` string filepath = @"..\\..\\Resources\\ProbData.dbf";`

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#655]
Also Missing the file from the Unit test for dbfreader ` string filepath = @"..\\..\\Resources\\ProbData.dbf";`

_Originally posted by @Brennan1994 in https://github.com/HydrologicEngineeringCenter/HEC-FDA/issues/653#issuecomment-1315885718_

**Comment by Brennan1994** [comment]
fixed
