### ISSUE TITLE
scenarioStageDamage.ProduceStructureDetails() throwing index out of bounds exception

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#662]
The issue is occurring in the DepthsToStrings method in the ImpactAreaStageDamage class:
In my study i have different numbers for these lists. I think we need more validation somewhere in this process.

![image](https://user-images.githubusercontent.com/47757848/202569462-f27c1c9f-a8e7-4944-8896-615cb25c661c.png)
![image](https://user-images.githubusercontent.com/47757848/202569476-b0798a03-7d3a-4fc8-a04a-accb90b71b18.png)
![image](https://user-images.githubusercontent.com/47757848/202569512-906601de-8826-42d6-810c-2e9659459722.png)

**Comment by codymccoy** [comment]
I am using default freq function and stage discharge function. Muncie steady hydro and muncie structures.
![image](https://user-images.githubusercontent.com/47757848/202569856-503fb1db-db8b-47b3-a147-218b1c3d4151.png)

**Comment by rnugent3** [comment]
That's weird. We are getting more WSEs than we're asking for. @Brennan1994 would you mind taking a look?

**Comment by rnugent3** [comment]
I don't think this has to do with any of the weird stuff we do in impact area stage damage - like interpolating and extrapolating. That only happens for the full compute.

**Comment by rnugent3** [comment]
The list of strings should be one larger than the inventory because the first row is the header.

**Comment by rnugent3** [comment]
My first comment is not true, I think we have 696 structures so we lost two.

**Comment by rnugent3** [comment]
So @Brennan1994 you could disregard, I'll do my best to take a look tonight.

**Comment by codymccoy** [comment]
maybe they are outside the hydro boundary?

**Comment by rnugent3** [comment]
The unit test StructureDetailsShould in StageDamageShould test class is passing. Need to check this once more using the UI.

**Comment by rnugent3** [comment]
[Uploading computeStructureStageDamageDetails.csv…]()
we are no longer hitting the index out of bounds exception
