### ISSUE TITLE
Stage Damage Table Values Incorrect In Edit Mode

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#665]
Computed stage damage curves:
![image](https://user-images.githubusercontent.com/47757848/202778696-856e6fd9-d19c-40c9-b497-ef819892f62b.png)

Save, close then open for edit:
![image](https://user-images.githubusercontent.com/47757848/202778734-34fafc93-85ea-43de-bc7a-775c5568d151.png)

Cody is tackling this one.

**Comment by codymccoy** [comment]
Maybe I am just using weird data? My mean value is always zero so I am not sure why i am getting .0005 and .0095. I don't really understand how this data is generated. HistogramRow takes an x and a y that is a histogram and then the .05 and .95 are generated using inverse cdf. We should probably write some unit tests to make sure the to xml and read from xml are generating the same values. I am giving up on this for now.

**Comment by codymccoy** [comment]
@Brennan1994 @rnugent3 I am curious if you guys are able to compute curves, close the editor and open it back up and see the same values in the table.

**Comment by rnugent3** [comment]
Weird. Seems like that problem might live in the histogram classes. I'll take a look on Monday.

**Comment by Brennan1994** [comment]
I feel like this has something to do with what I did yesterday in this class. add row may need to be smarter.
