### ISSUE TITLE
refactor search for complex objects

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#672]
We have many complex objects that hold compute results specific to combinations of: impact area, damage category, and asset category. While computing, we look for the correct complex object to which we add a given damage realization. If we can't find it, a dummy object is returned, we identify that the object is a dummy, and then create a new complex object for that given damage realization. Here is an example method that carries out this routine:

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/48ccd6fc22e2ab9008a6bedb7a8c31db23358368/fda-model/metrics/ConsequenceDistributionResults.cs#L287

This hacky approach is basically because I use a method to find the complex object with a return type of the complex object. So I need to start there - how to tell the computer that I couldn't find what I asked for. @Brennan1994 has done some try get stuff - that might be the way to go. @Brennan1994 what do you think?

**Comment by rnugent3** [comment]
I should take a look at the way that I aggregate histograms, too. I think that code is similarly hacky.

**Comment by rnugent3** [comment]
@codymccoy suggests that we use System.Linq. If trying to filter a list by several properties.

**Comment by rnugent3** [comment]
let's do this after certification so that troubleshooting is more direct? another option would be to sort. and we could play with linq lists.

**Comment by codymccoy** [comment]
https://stackoverflow.com/questions/13230468/linq-select-object-from-list-depending-on-objects-attribute
Linq allows you to do things like this. 

List<Answer> correctedAnswers =  Answers.Where(a => a.Correct).ToList();

"Answers" is a list in this case and this linq statement collects all the Answers that have a boolean property of "Correct" that is true and then returns that as a list "ToList()".
