### ISSUE TITLE
Inventory sample bug

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#675]
There is a bug somewhere within this method:

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/55ec51786fa53cb1d3bfa65602e37d9c27333682/fda-model/structures/Inventory.cs#L302

Reproduce this bug using the Muncie data with steady hydraulics. When attempting to compute stage-damage using the latest structure inventory with hundreds of structures, the sampled inventory (deterministic inventory) gets returned missing a structure. When attempting to do the same but using a much smaller structure inventory, this problem does not present itself. Please investigate why we're losing a structure. 

[NSI-Clipped.zip](https://github.com/HydrologicEngineeringCenter/HEC-FDA/files/10135954/NSI-Clipped.zip)
oes not present itself.

**Comment by codymccoy** [comment]
I have a MuncieNSI that has 696 structures.
![image](https://user-images.githubusercontent.com/47757848/205351661-c72060a0-f5a2-45f8-aa7a-67a0f2600903.png)

**Comment by codymccoy** [comment]
The clipped one that you attached has 7 structures:
![image](https://user-images.githubusercontent.com/47757848/205351748-4a3c74c2-c589-474a-af0b-93e3d03750c6.png)

**Comment by codymccoy** [comment]
My current test with the clipped structures is not producing any results and no error message. I am investigating.

**Comment by rnugent3** [comment]
I think there are bug fixes on my most recent branch that are important for getting reasonable results

**Comment by codymccoy** [comment]
I tried on your branch structureDetails and I am still getting no results.
This is my setup:
![image](https://user-images.githubusercontent.com/47757848/205357421-70b34513-ae2a-4aad-a47c-c422b11961ad.png)

**Comment by codymccoy** [comment]
@rnugent3 Can you send the study over that you were using? Are the structures using terrain?

**Comment by codymccoy** [comment]
The impact areas are zero. That seems to be the problem. More investigation.
![image](https://user-images.githubusercontent.com/47757848/205358891-5e5794cd-c358-4bbe-8b55-bbb430d3d4db.png)

**Comment by rnugent3** [comment]
I sent the study over through DoD SAFE. This screen shot contains the configuration I have been using. 

![image](https://user-images.githubusercontent.com/25163165/205361312-ddd9ce4d-4186-464b-bfc4-43a6eb9034bc.png)

**Comment by codymccoy** [comment]
Thanks

**Comment by codymccoy** [comment]
The issue appears to be occurring here:
For the structures file that contains 7 structures, the "Structures" count is 7 and then it checks to see if the impact areas contain that point and if id does, the point gets added to the "filteredStructuresList". In this case two structures are outside the impact area. All structures are within the terrain.

The seven structures:
![image](https://user-images.githubusercontent.com/47757848/205401382-261d05f0-9c91-46fb-b9ab-1363eb04f6cc.png)

The impact area doesn't cover all the structures:
![image](https://user-images.githubusercontent.com/47757848/205401412-fe7b4bc9-8e82-4730-a3bd-91635cfd0925.png)

**Comment by rnugent3** [comment]
I see. This tells me that we need to do the filtering by impact area earlier? We should be grabbing the WSEs for only those structures filtered. It seems like we're getting WSEs for all structures, but then we relate to the list of unfiltered structures.

**Comment by codymccoy** [comment]
@rnugent3 I will look into this a little more. Has there been any additional work on this that I should be aware of?

**Comment by codymccoy** [comment]
I am not sure how this code should be changed. It is mostly Model code. It seems to me that the entry point to this logic is the StageDamageConfiguration.CreateStageDamages(). Here are a couple of notes I took:
![image](https://user-images.githubusercontent.com/47757848/205755255-37466c38-d3b1-486a-98e9-5960b4cb1c57.png)

I will stop looking at this issue until further directions.

**Comment by rnugent3** [comment]
Understood thank you

**Comment by rnugent3** [comment]
I wonder if we were not successfully filtering by impact area before but we are now?

![image](https://user-images.githubusercontent.com/25163165/207391495-10575500-6b2e-4fc1-a3d0-99ea47e6d9c7.png)

**Comment by rnugent3** [comment]
this appears to have been resolved - we no longer encounter the bug
