### ISSUE TITLE
add to filter inventory unit test

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#678]
Could we add a unit test similar to the one at the below location where we draw on the data in the resources folder? I think it would be good to test in a more production-like environment, too.

**Comment by Brennan1994** [comment]
I think this bug report is incomplete. I'm not seeing the location below, and not sure I understand the ticket.

**Comment by rnugent3** [comment]
Yup. I forgot the link. 

I am interested in the following test in inventory should:

     [Fact]
        public void filterInventoryToIAPolygon()
        {
            Inventory inv = GetTestInventory(false);
            Inventory trimmedInv1 = inv.GetInventoryTrimmmedToPolygon(0);
            Inventory trimmedInv2 = inv.GetInventoryTrimmmedToPolygon(1);
            Inventory trimmedInv3 = inv.GetInventoryTrimmmedToPolygon(2);
            int countActual = inv.Structures.Count;
            int count1 = trimmedInv1.Structures.Count;
            int count2 = trimmedInv2.Structures.Count;
            int count3 = trimmedInv3.Structures.Count;
            Assert.Equal(countActual, count1 + count2 + count3);
        }
 
I think it would be great to draw on the Muncie data with this test. What do you think @Brennan1994 ?

**Comment by Brennan1994** [comment]
Considering this issue stale. In general, the simplest test is the best, and we do have some tests where we need to draw on data in the resources folder now. I think we've moved forward.
