### ISSUE TITLE
Occtype value uncertainty validation not working correctly

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#682]
I noticed that the content damage tab, value ration radio selected, has validation rules for some of the distributions. 
![image](https://user-images.githubusercontent.com/47757848/206040543-853d91ee-98d9-4153-bd89-5f7974a11368.png)

The structure damage tab and others don't have this validation working.
![image](https://user-images.githubusercontent.com/47757848/206040673-bee38393-434d-4f9e-afc9-b3a5865f4fe3.png)

I assume that in the image above, min being greater than max should have the same validation as in the first pic.

**Comment by rnugent3** [comment]
@codymccoy please make sure that occupancy type validation follows the discussion in #729.
