### ISSUE TITLE
Are we handling occtypes in error state during compute?

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#683]
We made a decision a while back that we would allow occtypes to save with certain errors. In the pic below you can see these errors. We allow non monotonic curves and we allow rule violations in the uncertainty values. Are we handling these correctly during the compute? Probably we need to message the user and not even try the compute?
![image](https://user-images.githubusercontent.com/47757848/206042864-8803af9b-32b3-497c-a22b-7aeae450dfe7.png)

**Comment by rnugent3** [comment]
validation has been added to handle errors among the occ types during the compute.
