### ISSUE TITLE
Should we log validation issues in the occtype editor?

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#684]
I ran across this comment today. It sounds like I left the validation methods that used to get called when the user tried to save in case we wanted to use those to write the messages out to a log file. This validation cascades down into several subcomponents so there are currently many methods that exist that are not getting called. Seems like we should either write them out to the log file or delete those unused methods.

![image](https://user-images.githubusercontent.com/47757848/206044259-1c684ce4-8ee9-405f-953c-853b693f45fc.png)

**Comment by rnugent3** [comment]
I have written a bunch of occupancy type validation in the model that you can write to file, and delete the unused methods. I think you'll need to call validate on the occupancy type and then get the errors.

**Comment by codymccoy** [comment]
How we get the errors and log them might change depending on the answer to issue #710
