### ISSUE TITLE
Saving histograms is taking a very long time

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#687]
I'm guessing there must have been some new code added because this didn't used to take so long.
I think the issue is the size of the bin counts. In the muncie study there are 420,000 bins that are being written out.
![image](https://user-images.githubusercontent.com/47757848/206274045-70564b43-e1b9-4e85-ac97-2cd78736987f.png)

At my current rate, this is going to take like 20 minutes to save.

**Comment by codymccoy** [comment]
I wonder if part of the slow down is that these are being added as attributes and not as their own xelement? I will test that and see if it saves faster.

**Comment by rnugent3** [comment]
Thanks for looking into this, @codymccoy. Any changes you make to Histogram.cs - would you mind also changing to ThreadsafeInlineHistogram.cs?

**Comment by codymccoy** [comment]
I think this version is the best. I see no reason to write out the iteration value "i". It seems to be fast to write AND pretty fast to open the xml in sqlite reader. I convert the list of bincounts into a single comma separated value string. 
![image](https://user-images.githubusercontent.com/47757848/206307154-8a5888cd-0b01-4be6-b7f1-7182b92f5431.png)

the updated reading logic:
![image](https://user-images.githubusercontent.com/47757848/206307337-f21ddae5-e27f-4a28-aaf8-67afa1f7129e.png)

I will remove the dead code and add this logic to the threadsafe histogram.

**Comment by codymccoy** [comment]
This is fixed in branch save_checkbox_state.
