### ISSUE TITLE
Stage Damage Compute with full NSI structures for Muncie takes a long time (minutes)

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#689]
Not sure if we can optimize or at least notify the user that we are still computing? Right now it just looks like the program is frozen. Progress bar? Parallel compute?
 
Below I will outline the major components of the compute:

3 different computes for lower, middle, upper:
![image](https://user-images.githubusercontent.com/47757848/206323711-b6185ed8-e46a-455d-8175-675a825094ed.png)

Loop over number of profiles. In my case this is 8:
![image](https://user-images.githubusercontent.com/47757848/206323794-943fb53f-fb49-4a53-8a9a-937689b17175.png)

loop over iterations count inside a convergence while loop:
![image](https://user-images.githubusercontent.com/47757848/206324026-0ea0271a-182a-4c8b-a13e-0d9322d839e4.png)

I don't see any one line that takes a long time but all these items are multipliers so in total we are doing thousands of calculations and it takes a while.

**Comment by codymccoy** [comment]
If we want a progress bar, below the compute button might be a good location.
![image](https://user-images.githubusercontent.com/47757848/206324602-4c5af940-68e0-4bbe-b882-5bd2d8769fee.png)

**Comment by rnugent3** [comment]
@codymccoy A progress bar is a great idea. Let's do this after we work on validation and messaging.

**Comment by rnugent3** [comment]
this now takes just a couple minutes.
