### ISSUE TITLE
Remove "Impact Area" from alternative editor

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#690]
![image](https://user-images.githubusercontent.com/25163165/206368253-1bc387c9-8684-4f91-a830-b212039c4751.png)

**Comment by rnugent3** [comment]
We have just Scenarios now, we no longer have Impact Area Scenarios.

**Comment by codymccoy** [comment]
This is fixed on branch update_index

**Comment by rnugent3** [comment]
confirmed
