### ISSUE TITLE
updated structure inventory makes unit tests fail

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#695]
When we updated the structure inventory which included fixes to the CRS among other things, we broke the structure inventory unit tests. I think we need to verify the "expected values" and fix as needed. 

An alternative would be to upload the old shapefile in so that the tests pass. That seems like an inefficient solution to me but I am open to hearing otherwise.

**Comment by rtle76** [comment]
What other changes were made from the old to the new? @rnugent3

**Comment by rnugent3** [comment]
I think you made all of the changes to the shapefile - I don't recall doing that myself.

**Comment by rtle76** [comment]
I'll take a look at those unit tests today and see if I can fix it

**Comment by rtle76** [comment]
I'm seeing all test in InventoryShould are failing. Is it happening anywhere else?

**Comment by rtle76** [comment]
5/6 tests in InventoryShould are now passing. 

The remaining failure is the filterInventoryToIAPolygon test. Not quite sure what's going on there @rnugent3

**Comment by rnugent3** [comment]
Great! Last time I think it was CRS issue. Are you able to draw on the data in the resources folder and use GIS software to validate what we have documented as the expected value?

**Comment by rtle76** [comment]
Should be good to go now. Pull request is ready for your review
