### ISSUE TITLE
please review muncie occupancy types

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#698]
I found an issue with the muncie occupancy types. I am not sure where the occupancy types came form. We should review them for validity and fix any issues. 

The issue I found is in the screen shot below. The max error in percent is 28.57. The min error in percent is 35.71. This is nonsensical. For reference, see: https://discourse.hecdev.net/t/how-does-the-triangular-distribution-work-for-occupancy-type-uncertainty-parameters/1951

We'll need to make sure that the occupancy type data makes sense because we use that data for all of our examples. When validated, we'll need to update everywhere that we have this data stored - shared drive, in particular.

**Comment by rnugent3** [comment]
![image](https://user-images.githubusercontent.com/25163165/206875845-ef0435f9-f0c8-436d-bf24-64be4fa2b302.png)

**Comment by rnugent3** [comment]
![image](https://user-images.githubusercontent.com/25163165/206876631-c9edfa18-0823-4e57-965c-282b7920ac4a.png)

**Comment by rnugent3** [comment]
Some occupancy types do not have CSVR uncertainty. 

The "fixed" occupancy types do not need to be based on actual study data - they just need to make sense. 

Though, we should be careful. Sometimes people take the example study data and use it for a real study, so the occupancy types should be reasonable.

**Comment by HenryGeorgist** [comment]
just like with the simulation, there needs to be a validation step on the computation of the aggregated stage damage functions at the time of execution. this validation needs to include validation of occupancy types.

**Comment by rnugent3** [comment]
Yessir! I have a ton of validation and messaging work in queue.

**Comment by rnugent3** [comment]
4hrs

**Comment by rnugent3** [comment]
there are still bugs in how occ types are being imported and how model occ types are being created, I am using this issue to document

**Comment by rnugent3** [comment]
CSVR min/max should be imported as percent of ratio

**Comment by rnugent3** [comment]
[Uploading MuncieOccTypes.txt…]()
I have updated the occupancy types so that the triangular parameters make sense. FDA 1.4.3 expected min and max to be relative to 100, that was not documented anywhere.
