### ISSUE TITLE
import all stage damage functions

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#700]
previously, we were not handling asset type, so we just imported the total stage damage function. now that we have a way to handle asset type, we should import the structure, content, and other stage-damage functions instead of the total. @codymccoy do you have a guess on what that level of effort would be?

**Comment by codymccoy** [comment]
I think this would be pretty easy. This is what I have found so far:
1.) All the curves in the text file get read in.
2.) the curves get grouped by their plan name and year name:
![image](https://user-images.githubusercontent.com/47757848/208488595-a577651b-fa61-4b75-b461-c0559bba234a.png)

3.) That group of curves gets used to create a stage damage element. This is where we are only grabbing the "total" curve
![image](https://user-images.githubusercontent.com/47757848/208488756-4b3957af-977e-4c0e-9334-32147e400820.png)

**Comment by codymccoy** [comment]
While debugging, I see that we have all the asset types:
![image](https://user-images.githubusercontent.com/47757848/208488909-4455c805-cc16-484e-a85a-402ece460078.png)
This is the order that they come in:
![image](https://user-images.githubusercontent.com/47757848/208488966-9a6e047e-5f8b-478c-a7a6-aa53bbd502f4.png)

**Comment by codymccoy** [comment]
I added logic to add all the curves. In my case, there were 5 curves and each has 5 asset types (including total) which comes out to be 25 curves total for the element:
![image](https://user-images.githubusercontent.com/47757848/208505089-9d6ee6c2-07f3-439d-b565-04e6f7ba050e.png)

When we open it up for edit, it shows all 25 curves and has the different asset types selected.
![image](https://user-images.githubusercontent.com/47757848/208505189-b59bd6a6-3f40-4611-8836-46d951e65817.png)

**Comment by codymccoy** [comment]
This work was completed in the update_index branch.

**Comment by rnugent3** [comment]
@codymccoy could you please exclude the "total" stage-damage functions? that will mess up the way that we aggregate results - we need _either_ total _or_ structure, content, vehicle, and other.

**Comment by codymccoy** [comment]
No problem. That is an easy change.

**Comment by codymccoy** [comment]
removed the total which produces 20 curves:
![image](https://user-images.githubusercontent.com/47757848/208523892-029d6f71-63fc-4b40-abac-85a23155fde7.png)
![image](https://user-images.githubusercontent.com/47757848/208523906-42c22ac6-760b-4e29-95e4-98627c28bb45.png)
