### ISSUE TITLE
progressChunks does not play well with 1 iteration computes

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#702]
Something broke the following unit test:

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/5b46429d6cb3d1c735a4a6165c9649faf808bd82/fda-model-test/unittests/ImpactAreaScenarioResultsShould.cs#L25

The problem has to do with the min and max iterations, and the behavior of progressCHunks in the impact area scenario compute. progressChunks are being set to 0. We hit the **temporary, only for debugging** line on 343, which means that without line 343, we get to line 345 and attempt to divide by 0 when calculating the remainder: 

![image](https://user-images.githubusercontent.com/25163165/207125912-5d0d970b-346e-4c8b-90c3-0f2bbebfe121.png)

How could this happen? It seems that the convergence test must be behaving incorrectly? When we enter the parallel for loop, we loop for 1 iteration for this test. We then move to the convergence test on line 352,  and we should get "true," but it seems like we might get false so that progressChunks are set to 0.

**Comment by rnugent3** [comment]
We hit line 181 which means that the convergence test was broken. Max iterations are 1 so when we ask if the histogram is converged, we should see that we hit max iterations and converged on max should be true. 

![image](https://user-images.githubusercontent.com/25163165/207128212-a81ebb5e-3d9b-455e-9110-83e6f8852696.png)

**Comment by rnugent3** [comment]
the bug is line 740. If min iterations equals max iterations equals 1, and we have 1 iteration, then the conditional in line 740 is evaluated as false, and so we return false. 

![image](https://user-images.githubusercontent.com/25163165/207129017-fc935b3f-ca8f-45c4-9ebd-1ec8ea209466.png)

I think we need to first check if min iterations equals max iterations, then, if true, and if sample size is greater than equal to both, then return true. any thoughts?

**Comment by HenryGeorgist** [comment]
how about if _samplesize <= _miniterations...

**Comment by rnugent3** [comment]
I don't think that solves the problem. As written, the line is being evaluated as true and the method returns false. If we change the inequality to be weak, it still returns false. 

I think we need to swap the conditional on line 741 to be ahead of the conditional on line 740.

**Comment by rnugent3** [comment]
Or maybe the problem is something else. Sample size is 0:
![image](https://user-images.githubusercontent.com/25163165/207131248-ac887a68-0e97-4426-8e39-cb2e7c172352.png)

**Comment by HenryGeorgist** [comment]
i trust your judgment.
i see where weak inequality doesnt fix the problem (and actually may introduce other problems.
