### ISSUE TITLE
structure detail out work

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#705]
- We need to include a notes field _and_ a structure description. We need these fields in the user interface structure import and in the model. 
- We need these fields in the model because we need to print them when we write out the structure detail report.
- The structure detail report should print total damage, all damage values should be inflated, and add "inflated" to the damage value headers.

**Comment by codymccoy** [comment]
I will add a new field under the "Notes" row for "Description"
![image](https://user-images.githubusercontent.com/47757848/208465481-c6b5c11b-5d57-429b-a103-85a11be2b436.png)

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/208467213-182013af-c2c5-4629-8700-3448534097bd.png)

**Comment by codymccoy** [comment]
I am trying to track where this new value needs to get updated. When the user finishes importing the structure inventory we create an Inventory element that hangs on to the mappings that point to the shapefile. I created a mappings object in the view model and there is also a similar class in the model. This is the method that tries to do the conversion:
![image](https://user-images.githubusercontent.com/47757848/208485182-cf32f9f5-6c29-44ec-99bb-87bad350311b.png)

**Comment by codymccoy** [comment]
It looks like there are several missing values. I see that I have a note saying that we should probably try to just use the model class. I think that is probably still a good idea. Not sure what all that would take to accomplish.

**Comment by rnugent3** [comment]
I think it is a good idea to buy down that technical debt - if we're looking at 4hrs or less 

@Brennan1994 any thoughts?

**Comment by codymccoy** [comment]
I created this issue to track the refactor of the column mapping classes:
https://github.com/HydrologicEngineeringCenter/HEC-FDA/issues/718

**Comment by rnugent3** [comment]
The work remaining on this issue involves the SDO work noted above.
