### ISSUE TITLE
histogram read/write are causing failing tests

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#707]
it looks like changes to the way that histograms are being written/read back are causing the failing tests 

![image](https://user-images.githubusercontent.com/25163165/208552074-89f71b11-8f30-4ae9-9ae8-a1f19999ae58.png)

_Originally posted by @rnugent3 in https://github.com/HydrologicEngineeringCenter/HEC-FDA/issues/688#issuecomment-1358662695_

**Comment by codymccoy** [comment]
This is completed.
