### ISSUE TITLE
Scenario compute percentage incorrect

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#708]
We created a constant of -1001 to mean that the compute had reached 100%. I forgot to update the % value to be the correct number after getting the -1001 value:
![image](https://user-images.githubusercontent.com/47757848/208951697-c90f96d9-e19b-4c5f-9977-a97cb394ba53.png)

This is now fixed:
![image](https://user-images.githubusercontent.com/47757848/208951726-4907bfcf-f791-4bf0-b8f0-c3a90d1d84b6.png)

todo: I should check the other computes? Alternatives, alt comp reports?
This fix is in branch update_index

**Comment by rnugent3** [comment]
please check the other computes, thank you.

**Comment by codymccoy** [comment]
Alternative percent is correct:
![image](https://user-images.githubusercontent.com/47757848/209220064-67eeeed6-add5-4e41-8b5c-2d5f3bf950cc.png)

Alt comp report is correct:
![image](https://user-images.githubusercontent.com/47757848/209220162-dc3cb7cb-d788-4080-90bb-a6077d9ddde1.png)

**Comment by rnugent3** [comment]
terrific thank you
