### ISSUE TITLE
CurveMetaData Names

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#709]
Each UPD object has a CurveMetaData property - and each CurveMetaData object has a name property. I think we've been assigning a generic name like "Rating Curve." I think it would be _really_ helpful if instead we took the name of the object provided by the user and assigned that name to the curve meta data name. This way, when we are writing errors to file for a given object, we will write the name that the user provided for that object, helping the user to troubleshoot much quicker. 

@codymccoy what do you think this would take?

**Comment by codymccoy** [comment]
I think I have this working pretty well. Most editors that have a table with plot implement CurveEditorVM. 
I added a method in that base class to update the name of the curve object to be the user defined name. 
![image](https://user-images.githubusercontent.com/47757848/209022900-c38aef44-d097-42aa-9a5d-8c542c0ad9aa.png)

For each of the implementing classes, in the save method, this update method needs to be called:
![image](https://user-images.githubusercontent.com/47757848/209022998-4a061fa6-c0b8-4779-8cd9-f978151eaf55.png)

These are the classes that implement curve editor vm:
![image](https://user-images.githubusercontent.com/47757848/209023027-981ac9a8-8307-4e05-937e-e9a945bb30c4.png)

**Comment by codymccoy** [comment]
I wrote a unit test to verify that this approach is working:
![image](https://user-images.githubusercontent.com/47757848/209023082-f060d24c-a99c-4c61-9dc1-19682a4e510b.png)

**Comment by rnugent3** [comment]
AWESOME

**Comment by codymccoy** [comment]
The analytical frequency editor and the stage damage editor needed to be handled differently. 
For the stage damage editor I concatenated the name, impact area, dam cat, and asset category.
![image](https://user-images.githubusercontent.com/47757848/209178660-ffa72e4f-becf-4491-b200-0e60166732d9.png)

**Comment by codymccoy** [comment]
I think that covers all the curves that I could think of. If we want to update other curves, you just have to assign the CurveComponentVM.Name property.

This work was done on Update_Index branch.
