### ISSUE TITLE
Repeat log messages saying we couldn't find results

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#716]
![image](https://user-images.githubusercontent.com/47757848/209202548-d1bc6401-9a19-4f87-8ac5-1f40e1456451.png)

The problem is with this code:
![image](https://user-images.githubusercontent.com/47757848/209202602-09b08e48-366c-4be8-933b-358119138826.png)

When we go to "AddResults", we first check to see if results with that impact area id exists. If it doesn't then we add the results to the results list. When we run the compute, we don't have an results, we get the first result and want to add it, no results exist with that id so we add it. This will occur for each result.

**Comment by codymccoy** [comment]
GetResults() is called in many places, and maybe it makes sense to have that log message in that method. I think what we can do is just remove the AddResults() method and just add the results directly to the list in the two calling locations. @rnugent3 Does that sound good to you? I think the only question that needs to be answered, is do we expect those two references to ever be trying to add a results object that is null or already exists?

**Comment by rnugent3** [comment]
I'll investigate.

**Comment by codymccoy** [comment]
I am noticing double messages in the log file for other messages too. Not sure why this is happening.
