### ISSUE TITLE
Structure inventory column mapping and occtype refactor and bug fix

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#718]
I believe that there is a bug in this logic. 
![image](https://user-images.githubusercontent.com/47757848/209361399-e45e45c7-e9f4-4e65-b97a-eecdd60bb3ad.png)

The model inventory is trying to match the string name of the occtype in the structure shapefile, to the string name of an occtype in FDA. When I import structures we force that the user has already imported occtypes and the user must match the structure occtype names to the FDA occtype names. I store this mapping in a dictionary but after working through the logic with Brennan we realized that that info get ignored and never makes it into the model. 

After our discussion we feel that it is best to remove the VM mapping class and just use the Model mapping class. The dictionary needs to be held at the VM level because it references VM objects. When the compute is about to happen, the VM needs to pass in the correct mapping of occtypes to the model.

**Comment by codymccoy** [comment]
This refactor is complete. There is a PR for inventory_column_mapping.

**Comment by rnugent3** [comment]
@codymccoy could you please add a test to show that the behavior you modified works as expected?

**Comment by rnugent3** [comment]
For the next bug you tackle, consider writing a test first before fixing to show that the bug has been identified, and then with the test, that the bug is fixed.

**Comment by rnugent3** [comment]
Thank you!!!
