### ISSUE TITLE
Stage damage compute failing

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#720]
![image](https://user-images.githubusercontent.com/47757848/209686043-63ab5d6d-11ea-4459-ab8a-ad12f63b42a3.png)

This appears to be the problem line:
![image](https://user-images.githubusercontent.com/47757848/209686063-dc873f14-ee6d-4e6b-bbb0-69bad46851cc.png)

There are also several unit tests that are failing for the above reason.

I am not sure if this is caused by my recent changes to the structures or not.

**Comment by rnugent3** [comment]
is this related to #722?

**Comment by codymccoy** [comment]
Yes, this is the same issue. I vote we kill this one and keep #722
