### ISSUE TITLE
How to handle all structures outside polygon?

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#722]
When running the stage damage compute, there is a method that removes structures that are not in the impact area. If no structures are within the impact area, this will result in an error in the compute (index out of bounds). 
![image](https://user-images.githubusercontent.com/47757848/209836823-92a3f20a-68c9-4bd5-a60f-d67fbf22cd99.png)

Before we run the compute I could loop over all the impact area stage damage objects and look at how many structures they have. It seems to me that if there are no structures in any of them, we should message to the user and not run the compute. 

![image](https://user-images.githubusercontent.com/47757848/209837047-29de5ea3-be5c-40a2-8482-216203fbbe71.png)

How to handle one ImpactAreaStageDamage having no structures while others do have structures? Should I message the user and remove that ImpactAreaStageDamage from the list?

This is the error message and the line of code that is causing it:
![image](https://user-images.githubusercontent.com/47757848/209837230-de70a9f6-7a50-4aba-8f65-f5de2131d691.png)
![image](https://user-images.githubusercontent.com/47757848/209837241-9a71144e-ebe6-4e71-b63a-753319661870.png)

**Comment by codymccoy** [comment]
I think we should probably "ReportMessage" in the trim to polygon method if we are removing structures. This message would then show up in the log file. Something like: "3 structures where not inside the polygon and will not be used during the stage damage compute."

**Comment by rnugent3** [comment]
I agree. This is all validation that has to happen in the model. It's work that is queued for me.

**Comment by codymccoy** [comment]
I agree that validation is needed in the model, but I am thinking that I should probably evaluate something in the VM and stop the compute it there are no structures. I feel like a message box should be displayed to the user letting them know what is going on. I don't think we throw message boxes from the model.

**Comment by rnugent3** [comment]
I agree.

**Comment by rnugent3** [comment]
Rather we'll stop the compute in the model and pass the view model some info that there were no structures to the stage damage functions being returned reflect $0

**Comment by codymccoy** [comment]
I added the following validation check and message:
![image](https://user-images.githubusercontent.com/47757848/209995368-be5ee40e-4a7f-4a6b-881e-8fae5072534f.png)

Let me know if you want the wording changed:
"The compute will not run because this scenario has zero structures inside the impact area. This might be the result of the sturcutres and impact area having different projections."

![image](https://user-images.githubusercontent.com/47757848/209995434-005605d8-7a63-4064-96cc-86c4c0bd8def.png)

**Comment by rnugent3** [comment]
My only suggestion would be to use string interpolation so that you can include the impact area name inside the message

**Comment by codymccoy** [comment]
Looks like I also misspelled structures on the last line. Fixing it now.

This is the new message:
![image](https://user-images.githubusercontent.com/47757848/210004328-2e0a1df0-e96b-4c5c-9650-510560853f39.png)

**Comment by Brennan1994** [comment]
That message would be more useful if it said SF8 or SF9. The user would be interested in which of the polygons in the set has no structures. They could easily intuit themselves that the set their using is the offending set.

**Comment by rnugent3** [comment]
Looks like you might have used the name of the impact area set instead of the specific impact area name?

**Comment by codymccoy** [comment]
Yeah, the way i currently have it, that message will only show up if all structures are zero for all impact areas. I don't think i got an answer of what to do if one ImpactAreaStageDamage has zero structures while others have structures. Should I remove those from the compute if they have zero structures and then continue the compute?

case 1: all ImpactAreaStageDamage have zero structures. 
           Stop the compute and warn the user
case 2: Some ImpactAreaStageDamage have zero structures.
          Message the user that certain impact areas are being ignored because they have zero structures and continue the compute?

**Comment by codymccoy** [comment]
I implemented the above cases. Here are the messages to the user:
case 1:
![image](https://user-images.githubusercontent.com/47757848/210106062-35c3c331-0085-4e23-86b3-d044b54202ba.png)

case 2:
![image](https://user-images.githubusercontent.com/47757848/210106071-a327c15e-91f0-432a-b28f-2f952c5b7063.png)

**Comment by codymccoy** [comment]
this is completed in branch gridded_stage_damage_compute

**Comment by rnugent3** [comment]
This is great. Thanks @codymccoy

**Comment by rnugent3** [comment]
I think the only work remaining on this issue is to add messaging regarding structures removed.

**Comment by rnugent3** [comment]
I cannot test this issue until #727 is fixed

**Comment by Brennan1994** [comment]
@rnugent3 should this still be open?

**Comment by rnugent3** [comment]
I decided against adding messaging regarding structures removed, because we pull only those structures that are in a given impact area and ignore the rest.
