### ISSUE TITLE
Gridded stage damage compute not able to find files

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#723]
Running a gridded hydro compute is failing
![image](https://user-images.githubusercontent.com/47757848/209841043-28b37ffe-cac8-42b8-9fa8-1ba0cfeeee1e.png)

**Comment by codymccoy** [comment]
We probably changed the way that the gridded hydros save and didn't update this validation logic. I just found this comment and am not totally sure what it is saying. I would like to change it back to storing the vrt path. As a refresher, when the user clicks the save button to import the gridded hydros, we copy the directories into our study and we save the paths in the sqlite database. To be a valid gridded hydro, we require 8 directories that have N number of tifs and 1 vrt. Currently we are saving into the sqlite the first tif we find. I feel like we should be storing the vrt file path.
![image](https://user-images.githubusercontent.com/47757848/209854794-71a7e602-1a96-4483-abf5-cdb424e586dc.png)

**Comment by codymccoy** [comment]
I think this is now fixed. I can't really test it because i don't know of a set up that has overlapping structures, impact area and gridded hydros. @rnugent3 @Brennan1994 Do you guys have a study that we can use to test gridded stage damage computes?

This was fixed on branch gridded_stage_damage_compute.

**Comment by rnugent3** [comment]
Muncie should do the trick

**Comment by codymccoy** [comment]
Ok, I will test with Muncie.

**Comment by codymccoy** [comment]
The original problem that I posted was because i was using an old study. At some point we changed the path that gets saved for the hydraulics to be a file path instead of a directory path. At some point Brennan changed this path from the vrt path to the tif path. This was to fix an issue with RAS not always including a vrt file. In order to fix the above validation message about not finding files, the user must delete their hydraulics and re-import them.

**Comment by codymccoy** [comment]
The only files I could get to work were taken from the model-test resources. I used the impact area and nsi structures from that location and the stage damage compute was able to get past the trimming method with lots of structures. The compute was taking forever and eventually my computer froze and crashed. Not exactly a resounding success.

**Comment by Brennan1994** [comment]
The failing compute is unfortunately something we've uncovered today. We're eating the memory on your computer until we kill it. Stage damage is not working. 

I got the trimming to work with a different dataset though. that issue has to be related to projections not matching. Once things work again, the need for reprojection working is mounting.

**Comment by codymccoy** [comment]
Ok. Thanks for the update.

**Comment by Brennan1994** [comment]
I believe this issue has been resolved and gone stale. Closing.
