### ISSUE TITLE
add % symbol to occ type editor for deterministic value ratio 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#731]
![image](https://user-images.githubusercontent.com/25163165/211690767-1ecf83cf-d861-40c9-b629-6330d708f50c.png)

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/211928414-c28331da-51d5-4345-a6de-9bb5a61d7ec1.png)
![image](https://user-images.githubusercontent.com/47757848/211928433-bea7b18b-285e-4661-9d1e-8d5f093238bc.png)


This is completed in branch stage_damage_compute_bug

**Comment by rnugent3** [comment]
Perfect thank you
