### ISSUE TITLE
NPE when sampling inventory

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#732]
I am encountering an NPE when running a unit test for sampling an inventory.
This is where the exception is happening:
![image](https://user-images.githubusercontent.com/47757848/211839008-db55b8db-4cef-4fc9-89a6-24fe6b76188a.png)

The curve in question is the structure depth percent damage function of the occupancy type:
![image](https://user-images.githubusercontent.com/47757848/211839286-a346d64a-feac-4af7-92ee-e8a58d06b2d0.png)

I think all the occtype curves will be empty of x and y values because the unit test is using the default ctor:
![image](https://user-images.githubusercontent.com/47757848/211839582-405a6fb2-1ef1-4304-8488-c139cb2268bc.png)

I am not sure if this is really a problem that needs to be addressed or if this is something that only really comes up when running unit tests with the default occtype. Could we default the curves in that ctor to all have one coordinate of (0,0)?

**Comment by rnugent3** [comment]
I think a better approach would be to use occupancy type data. Copy and paste the occupancy type data and occupancy type constructed here:

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/4a40a123b9d12fe154a34fb6bb3d18389e2aed55/fda-model-test/integrationtests/TractableStageDamageTests.cs#L84

**Comment by codymccoy** [comment]
I ended up using this one from StageDamageShould:
![image](https://user-images.githubusercontent.com/47757848/211859148-3ed18c1a-c0be-4d4e-b5d0-25e4061d286e.png)

I am fine with just ignoring this issue, but it does seem like an issue to have a ctor that will create an object that will throw exceptions if you call any/some methods on it.

**Comment by rnugent3** [comment]
I understand. Would you mind dropping a public xml comment on the constructor that an occupancy type must be constructed using the builder pattern - the constructor cannot be used on its own?

**Comment by codymccoy** [comment]
I should have seen this earlier, but we can actually just make that ctor private. I think that is the appropriate way to handle an object that uses a builder. The only places that were publicly calling it were unit tests. I changed those unit tests to use the builder instead:
OccupancyType.builder().build();

Even if using the builder, you can still get exceptions if you call certain methods on an empty occtype, but we have bigger fish to fry and maybe that won't be an issue when using it for real.

![image](https://user-images.githubusercontent.com/47757848/211879082-a99fc25a-adc9-454f-aab2-43a56f2f43d2.png)

This is completed on branch stage_damage_compute_bug

**Comment by rnugent3** [comment]
Perfect thank you
