### ISSUE TITLE
not all stage damage functions are coming through 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#738]
Something is happening where the stage-damage functions being returned have a damage category of NA. I suspect that the functions are being aggregated over damage categories. We should see residential, commercial, industrial, and public here. 

![image](https://user-images.githubusercontent.com/25163165/212168786-e4d5aa40-0f84-428d-8c01-8ea2e09f60dd.png)

**Comment by rnugent3** [comment]
this is a model problem 

![image](https://user-images.githubusercontent.com/25163165/212179979-37d54fba-d2f9-4d80-b525-a6fd845784d9.png)

**Comment by rnugent3** [comment]
The damage categories are not being set on the structures

**Comment by rnugent3** [comment]
![image](https://user-images.githubusercontent.com/25163165/212180810-cbd2bcfd-35ac-46ee-8c29-875fc4e8eaa9.png)

**Comment by rnugent3** [comment]
I don't think it is a model issue, this actually appears to be a VM issue. @codymccoy please observe that the damage category for the structures injected into the constructor is NA:
![image](https://user-images.githubusercontent.com/25163165/212181190-8ec227a8-8286-4f74-84c5-29fd7a0e63fe.png)

**Comment by rnugent3** [comment]
Back to the culprit being in the model. The damage category is in the data row but is not being translated into the fda-model.structures.Structure dam cat. 


![image](https://user-images.githubusercontent.com/25163165/212182326-e320691a-7865-45be-a0ad-734ca74e7d34.png)

**Comment by rnugent3** [comment]
Once upon a time, we wanted to identify the damage category using the occupancy type. That is not what is happening now. We attempt to identify the damage category through the map, but we don't identify the mapping because we hadn't plan on using it.

**Comment by codymccoy** [comment]
The inventory importer doesn't have a field for damcat but it does like every structure to an occtype.
![image](https://user-images.githubusercontent.com/47757848/212399197-06fe7e41-c8e2-401c-b5e5-f02f3cabf3d5.png)
![image](https://user-images.githubusercontent.com/47757848/212399210-db156dd0-b37a-436a-b5c4-d0882923db2b.png)

Seems to me like we could pull the dam cat from the occtype. Would that work?

**Comment by rnugent3** [comment]
I already fixed this :)

**Comment by codymccoy** [comment]
Ok, cool

**Comment by codymccoy** [comment]
Did you get the dam cat from the occtype?

**Comment by codymccoy** [comment]
This is what I was thinking.
![image](https://user-images.githubusercontent.com/47757848/212400847-f5bd6e5f-0620-4c73-9754-b8ba11b22fa2.png)

![image](https://user-images.githubusercontent.com/47757848/212400861-59a17a88-9108-490e-bcac-086b0bd66544.png)

**Comment by rnugent3** [comment]
That's pretty much what I did!
