### ISSUE TITLE
Index points validation is broken

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#739]
The index points description is being validated for access to the OK button. See the screenshot - the name, shapefile, and unique name have all been defined but the OK button is greyed out. 
![image](https://user-images.githubusercontent.com/25163165/212169718-535a22cf-dc2c-48ce-9ea8-a602aadc6be0.png)
Once I define the description, I can hit OK. 
![image](https://user-images.githubusercontent.com/25163165/212169823-b246ff83-ab9c-4b87-ab00-00f3ac93681c.png)
A description is optional to save.

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/212206692-6801b9b9-56cb-462d-aaf0-7d6446fb3f6d.png)
 This is fixed in branch index_points_validation
