### ISSUE TITLE
Inventories without a FFE field will cause exception when testing whether a FFE field contains a "" or dbnull

### ISSUE THREAD

**Issue by AlexRyanUSACE** [HydrologicEngineeringCenter/HEC-FDA#744]
For structure inventories without a first floor elevation field (to be calculated from ground elevation and foundation height) the StructureSelectionMapping will not have field name for the FFE field. When the referenced line tries to determine if the value in the field with that name is either dbnull or "" it will throw an exception.

Recommend testing if the result of the previous line of code, which uses the GetRowValueForColumn function, is -999 and computing FFE as ground elevation + foundation height in that case.

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/65cacc504e1bf227ad4c331ebc3e8522a496497f/fda-model/structures/Inventory.cs#L187

**Comment by Brennan1994** [comment]
Confirmed this issue stale. Comment was addressed silently in the time since.
