### ISSUE TITLE
NPE when computing Aggregated stage damages

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#761]
![image](https://user-images.githubusercontent.com/47757848/217108966-b2ece984-c38a-42b1-b6ce-b32694b91f4c.png)

Ran into NPE when computing stage damage curve for "MuncieExampleStudy". I used the example study, opened "compute" for edit, switched structures to NSI and then clicked compute.

**Comment by rnugent3** [comment]
That's strange! I haven't seen that one yet. Does your occ type data look good?

**Comment by codymccoy** [comment]
The NSI structures are using these occtypes:
![image](https://user-images.githubusercontent.com/47757848/217114033-958238e9-75f6-442a-9004-fe450d47b207.png)

The clipped nsi structures are using these occtypes:
![image](https://user-images.githubusercontent.com/47757848/217114622-31ce5c23-12c6-443a-b471-69e9f612d14d.png)

**Comment by codymccoy** [comment]
The compute works just fine with the clipped structures, but hits that NPE every time with the NSI structures.

**Comment by rnugent3** [comment]
Huh. So it sounds like the inventory shape file is the problem? Best,R Nugent IIIOn Feb 6, 2023, at 4:05 PM, codymccoy ***@***.***> wrote:﻿
The compute works just fine with the clipped structures, but hits that NPE every time with the NSI structures.

**Comment by codymccoy** [comment]
Several null values in the sampledStructureParameters:
![image](https://user-images.githubusercontent.com/47757848/217289699-502dcfd3-f58d-426e-93b1-c50344c7dcb7.png)

**Comment by codymccoy** [comment]
The problem is that this method that creates those parameters is early exiting because of errors:
![image](https://user-images.githubusercontent.com/47757848/217290364-d0a06f74-6fa7-410c-b0f4-ba3a88c0f384.png)

**Comment by codymccoy** [comment]
These are the errors for this occtype:
![image](https://user-images.githubusercontent.com/47757848/217290909-d07a2a8d-4b2f-44d0-a4f8-60c4859838a4.png)
![image](https://user-images.githubusercontent.com/47757848/217290930-51e4d030-efad-4ae2-af84-05fb668d1b79.png)

**Comment by codymccoy** [comment]
Seems like we could check for fatal errors in the occtypes and not compute if any are fatal?

**Comment by codymccoy** [comment]
the inventory class has rules that test each occtype. Maybe it isn't ever being checked?
![image](https://user-images.githubusercontent.com/47757848/217293702-0290c380-8ce7-47cf-9306-09062c56cde5.png)

**Comment by rnugent3** [comment]
Ok. So it sounds like further resolution here will be to not run the compute instead of returning the null sampled structure parameters object?

**Comment by codymccoy** [comment]
I think so. I am still investigating. Trying to fix a side bug that i just found.

**Comment by rnugent3** [comment]
I will prioritize getting that done. I look forward to learning about anything else you find.

**Comment by codymccoy** [comment]
The tractable stage damage tests are failing for this same reason. 
![image](https://user-images.githubusercontent.com/47757848/219715864-60047741-d12c-4293-a9a3-5d1c6485a907.png)

**Comment by rnugent3** [comment]
Understood. I will prioritize this work.

**Comment by rnugent3** [comment]
@rnugent3 follow up

**Comment by rnugent3** [comment]
Failing test confirms that we have work to do in avoiding null ref exceptions in stage damage compute 

![image](https://user-images.githubusercontent.com/25163165/232169612-61d32798-36cf-4afe-893e-e1f147f09251.png)
