### ISSUE TITLE
Rule messages calling toString on the errors list.

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#764]
There are several places that have rules that print a message that calls "ToString" on the errors. This produces a bad error message.
![image](https://user-images.githubusercontent.com/47757848/217347964-0e850089-838c-489f-b21b-e657fb80ddd6.png)
![image](https://user-images.githubusercontent.com/47757848/217347974-23b8408d-d7b0-4e13-9a1d-1046841b6d0d.png)

I think what we need to do is write something like this:
String.Join(", ", occupancyType.GetErrors().Cast<IErrorMessage>().ToList().Select(err => err.Message))

That is an ugly line of code that would have to go into many places. I am wondering if we should write a method next to GetErrors() that returns a nice string of the errors. Something like GetErrorMessages().

**Comment by rnugent3** [comment]
I support GetErrorMessages() ... @Brennan1994 any thoughts?

**Comment by codymccoy** [comment]
There are a couple rules in the Inventory class that also call ToString on the getErrors. 
I would do a ctrl f and search everywhere for GetErrors().ToString()

**Comment by rnugent3** [comment]
awesome thank you

**Comment by codymccoy** [comment]
Not sure where I should put this information so I will put it here. @rnugent3 mentioned that the validation that takes place in framework was part of what was eating up so much time on some of the computes. He had me remove the validation call that I added to the Error logging. I see that there is a validate call in the "GetErrors" method in Base.
![image](https://user-images.githubusercontent.com/47757848/219792523-7e968e51-2aeb-428c-9039-897a6d434d8d.png)

We just want to avoid calling validate more than we have to. I am adding a method to "getErrorMessages()". I will not call validate on it. Maybe we should consider removing the validate call on GetErrors() and force the programmer to call Validate() if they think it needs it?

**Comment by codymccoy** [comment]
I submitted a PR for this in Framework. The messages will return as a single string formatted with a newline after each error like this:
![image](https://user-images.githubusercontent.com/47757848/220160555-9a2defa1-db03-42e2-89e3-ed08b0435463.png)
