### ISSUE TITLE
no unclicking structure damage checkbox in occ types

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#765]
We should not be able to unclick structure damage in the occupancy type editor. Our current set up does not handle structure damage as optional. Please make that checkbox not-editable or remove the checkbox entirely, whichever is easier. Thank you!

![image](https://user-images.githubusercontent.com/25163165/217632491-f523815c-9bb2-4f6d-9453-b277ddb3bc20.png)

**Comment by HenryGeorgist** [comment]
what if someone wants to model a point as a car only.

**Comment by Brennan1994** [comment]
User can assign structure damage to zero, or assign a depth percent damage function for an auto to the structure damage.

**Comment by codymccoy** [comment]
I currently have the checkbox selected and not editable, but I think we should just remove the checkbox on that tab. I think that would be less confusing to the user. @rnugent3 Thoughts?

**Comment by codymccoy** [comment]
Maybe add tooltip message on the structures checkbox?

**Comment by rnugent3** [comment]
For now, please remove the checkbox. Thank you.

**Comment by Brennan1994** [comment]
Checkbox is selected an not editable. Could be removed in the future entirely,
