### ISSUE TITLE
Strange Damage Collection 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#771]
The bin counts in the screen shot do not make sense. 99,992 $0 EADs and 8 EADs > $0. What the heck? How is this possible?

![image](https://user-images.githubusercontent.com/25163165/218214554-e124b765-d134-4e98-94c4-08071904ec52.png)

**Comment by rnugent3** [comment]
![image](https://user-images.githubusercontent.com/25163165/218216296-d06ac7ad-1593-4b30-8e1a-0e5cccfd4f3a.png)

**Comment by rnugent3** [comment]
![image](https://user-images.githubusercontent.com/25163165/218216827-7fa23901-fc23-4be7-b3db-ba3517621085.png)

**Comment by rnugent3** [comment]
these weird histograms are adding a lot of noise to the results. one solution will be to figure out how to not produce results for each asset category. however, I really want to understand how these histograms are collecting observations where damage is positive when all inventory values are zero.

**Comment by rnugent3** [comment]
maybe this is related to #755 

![image](https://user-images.githubusercontent.com/25163165/218217758-92e662e6-c791-4c57-bb8c-e42fe7eba17b.png)

**Comment by HenryGeorgist** [comment]
how do you determine which asset category to put a result in. are you certian it is correct or is it possible that there is a problem with the algorithm to put a result in the proper histogram?

it seems like results are going to other and vehicle when they shouldnt ever....?

**Comment by HenryGeorgist** [comment]
it is also weird that the value 8.stuff is seen as the max in other and in strucutre. the odds of that should probably be low?

**Comment by rnugent3** [comment]
this was fixed by my fix for #755
