### ISSUE TITLE
Import Aggregated Stage-Damage Functions incorrectly assigns Damage and Asset Categories

### ISSUE THREAD

**Issue by jbslaughter** [HydrologicEngineeringCenter/HEC-FDA#774]
Build provided here: [\\share.hec.usace.army.mil\USACE\HEC-FDA\Version_2.0\LatestPortablePackage.7z](file://share.hec.usace.army.mil/USACE/HEC-FDA/Version_2.0/LatestPortablePackage.7z) used to test Beargrass Creek dataset.

The Damage Category selection box was empty and the Assest Category selection box contained the Damage Category.

![image](https://user-images.githubusercontent.com/89167848/219497189-990e8423-1225-49fc-b7be-92297d047f26.png)

**Comment by rnugent3** [comment]
I see that asset category is being assigned correctly but damage category is not. @codymccoy please prioritize this bug.

**Comment by rnugent3** [comment]
@jbslaughter thank you for reporting the issue

**Comment by codymccoy** [comment]
My beargrass creek study looks fine. Is it possible that the study you are using is really old? @jbslaughter can i get a copy of that study?
![image](https://user-images.githubusercontent.com/47757848/219724023-6e127542-7e04-450b-af26-5ead178f798a.png)

**Comment by codymccoy** [comment]
@rnugent3 Do you have a study that is showing this bug? I am not seeing it.

**Comment by rnugent3** [comment]
I am going to get you data ASAP. Do you have time to work on this today?

**Comment by codymccoy** [comment]
I don't think so. I am in a meeting right now and am trying to leave around 11 am today to go visit my brother who flew into town. I can make it my priority on Monday.

**Comment by rnugent3** [comment]
[Beargrass-Creek_1-4-3_Study-Data-Export.txt](https://github.com/HydrologicEngineeringCenter/HEC-FDA/files/10827430/Beargrass-Creek_1-4-3_Study-Data-Export.txt)
[ImpactAreas.zip](https://github.com/HydrologicEngineeringCenter/HEC-FDA/files/10827435/ImpactAreas.zip)

**Comment by codymccoy** [comment]
@rnugent3 I imported the txt file above and it didn't import any stage damages. I created a new one and it had correct dam cats.
![image](https://user-images.githubusercontent.com/47757848/221262342-8cd8eed1-7655-4bd8-b9d9-e34c318f9a1b.png)

**Comment by rnugent3** [comment]
Ok. So it seems like it might be the individual text file which would be awesome. I'll investigate.

**Comment by rnugent3** [comment]
8hrs

**Comment by rnugent3** [comment]
we also need to make sure that the importer brings in each unique function, and does not copy functions
