### ISSUE TITLE
Validation not applying error level to impact area stage damage

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#777]
We were running into a null reference exception because there was a fatal error on a CSVR and we refused to sample the erroneous CSVR. However, we should not have gotten to that point. We check if there are errors in the inventory (which would include errors in the occupancy types which would contain errors in the CSVR). The inventory shows that there is a fatal error. However, the error level is not applied to the impact area stage damage object. See attached screen shot. @Brennan1994 will you please take a look?

![image](https://user-images.githubusercontent.com/25163165/219903837-b65961d9-9174-46dd-b940-a1974bed58a4.png)

**Comment by rnugent3** [comment]
![image](https://user-images.githubusercontent.com/25163165/220494205-1b041ec6-cdb6-4351-bf0a-a7400cf4f865.png)
not fixed

**Comment by rnugent3** [comment]
There is a problem with Muncie occupancy types and it was not caught at the start of the compute

**Comment by Brennan1994** [comment]
I didn't intend to close that. Sorry about that. Must have been linked to that pull request.

**Comment by rnugent3** [comment]
I thought it was fixed!!

**Comment by rnugent3** [comment]
I had a little fix in PR #778 that I thought took care of the issue - but I ran into it again

**Comment by rnugent3** [comment]
I have the fix for the occupancy types on the way - but still do not have a fix for not preventing the stage damage compute

**Comment by rnugent3** [comment]
I think there is some weakness in the property rule system we're using. Maybe the way we're using it? I am seeing rules not being checked. E.g. graphical UPD.

**Comment by Brennan1994** [comment]
8hrs 
-figure out if this is broken for all objects
- confirm we're calling validate on all objects in the bubble chain.

**Comment by rnugent3** [comment]
I have written new unit tests to confirm that validation is behaving as expected. Work on this issue is done.
