### ISSUE TITLE
EAD = AAEQ if EAD same for base and future year

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#782]
I think we need some checks to see if the ead distribution is the same for both analysis years - in which case the aaeq distribution should match the ead distribution. At the moment, these two things do not match after uncertainty. 

EAD: 
![image](https://user-images.githubusercontent.com/25163165/220502227-d6b29c1c-5933-48db-92c3-255095a33a53.png)

AAEQ:
![image](https://user-images.githubusercontent.com/25163165/220502199-25b9388e-4c0c-457c-a730-1943e711268b.png)

**Comment by rnugent3** [comment]
I think that this issue is related to #798 - there is a frequent difference between base year EAD and mlf year EAD for a given probability step 

The three highlighted numbers should theoretically be exactly the same. 
![image](https://user-images.githubusercontent.com/25163165/221385917-b3adbba8-2a81-4580-9259-22da37963313.png)

**Comment by rnugent3** [comment]
This is it. Although there is a small difference - the difference is amplified by the sum of the bin count of base year EAD and the bin count of future year EAD.

**Comment by rnugent3** [comment]
The logic in the way that results are obtained stopped making sense when we moved to the quantiles approach for distribution combination. If we are not going to randomly sample EAD distributions then it does not make sense to create an AAEQ distribution - we should just calculate the moments and pass over the paired data (freq, aaeq) to plot that instead of the histogram. This means that the main object of alternative results will change from a histogram to a paired data object. 

For now, I'll keep creating a junk histogram so that we're plotting something, but I am going to completely re-wire the way that the results are obtained.

**Comment by rnugent3** [comment]
![image](https://user-images.githubusercontent.com/25163165/221978669-35db192a-598c-4918-9d4b-fda91f3f1a61.png)

same data different results

**Comment by rnugent3** [comment]
@rnugent3 follow up on this one

**Comment by rnugent3** [comment]
I'll follow up on this one after I address #798

**Comment by Brennan1994** [comment]
4hrs -

**Comment by Brennan1994** [comment]
@rnugent3 Confirm this is fixed and close

**Comment by rnugent3** [comment]
The residual difference is much smaller now after a few fixes that were jointly causing the problem. One more fix in making the checks I described above and this issue is complete.
