### ISSUE TITLE
Necessary plotting changes

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#784]
From Beth F:

"The display of a frequency curve must at least have an option to plot it on a frequency axis.  The user needs it echoed properly so they can compare to what they’ve got to check that it’s right.   Also, they  must be able to see the table, to check the values.

Also, I’d say including the confidence interval (computed from the equivalent record length) in the flow or stage frequency curve plot is necessary.  Perhaps a radio button to turn it off and on, if you want a simpler image?"

@codymccoy lets discuss

**Comment by rnugent3** [comment]
Further instruction from Beth: "Currently, analytical is using a Monte Carlo to do it, so perhaps a quick Monte Carlo of just frequency curve bootstrap and picking out the 90% interval? I think it takes a few seconds in SSP to do that (when it's not doing a 17C compute, which does it differnetly.)"

**Comment by rnugent3** [comment]
Part of this issue: display the AEP histogram using Sturge's rule

**Comment by rnugent3** [comment]
Make sure to address the notes in #789

**Comment by Brennan1994** [comment]
40hr

**Comment by Brennan1994** [comment]
@rnugent3  I'm closing this issue because it's got too many parts for me to keep track of. I broke it into three other issues I've tagged with Priority. Could you verify I've captured the important parts in those and edit/add issues to make sure we're tracking everything?

**Comment by rnugent3** [comment]
done. thank you.
