### ISSUE TITLE
monetary units

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#786]
We have a monetary units combo box in the study properties - but we're not doing anything with it - nor with the language. Could we please pull that stuff out?

**Comment by codymccoy** [comment]
No problem.

**Comment by codymccoy** [comment]
Units of measurment section removed:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/5a571d04-2a63-4819-8bec-94753c0234ef)

![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/d87ece9a-e695-4446-bbce-8f347ecb751b)

**Comment by codymccoy** [comment]
This was completed in branch scenario_year_894
