### ISSUE TITLE
"Impact Area Row" showing up

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#787]
![image](https://user-images.githubusercontent.com/47757848/221035606-e7a98282-3421-4727-9c61-f504f4b32d5e.png)

**Comment by codymccoy** [comment]
This is the issue:
![image](https://user-images.githubusercontent.com/47757848/221035982-bd07bd5e-ace6-4986-89e4-499cf379d430.png)
I can see that my comment turned out to not be accurate, lol.

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/221038014-1aef1a92-7b30-4e1c-9ed3-24943cb9a3bc.png)

I am seeing this on my study too. This shouldn't be too hard to fix. It is probably saving correctly the first time and then when the study loads the name is getting set to "impact area row" (I still don't know why I am doing that). This probably means that if the user has saved the stage damage, that name is now being saved into the database. They will probably have to create new stage damages to get better names again.

**Comment by rnugent3** [comment]
Makes sense. Do you have time to fix this today?

**Comment by codymccoy** [comment]
I don't think so. I am in a meeting right now and am trying to leave around 11 am today to go visit my brother who flew into town. I can make it my priority on Monday.

**Comment by codymccoy** [comment]
The first thing i would want to figure out is what is being saved to xml. If we are displaying a name the user than that name must be getting written out. We should be reading that value back in and using it instead of "impact area row".

**Comment by codymccoy** [comment]
This is what is in the database:
![image](https://user-images.githubusercontent.com/47757848/221266574-0c840c1a-570e-41f8-ab8d-98160d5f6de2.png)

We are storing the impact area ID. I think we just need to use that ID to get the actual name of the impact area with that id.

In my case i only have one impact area called Muncie.
![image](https://user-images.githubusercontent.com/47757848/221266702-cc596ed4-0a94-4d78-8190-5f2af3bb5322.png)

**Comment by codymccoy** [comment]
This is now fixed. I left a todo statement for myself. I think there is room for improvement on this one, but I think what I did is fine for now. Basically we just needed to get the name from the ID.
![image](https://user-images.githubusercontent.com/47757848/221274961-7602af9a-e2e5-427c-b3a8-938a31093aea.png)

This is fixed in branch stage_damage_dam_cat

**Comment by rnugent3** [comment]
AMAZING THANK YOU for getting this wrapped up so fast. Please submit a PR and I'll take it from there. If you have a minute, sketch up an issue with your thoughts for further improvements?

**Comment by codymccoy** [comment]
PR created. I would say just don't close this bug out yet and I will take a look at it next week.

Cody- Look at this todo:
![image](https://user-images.githubusercontent.com/47757848/221275899-7c75b10b-6bef-4e57-8db3-5726c0958944.png)

**Comment by Brennan1994** [comment]
2hrs
