### ISSUE TITLE
Performance report must indicate levee

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#792]
We need to figure out a way to demonstrate to the user that the threshold is based on a levee. I think this can take place within the model as a new threshold type. I'd actually do two: with and without fragility. @codymccoy if I add threshold types in the threshold type enum and handle it appropriately in the model, is there anything you'll need to do?

**Comment by codymccoy** [comment]
Sounds good. I think this is the enum you are talking about:
![image](https://user-images.githubusercontent.com/47757848/221209437-f0abf536-1c3a-41fd-95ee-bf22be385c7a.png)

This is the threshold type and the 7 references to it at the bottom:
![image](https://user-images.githubusercontent.com/47757848/221209560-e5bfa668-0977-474a-8f74-2a749677f2d6.png)
Maybe some of those references would need to be updated to use the new enum?
"a way to demonstrate to the user" - Not sure what that looks like.

**Comment by rnugent3** [comment]
I’ll take a look this weekend. Thanks @codymccoy
