### ISSUE TITLE
uncontrolled randomness

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#798]
The results from one simulation are slightly different if re-computed. Did we miss a seed somewhere? 

@HenryGeorgist if you have a couple minutes, I'd appreciate your help investigating. The means are the same but the distributions are not. The quartiles are off by less than $100 - a very small fraction. I am not sure if it matters, but it looks like the difference is increasing with increasing cumulative probability.  

My greater concern for **this** is that I think the issue is related to #782. 

## Existing Condition Future Year Left Bank EAD Results
![image](https://user-images.githubusercontent.com/25163165/221384679-fd833a45-1c09-4cc4-8b58-66edafd77a37.png)

## Same Results Recomputed 
![image](https://user-images.githubusercontent.com/25163165/221384776-10425c96-26b9-40b4-a996-757891698bda.png)

**Comment by HenryGeorgist** [comment]
is this only the EAD compute. so aggregated stage damage functions are fixed?

EAD compute is parallelized, is convergence occurring before max iterations or is it strictly at max iters.

check if the number of simulations is identical between the two.

**Comment by rnugent3** [comment]
assurance of the threshold for the .02 event is always the same from compute to compute - the others are not. the configuration of the methods below appears to be related. 

![image](https://user-images.githubusercontent.com/25163165/221699189-4f79f454-eed5-4b0a-b8c1-6657c8222934.png)

**Comment by rnugent3** [comment]
so we should test for convergence of all histograms maybe?

**Comment by HenryGeorgist** [comment]
If we are converging on a poorly stated metric, yes we should converge for other metrics. I'm not sure the answer is convergence for all metrics though.

**Comment by Brennan1994** [comment]
40hrs

**Comment by rnugent3** [comment]
I have re-confirmed that this problem is isolated to the scenario compute and not found in the stage-damage compute. 

![image](https://user-images.githubusercontent.com/25163165/233169656-295514b3-a19c-4e50-b14d-0aa9b3e780bf.png)
![image](https://user-images.githubusercontent.com/25163165/233169700-0891c8d6-46b0-4292-b1e0-eef3447da60f.png)

**Comment by rnugent3** [comment]
## EAD With Uncertainty - Left Bank
![image](https://user-images.githubusercontent.com/25163165/233169916-4c428506-f078-4286-aa9d-5a1a48b3a338.png)
![image](https://user-images.githubusercontent.com/25163165/233170382-ce9e3ab0-7dbc-4d17-8177-7a28c6da7cb5.png)

## AEP With Uncertainty - Left Bank
![image](https://user-images.githubusercontent.com/25163165/233169980-386fe0b5-2e19-47c3-9f49-675f86e1de7b.png)
![image](https://user-images.githubusercontent.com/25163165/233170651-30e195ea-4075-44b6-bd51-550842171380.png)

## Assurance of Threshold - Left Bank
![image](https://user-images.githubusercontent.com/25163165/233170022-efe66c62-90a0-4158-8894-4235bfec5fda.png)
![image](https://user-images.githubusercontent.com/25163165/233170718-dec67270-9265-4f97-8cbb-789249bebaac.png)

## Damage with Uncertainty - Right Bank 
![image](https://user-images.githubusercontent.com/25163165/233170156-85234047-093b-4726-9070-921a4da37e3e.png)
![image](https://user-images.githubusercontent.com/25163165/233170831-52d8d23b-566c-4e68-9a1f-b1b817910f00.png)

## AEP with Uncertainty - Right Bank
![image](https://user-images.githubusercontent.com/25163165/233170293-047553e6-718a-43e9-8635-5d9c9c4422e0.png)
![image](https://user-images.githubusercontent.com/25163165/233170974-c142ecba-8886-4098-84a1-1c8f7a0ae6a4.png)

## Assurance of Threshold - Right Bank
![image](https://user-images.githubusercontent.com/25163165/233170353-22dd4a6e-b9b9-41a4-9246-baf7b15434f6.png)
![image](https://user-images.githubusercontent.com/25163165/233171071-e48d7a38-c84f-41a7-9bf1-f8f1fb2e5aa1.png)

**Comment by rnugent3** [comment]
I changed the LP3 + Rating to Graphical Stage-Freq, ran two computes, they're different - so does not appear to be related to the use of an LP3. 
![image](https://user-images.githubusercontent.com/25163165/233173147-fdbf3f47-35c0-40b4-b7d5-ccec7dcdff39.png)
![image](https://user-images.githubusercontent.com/25163165/233173170-2a66f5db-9cdd-4d26-927c-c21f69ad5872.png)

**Comment by rnugent3** [comment]
Perhaps the difference between the results comparison of the two impact areas is that damage in the left bank is an order of magnitude higher.

**Comment by rnugent3** [comment]
I have a test for this issue, I cannot get the test to fail:

```
        [Theory]
        [InlineData(1111, 50000)]
        [InlineData(1234, 50000)]
        public void RandomnessShouldBeControlledWithSeed(int seed, int iterations)
        {
            ContinuousDistribution flow_frequency = new LogPearson3(mean: 3.6, standardDeviation: 0.45, skew: 0.075, sampleSize: 40);
            //create a stage distribution
            IDistribution[] stages = new IDistribution[2];
            for (int i = 0; i < 2; i++)
            {
                stages[i] = new Triangular(0, 0.3*30*i, 30*i) ;
            }
            UncertainPairedData flow_stage = new UncertainPairedData(Flows, stages, metaData);
            //create a damage distribution
            IDistribution[] damages = new IDistribution[3]
            {
                    new Normal(1000, 100),
                    new Normal(34735984.75983, 1000),
                    new Normal(549584098.509458, 10000)
            };
            UncertainPairedData stage_damage = new UncertainPairedData(Stages, damages, metaData);
            List<UncertainPairedData> upd = new List<UncertainPairedData>();
            upd.Add(stage_damage);
            ImpactAreaScenarioSimulation simulation = ImpactAreaScenarioSimulation.builder(id)
                .withFlowFrequency(flow_frequency)
                .withFlowStage(flow_stage)
                .withStageDamages(upd)
                .build();

            RandomProvider randomProvider = new RandomProvider();
            ConvergenceCriteria convergenceCriteria = new ConvergenceCriteria(minIterations: 10000, maxIterations: iterations);

            ImpactAreaScenarioResults results_one = simulation.Compute(randomProvider, convergenceCriteria);
            ImpactAreaScenarioResults results_two = simulation.Compute(randomProvider, convergenceCriteria);

            //Mean EAD
            Assert.Equal(results_one.MeanExpectedAnnualConsequences(), results_two.MeanExpectedAnnualConsequences());

            //EAD Distribution
            Assert.Equal(results_one.ConsequencesExceededWithProbabilityQ(exceedanceProbability: 0.25), results_two.ConsequencesExceededWithProbabilityQ(exceedanceProbability: 0.25));
            Assert.Equal(results_one.ConsequencesExceededWithProbabilityQ(exceedanceProbability: 0.50), results_two.ConsequencesExceededWithProbabilityQ(exceedanceProbability: 0.5));
            Assert.Equal(results_one.ConsequencesExceededWithProbabilityQ(exceedanceProbability: 0.75), results_two.ConsequencesExceededWithProbabilityQ(exceedanceProbability: 0.75));

            //Mean and Median AEP
            Assert.Equal(results_one.MeanAEP(thresholdID: 0), results_two.MeanAEP(thresholdID: 0));
            Assert.Equal(results_one.MedianAEP(thresholdID: 0), results_two.MedianAEP(thresholdID: 0));

            //AEP Distribution - Assurance of AEP
            Assert.Equal(results_one.AssuranceOfAEP(thresholdID: 0, exceedanceProbability: 0.10), results_two.AssuranceOfAEP(thresholdID: 0, exceedanceProbability: 0.10));
            Assert.Equal(results_one.AssuranceOfAEP(thresholdID: 0, exceedanceProbability: 0.04), results_two.AssuranceOfAEP(thresholdID: 0, exceedanceProbability: 0.04));
            Assert.Equal(results_one.AssuranceOfAEP(thresholdID: 0, exceedanceProbability: 0.02), results_two.AssuranceOfAEP(thresholdID: 0, exceedanceProbability: 0.02));
            Assert.Equal(results_one.AssuranceOfAEP(thresholdID: 0, exceedanceProbability: 0.004), results_two.AssuranceOfAEP(thresholdID: 0, exceedanceProbability: 0.004));
            Assert.Equal(results_one.AssuranceOfAEP(thresholdID: 0, exceedanceProbability: 0.002), results_two.AssuranceOfAEP(thresholdID: 0, exceedanceProbability: 0.002));

            //Assurance of Threshold 
            Assert.Equal(results_one.AssuranceOfEvent(thresholdID: 0, standardNonExceedanceProbability: 0.90), results_two.AssuranceOfEvent(thresholdID: 0, standardNonExceedanceProbability: 0.90));
            Assert.Equal(results_one.AssuranceOfEvent(thresholdID: 0, standardNonExceedanceProbability: 0.96), results_two.AssuranceOfEvent(thresholdID: 0, standardNonExceedanceProbability: 0.96));
            Assert.Equal(results_one.AssuranceOfEvent(thresholdID: 0, standardNonExceedanceProbability: 0.98), results_two.AssuranceOfEvent(thresholdID: 0, standardNonExceedanceProbability: 0.98));
            Assert.Equal(results_one.AssuranceOfEvent(thresholdID: 0, standardNonExceedanceProbability: 0.996), results_two.AssuranceOfEvent(thresholdID: 0, standardNonExceedanceProbability: 0.996));
            Assert.Equal(results_one.AssuranceOfEvent(thresholdID: 0, standardNonExceedanceProbability: 0.998), results_two.AssuranceOfEvent(thresholdID: 0, standardNonExceedanceProbability: 0.998));
        }
```

**Comment by rnugent3** [comment]
I even pulled the seed out of the random provider, still passes.

**Comment by rnugent3** [comment]
I added a small change - instead of two computes off of the same impact area scenario, one compute off of two impact area scenarios constructed with the same data. The test failed by a little bit. 

```
            ImpactAreaScenarioSimulation simulation = ImpactAreaScenarioSimulation.builder(id)
                .withFlowFrequency(flow_frequency)
                .withFlowStage(flow_stage)
                .withStageDamages(upd)
                .build();

            ImpactAreaScenarioSimulation simulation2 = ImpactAreaScenarioSimulation.builder(id)
                .withFlowFrequency(flow_frequency)
                .withFlowStage(flow_stage)
                .withStageDamages(upd)
                .build();

            RandomProvider randomProvider = new RandomProvider();
            ConvergenceCriteria convergenceCriteria = new ConvergenceCriteria(minIterations: 10000, maxIterations: iterations);

            ImpactAreaScenarioResults results_one = simulation.Compute(randomProvider, convergenceCriteria);
            ImpactAreaScenarioResults results_two = simulation2.Compute(randomProvider, convergenceCriteria);
```

**Comment by rnugent3** [comment]
So there is something about the construction of the impact area scenario that is random???

**Comment by rnugent3** [comment]
This line passes as long as the method confirms that the results are not equal:

```
            Assert.True(simulation.Equals(simulation2));

```

**Comment by rnugent3** [comment]
So how could it be that the same two objects compute two different EAD distributions?

**Comment by rnugent3** [comment]
Since only EAD is different - performance is not - this makes me think that the issue has to do with the way that stage-damage is sampled or the way that stage-damage is combined with stage-frequency.

**Comment by rnugent3** [comment]
While stage-damage is the only function composed of empirical distributions, my unit test uses a parametric distribution and still fails.

**Comment by rnugent3** [comment]
changing stage-damage to a parametric distribution does bring the EAD distributions closer

**Comment by rnugent3** [comment]
From GMK: This could have to do with the order of operations. Due to the parallel compute, the nature of loss of precision is random.

**Comment by rnugent3** [comment]
I think the solution might be to create the histogram with min, max, and bin width. 

It seems since the first queue contains a random set of iterations, and since that queue identifies the histogram parameters, then we can have variation in histogram state from one compute to the next.

**Comment by rnugent3** [comment]
I misled myself by looking at the first failing assertion statement. All of the results vary from compute to compute. This means that the random construction of a threadsafeinlinehistogram for EAD is probably a symptom. All of the results differ from compute to compute - AEP and assurance, to boot. The variation from compute to compute is small, but enough to want to chase down.

**Comment by rnugent3** [comment]
Since the AEP results differ from compute to compute that means that the random construction of a histogram is only a symptom because the AEP histogram is constructed the exact same way for every compute, every study. There is a fixed min, max, and bin width.

**Comment by rnugent3** [comment]
So now the question is, could the order matter when adding observations to the same histogram so that loss of precision is random? 

Really the question at hand is whether random loss of precision is generating the uncontrolled randomness in our results, or is it something completely different. 

I don't want to spend too much time spinning wheels on this one internally.

**Comment by rnugent3** [comment]
I have confirmed that the source of randomness is the multi-threaded process in the simulation compute. I have tests for the equality of results for two different computes that fail when running the compute in parallel. When you switch the parallel for to a regular 'for', my tests on the equality of the results pass.
