### ISSUE TITLE
Levee increases damage

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#808]
Something went wrong. Levees increase EAD. 

## With Levee
![image](https://user-images.githubusercontent.com/25163165/222231134-3b4acc5d-7a03-456c-b96a-fd0ff4f2c1ec.png)

## Without Levee
![image](https://user-images.githubusercontent.com/25163165/222231194-284576e1-bad2-494c-b706-4ad85d739c78.png)

**Comment by rnugent3** [comment]
I made the levee even bigger and damage got higher

![image](https://user-images.githubusercontent.com/25163165/222234456-b15dbee3-a7aa-4889-a508-b602078804bb.png)

**Comment by rnugent3** [comment]
This is on main branch so has nothing to do with any of my recent refactor work

**Comment by HenryGeorgist** [comment]
https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/ff9bcedc5f08ac040295ea3d33256cf682197665/fda-model/compute/ImpactAreaScenarioSimulation.cs#L369
what does this produce on the levee?
is it percents or whole numbers

**Comment by HenryGeorgist** [comment]
i suspect failures are not being converted to percents

**Comment by rnugent3** [comment]
First attempt at reproducing failed. The results seem reasonable. 
![image](https://user-images.githubusercontent.com/25163165/226989737-1e5926a0-3e17-4737-8051-b2c1b14beddf.png)
![image](https://user-images.githubusercontent.com/25163165/226989757-fd85f052-3221-44ad-99ca-5308de6faa31.png)
![image](https://user-images.githubusercontent.com/25163165/226989782-6d722a2a-2569-4a8c-a929-9782962137d1.png)

**Comment by rnugent3** [comment]
I have a replicating study:
![image](https://user-images.githubusercontent.com/25163165/227003808-c7b5cd28-49ea-4298-a874-3068f7a5e5cb.png)
![image](https://user-images.githubusercontent.com/25163165/227003829-700e004c-51c9-4273-bba8-3b34c3401c28.png)

![image](https://user-images.githubusercontent.com/25163165/227003852-64c33f07-1c1d-456c-8738-29d0b74b58e0.png)
![image](https://user-images.githubusercontent.com/25163165/227003881-b4918b3f-6822-48c4-9c1b-dc27dfc23f1c.png)

**Comment by rnugent3** [comment]
this is happening because of a combination of conditions:

1. sparsely defined fragility function with big differences in stage between coordinates
2. using the stages from the fragility function for the multiply instead of the stages from the stage damage function

When we're using the x values from a sparsely defined fragility function, we lose the nonlinearity in the stage-damage function which can result in a more linear function which, despite having lower damage for some frequencies, ends up sitting above the without-project damage frequency for some of the higher-frequency damages.

**Comment by rnugent3** [comment]
![image](https://user-images.githubusercontent.com/25163165/227025636-f3c87980-cf40-46cb-9324-101d039ee932.jpeg)

**Comment by rnugent3** [comment]
instead, we should take as new xvals the stages from the stage-damage function and identify f(stage)=failureprob

**Comment by Brennan1994** [comment]
40hr

**Comment by rnugent3** [comment]
we need both:

1. Stages from the stage-damage function to preserve stage-damage non-linearity 
2. Stages from fragility function to identify stage at which prob of failure becomes certain, and secondarily (but not as important because we use small stage increments in stage damage) to maintain fragility function non-linearity

**Comment by rnugent3** [comment]
![image](https://user-images.githubusercontent.com/25163165/227623414-a86cdb44-7310-4e3e-ac46-86f24e5a7e25.png)
bada bing bada boom
