### ISSUE TITLE
scenario names show up weird in alternative 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#809]
the software appears to not handle underscores between numbers?

![image](https://user-images.githubusercontent.com/25163165/222469279-d8b56790-77b5-4f0d-8b1b-de391e335227.png)

**Comment by codymccoy** [comment]
Not sure why that first underscore was getting dropped. The alternative editor is different now and I do not see this problem anymore. 
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/b9f843fc-c71c-4c3c-a83a-10f7004e4e6b)
This is completed in scenario_workflow_818

**Comment by rnugent3** [comment]
Terrific!
