### ISSUE TITLE
view results index out of bounds exception

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#810]
attempted to view results of levee three scenario of workshop 5 muncie data 

![image](https://user-images.githubusercontent.com/25163165/222476373-fe13614b-bbfc-4a8f-83b3-7967b277da82.png)

I removed and recomputed - still have the issue. I was able to view results for this scenario at some point.

**Comment by rnugent3** [comment]
this happens when you edit the levee height and recompute

**Comment by Brennan1994** [comment]
8hr

**Comment by rnugent3** [comment]
could not replicate
