### ISSUE TITLE
Terrain validation

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#815]
We hit an unhandled exception if we can't access terrain successfully

**Comment by rnugent3** [comment]
is there a way to validate whether we can read the terrain when they are attempting to import?

**Comment by Brennan1994** [comment]
There is, The view model can construct a file in a try catch and throw an error if it needs to.

**Comment by rnugent3** [comment]
I don't have a terrain file in my study. I attempted to compute stage-damage. I ran into the below unhandled exception. We do have the try, catch, but I uncommented so I could diagnose where the exception came from. 

Is there a way to improve messaging to the user  that they need to import terrain for the stage damage compute when using HDF?

![image](https://user-images.githubusercontent.com/25163165/231267706-f60aa045-ff38-4467-9088-4cfb28d79cc7.png)

**Comment by Brennan1994** [comment]
This has been since addressed.
