### ISSUE TITLE
Threshold calculation 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#820]
We need to handle thresholds one of three ways:

1. If without-project condition, calculate default threshold 
2. If levee present, calculate default threshold
3. If with-project condition and no levee present, use without-project condition threshold 

I think that (3) means that we'll need a way to force the user to decide if with- or without-project condition, and then act upon their logic route 

![image](https://user-images.githubusercontent.com/25163165/223200417-ae92c9b4-072f-4a38-9059-48b68ad6615a.png)

**Comment by Brennan1994** [comment]
Prevents user from getting critical information : YES
Saves to disk in a way that would be hard to support going forward if we release as is: MAYBE
Is difficult enough to use that it would be embarrassing to release: YES

**Comment by rnugent3** [comment]
we want a rigid workflow but we don't want to link scenarios. we might create a thresholds report to help the user enter the correct data

**Comment by rnugent3** [comment]
as part of this issue, lets address threshold types. interior stage does not make sense - where inside the floodplain should this be? lets drop this until we have a good use case. damage could make sense, we'd collect the same way as stage for assurance. however, we have no use cases or demand for this information, so I don't see a reason to finish out that capability at this time.

**Comment by rnugent3** [comment]
the user should only be able to add exterior stage threshold type so we should remove the option to select threshold types

**Comment by rnugent3** [comment]
![image](https://user-images.githubusercontent.com/25163165/224106423-33249875-1592-4c60-a06f-45260e3e1276.png)
![image](https://user-images.githubusercontent.com/25163165/224106517-2848815d-1ca1-4f51-b7d6-e6d8a21a6712.png)

**Comment by rnugent3** [comment]
we always have a system response in the model, so we need a way to identify whether the system response is a true system response or just the default so that we can assign the correct threshold type

**Comment by rnugent3** [comment]
https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/93794889c17f484de2ec5dcfaa5d1e5c9523fc7b/HEC.FDA.ViewModel/GeoTech/LateralStructureElement.cs#L80

**Comment by Brennan1994** [comment]
40hrs

**Comment by codymccoy** [comment]
Notes from meeting with Richard:
Right click a scenario and menu item "View Thresholds...". 

in the Scenario UI:
new checkbox  "Scenario reflects without project conditions"(default to true), default stage (textbox), thresholds
the text box is only enabled in the one condition(3)
if unchecked and no levee then default stage becomes enabled and is required to compute.

**Comment by codymccoy** [comment]
@rnugent3 I assume the thresholds table is not editable, it is just for the user to view?
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/d6a79131-7714-4a61-bff7-cb2490591e79)

**Comment by codymccoy** [comment]
Menu item added and UI:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/87bffbbb-258b-4d88-9ba8-be62b27413ae)
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/f8e309f1-0e93-41fb-b45d-5ac780a646de)

This work was completed in branch scenario_threshold_820 as well as in branch scenario_workflow_818

**Comment by codymccoy** [comment]
I added live updates. So if you modify the thresholds in the IAS editor while the thresholds table is still open, it will automatically update to the new info.

**Comment by rnugent3** [comment]
This is terrific. 

Is there a way that you can detect whether there is no default threshold calculated/identified, and if so, let the user know? 

I think it is important that this is communicated.
