### ISSUE TITLE
batch actions

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#822]
We should have three "batch" actions for all scenarios:
1. Compute
2. Display EAD
3. Display project performance 
The batch report would display results across all dimensions and scenarios. It is rather inconvenient that results are only available one scenario, one impact area at a time.

**Comment by rnugent3** [comment]
batch actions should include a checkbox list to select which scenarios to include in the batch action

**Comment by rnugent3** [comment]
we should have a similar reporting batch action on alternatives

**Comment by rnugent3** [comment]
"View Scenario Summary Reports" and "View Alternatives Summary Reports"

**Comment by rnugent3** [comment]
and we'll need a "View Alternative Comparison Summary Reports" - see Issue #824

**Comment by rnugent3** [comment]
The tricky thing is that the alternative comparison report won't really need to be a batch action because it is set up as a batch action already

**Comment by Brennan1994** [comment]
Prevents user from getting critical information : NO
Saves to disk in a way that would be hard to support going forward if we release as is: NO
Is difficult enough to use that it would be embarrassing to release: YES

**Comment by rnugent3** [comment]
three new buttons and three new controls: compute all scenarios, view scenarios summary results, view alternatives summary results

**Comment by Brennan1994** [comment]
40hrs

**Comment by codymccoy** [comment]
I want to make sure that I am understanding this correctly. I will display the original menus below and then the updated menu items that I think i am being asked to create:

Original Menus:
scenario parent menu:
![image](https://user-images.githubusercontent.com/47757848/231011144-548b2651-60da-47b6-a2d6-2838db8201e9.png)

scenario menu:
![image](https://user-images.githubusercontent.com/47757848/231011229-8a911e94-59ea-4cbb-b07d-ef477877c6b9.png)

Alternative parent menu:
![image](https://user-images.githubusercontent.com/47757848/231011250-483bc2d3-a8e4-4f25-b74d-0aa5e145967b.png)

Alternative menu:
![image](https://user-images.githubusercontent.com/47757848/231011274-b91cf752-7b3f-4fab-a73f-f0ddb2996ff2.png)

Alt comp parent menu:
![image](https://user-images.githubusercontent.com/47757848/231011308-96724a06-ef9d-43c4-a937-519926cab9fa.png)

Alt comp menu:
![image](https://user-images.githubusercontent.com/47757848/231011333-2ffafdbe-dcac-4153-9fb0-ccc38a0230ac.png)

**Comment by rnugent3** [comment]
Each of the items we're asking for should go into the parent menu

**Comment by rnugent3** [comment]
I will make some example tables in excel to help illustrate how the summary results should look.

**Comment by codymccoy** [comment]
new scenario parent menu:
![image](https://user-images.githubusercontent.com/47757848/231012365-a8c4b12c-9b7b-4ea0-a1ea-dc861cdb6c7a.png)

This menu item will compute all of the scenarios and then display a new UI? Or am i displaying a new UI that allows the user to select the scenarios using checkboxes and then click "compute"?

**Comment by rnugent3** [comment]
I like this idea: Or am i displaying a new UI that allows the user to select the scenarios using checkboxes and then click "compute"?

And then just a message box "All computes completed, would you like to view summary results? What do you think?

**Comment by rnugent3** [comment]
And do you think that we should use the same UI that allows the user to select scenarios and alternatives to generate the summary report?

**Comment by rnugent3** [comment]
[SummaryResults.xlsx](https://github.com/HydrologicEngineeringCenter/HEC-FDA/files/11194591/SummaryResults.xlsx)

**Comment by codymccoy** [comment]
This is what I have so far: 
Scenarios:
![image](https://user-images.githubusercontent.com/47757848/231218022-5008e00b-ff63-489c-b68a-82fc0fd160eb.png)

Alternatives:
![image](https://user-images.githubusercontent.com/47757848/231218056-9bee1392-ca39-4977-aecf-e56b0bc6abe3.png)

I am using the same UI and VM with an enum to tell me which version to use so that I can update labels etc.

**Comment by codymccoy** [comment]
@rnugent3 Does this look correct for how to fill out the row of values in the table:
![image](https://user-images.githubusercontent.com/47757848/231546009-0eb269a8-3858-4404-979e-7fff03dc0a27.png)
![image](https://user-images.githubusercontent.com/47757848/231546036-466dbc8f-cdf7-4ca6-a997-d399a59ff6c1.png)

**Comment by rnugent3** [comment]
Swap the .25 and the .75. Consequences exceeded with probably of 0.75 is the first quartile. 

Is it possible to list the actual dam cats in the table header?

**Comment by codymccoy** [comment]
Yes, the actual dam cat names will be in the column headers. Can we assume the dam cat names will be the same for all scenarios?

**Comment by rnugent3** [comment]
The dam cats could be different. I think if you requested damage for a particular damage category that was not in the results, you'll get back a zero, which is what we want. We'll have to test. 

The dam cats do come from the occ types, which do get assigned to structures

**Comment by codymccoy** [comment]
This table is getting complicated. I am wondering if we could make a second table to handle the dam cats. If there are 20 dam cats, then this table is going to be super wide and require scrolling. Especially if one has 20 dam cats that don't overlap with another 20 dam cats. Part of the complication here is that there doesn't appear to be a default wpf way of creating grouped headers like you want in this table. There are some hacks online which is what I am doing (you can see that the top row doesn't quite match the width. I seem to be off by a couple of pixels). Maybe there is a way to make the damcats go vertically in another table?

**Comment by rnugent3** [comment]
A second table sounds like a good idea.

**Comment by codymccoy** [comment]
When you modify a child element that a scenario depends on an asterisk appears on the scenario with a tooltip message. Once you close the study and open it the asterisk is gone and no tooltip message. I added some validation on the load method that puts the asterisk and a message back on the scenario.
![image](https://user-images.githubusercontent.com/47757848/232822356-b6a2687c-b338-47a0-9806-b59fa6fb2634.png)

**Comment by codymccoy** [comment]
A PR has been submitted for this issue. There was a lot of work on this issue which is discussed below. I vote that we try to close this issue out and start new issues for any subsequent work on this issue.

Notes about the work that I did:
![image](https://user-images.githubusercontent.com/47757848/236583299-1c54aa16-a5dc-4449-89e5-e1bc68cd3a2d.png)

![image](https://user-images.githubusercontent.com/47757848/236583480-945adca6-88a5-4df7-9b29-536b456a641e.png)

![image](https://user-images.githubusercontent.com/47757848/236583499-c71438ef-6ac3-451e-b378-c2676690eb18.png)

**Comment by Brennan1994** [comment]
@rnugent3 have you tested this enough to close out this issue?

**Comment by rnugent3** [comment]
I did a detailed test with respect to the referenced PR and all associated issues.
