### ISSUE TITLE
focus damage reporting 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#823]
We should remove EAD reporting at the alternative level.

- Scenario damage is EAD
- Alternative damage is AAED
- Alternative comparison damage is EAD Reduced and AAED Reduced

**Comment by rnugent3** [comment]
easy to remove things

**Comment by rnugent3** [comment]
remove damage measure combo box and add "Average Annual Equivalent" to header or title 

![image](https://user-images.githubusercontent.com/25163165/223824037-6ff50c8d-5328-4654-8113-4492a6e73f0a.png)

**Comment by Brennan1994** [comment]
4hrs
