### ISSUE TITLE
add other H&H relationships to stage-damage editor

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#826]
We use H&H functions as part of the stage-damage compute for two things:

1. Calculate min and max stages at index location
2. Align WSE at structure to stage at index location _by probability_

Because of the second point above, we need to have the correct stage for a given probability. If there is flow regulation involved in the hydraulics modeling, we'll need to involve flow regulation in our calculation of the stage at the index location by probability. 

We need to think about whether this means that we need an interior/exterior function, too. I confuse myself on this one.

**Comment by rnugent3** [comment]
At the moment, we only accommodate a frequency function and a rating curve 

![image](https://user-images.githubusercontent.com/25163165/223283501-b69efc99-e4ca-4139-b347-4c47114198fe.png)

**Comment by rnugent3** [comment]
This issue can be resolved relatively simply. 

Optional: user selects a blank, include "(optional)" in header

**Comment by Brennan1994** [comment]
Prevents user from getting critical information : YES
Saves to disk in a way that would be hard to support going forward if we release as is: KINDA  
Is difficult enough to use that it would be embarrassing to release: YES

**Comment by Brennan1994** [comment]
6hrs

**Comment by codymccoy** [comment]
@rnugent3 What exactly am i changing here? Am i adding exterior/interior column? Is that the column that is "optional" and has a blank row?

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/230952385-54f85db2-360f-4c73-87cf-1653de383d2f.png)

**Comment by codymccoy** [comment]
By adding another column, we were running out of space I reworked the UI to put the table underneath the other combo options:
Original design:
![image](https://user-images.githubusercontent.com/47757848/230979610-63369203-fadf-4ea1-b56a-60aa648fd583.png)

New and improved:
![image](https://user-images.githubusercontent.com/47757848/230979647-0d4c8fae-e340-4f6a-ba58-3c7da8c1df11.png)

**Comment by rnugent3** [comment]
Looks terrific.

**Comment by codymccoy** [comment]
This is completed in branch stage_damage_ui_update_826. Just like the other items in that table, the reg-unreg elements in that column support live updating. This means that you can leave the editor open and create new reg-unreg elements and you will see them added to the combobox. Same with removing elements and name changes. If a saved reg-unreg no longer exists then the selected item will be the blank row.

Took about 6 hrs.
