### ISSUE TITLE
change alternative and alternative comp report dists to match scenario dist 

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#861]
Could we change the distributions of damage in the alternative results and alternative comparison report results to match the format of the damage distribution in the scenario results? I have included examples below. 

## Scenario EAD Distribution
![image](https://user-images.githubusercontent.com/25163165/230703018-b391a2ad-2709-49ad-bf78-d2cfcd72d279.png)

## Alternative AAED Distribution 
![image](https://user-images.githubusercontent.com/25163165/230703061-7c62553e-53ab-437b-8e45-037524ff04de.png)

## Alternative Comparison Report EAD Reduced 
![image](https://user-images.githubusercontent.com/25163165/230703083-ba18c9fa-6022-46f9-814c-86b5e527af80.png)

**Comment by Brennan1994** [comment]
@codymccoy I have the pattern for doing this mapped out in the DamageWithUncertaintyVM and it's associated control. Would you be willing to take care of the rest of them following the same pattern?

**Comment by codymccoy** [comment]
@Brennan1994 Yes, I'll take a look after I finish 822.

**Comment by codymccoy** [comment]
And this is the alt comp report:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/4b3446be-2d83-4c82-93e8-649dbc57bcec)

**Comment by codymccoy** [comment]
This was completed on branch scenario_threshold_820

**Comment by rnugent3** [comment]
Your assumption is correct. Please revise the plot titles to AAEQ Damage and Damage Reduced, respectively. 

@Brennan1994 would you mind reviewing Cody's work on this?

**Comment by codymccoy** [comment]
plot headers updated:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/57ca9f2c-2ad5-4166-b913-530bc7b411b7)
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/3f157727-99cf-46b2-b66c-fa52fd05c589)
This was completed on branch scenario_threshold_820

**Comment by rnugent3** [comment]
Could you please add the word "Distribution" after "Damage Reduced"

**Comment by codymccoy** [comment]
Updated title:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/14581c73-32d7-4658-a505-88b9d5d4b486)
