### ISSUE TITLE
frequency function uncaught exception

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#866]
The below uncaught exception happens on main as of 10 Apr 23. The study can be downloaded here: https://drive.hecdev.net/share/n11bZMSR

![image](https://user-images.githubusercontent.com/25163165/230738837-e5c9c6ea-b896-4a85-bf4d-0ae0e9ba6af7.png)

_Originally posted by @rnugent3 in https://github.com/HydrologicEngineeringCenter/HEC-FDA/issues/858#issuecomment-1500958774_

**Comment by Brennan1994** [comment]
Unable to reproduce. We need to look at your build together and figure out what's up. Something is screwy.
