### ISSUE TITLE
study file in properties does not update

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#868]
I have the box checked, but structure details are not written to file.

**Comment by rnugent3** [comment]
I found the files. I looks like the files are being written to a temp folder. I am not sure if this is something weird that I did, or something within the code? Anyway, the study directory does not match the directory to which the files are being written. 

![image](https://user-images.githubusercontent.com/25163165/231276159-0152274a-60eb-46da-9358-d0663f859e3d.png)

**Comment by rnugent3** [comment]
@codymccoy could I have moved the study, but the study directory in the properties did not update?

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/231277180-e4aea3d0-d08a-4671-8571-76da17c00886.png)
![image](https://user-images.githubusercontent.com/47757848/231277194-204231cb-8a76-4a90-832b-03ef4c8c323e.png)

Sounds like something is wrong with the _ProjectDirectory variable.

**Comment by codymccoy** [comment]
Not sure how that is possible. Looks like everytime a study is opened the project directory gets set here:
![image](https://user-images.githubusercontent.com/47757848/231278793-a276384f-82dd-4954-93bc-c19d85b37967.png)

@rnugent3 are you able to put a break point on that line and see what your project directory is?

**Comment by codymccoy** [comment]
I just tested on my machine and it wrote to the correct place.

**Comment by rnugent3** [comment]
@codymccoy it ends up that I moved a study, but the study file in the study properties did not update. I think this should update. Could we make that happen?

**Comment by codymccoy** [comment]
This is now fixed in branch occtype_missing_values_882. I also changed it to display the sqlite file in the study properties instead of the study directory since the label says "Study File:".
