### ISSUE TITLE
Negative EAD?

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#869]
In Cody's example study, we see negative damage for the first quartile of EAD distribution. This is nonsensical. Investigation.

**Comment by codymccoy** [comment]
![image](https://user-images.githubusercontent.com/47757848/232102204-9e03a060-3076-4d10-8dab-627f9c7e57f5.png)

**Comment by rnugent3** [comment]
Cody, could you either confirm what study data you had selected for the compute or upload your study with the negative EAD?

**Comment by codymccoy** [comment]
I am still seeing negative numbers in my muncie study. Can you send me a way to share my zipped study. It is too big to add here.
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/405a2399-3f52-4ba3-bac0-e1e5f1cb47fa)

**Comment by rnugent3** [comment]
I have sent a link.

**Comment by rnugent3** [comment]
this appears to happen when we're using manually-entered stage-damage functions

**Comment by rnugent3** [comment]
here is what happened: the manually-entered stage-damage function has wild variability so that theoretically a downward-sloping or below-zero curve could be sampled. I think that this happened because sample paired data for some reason did not force monotonicity.
