### ISSUE TITLE
Verify how we use year in service

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#883]

**Comment by rnugent3** [comment]
at the moment, we accept an analysis year as an argument of an ImpactAreaStageDamage constructor, but we do not allow the user to specify the analysis year. to use the year in service attribute, we'll need to add analysis year to the stage damage compute control.

**Comment by codymccoy** [comment]
I am adding an analysis year to the calculated stage damage. When importing from old FDA is there a value for this year or should I just make it the current year? For now I have added it as the current year.
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/48c05098-32e4-49b8-8c5c-2ef55f9edc53)

**Comment by rnugent3** [comment]
Just make it current year. 1.4.3 kept track of analysis years differently.

**Comment by codymccoy** [comment]
The analysis year has been added to the UI:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/cffa3c84-576c-4be1-940e-7b1a86159e08)

The year gets passed into the ImpactAreaStageDamage constructor when computing. I haven't tested what happens in the compute with the addition of this analysis year. 

This work was completed on branch scenario_year_894
