### ISSUE TITLE
NPE's when using IAS elements

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#884]
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/de307700-5772-484c-8ff9-d56dc9c84214)

![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/7a43d4d3-0628-4ad3-8cde-a2acd357cb6e)

**Comment by codymccoy** [comment]
I added a null check on the get Y Values and that got me past that one.

**Comment by rnugent3** [comment]
@codymccoy Do you have an idea of what caused the null y values? I'd like to validate for that.
