### ISSUE TITLE
Unable to close compute dialogue using close button

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#890]
I launched the software from the executable, computed all scenarios, and canceled about 10 seconds later. The close button does not close the compute dialogue - only the red X does.

**Comment by rnugent3** [comment]
it looks like this behavior occurs all the time - not just when you cancel a compute

**Comment by codymccoy** [comment]
I forgot to do anything with the close button. It is now plugged in to the closing event. 
Fixed in branch scenario_threshold_820
