### ISSUE TITLE
Study Load times seem longer

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#896]
My Beargrass creek study is taking around 4 seconds to load. I am not positive, but that seems longer than it used to be. I put a break point in the loading logic and the culprit is the frequency elements:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/665c1a2c-3672-4323-8c0b-9ca63a7d70d8)

I tracked it down to these load methods:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/0206b9a0-a405-4a69-9af1-877ab13bda40)

I am not sure if this is worth looking into more, but I thought I would at least create an issue in case someone wants to track it down further. It might just be that there is a lot on items to read from the database for frequencies.

**Comment by Brennan1994** [comment]
There's some montecarlo happening for LP3s. I've got a pull request in that should speed this back up.
