### ISSUE TITLE
Frequency editor radio button binding issue

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#901]
The frequency editor would crash when trying to pop it out into its own window. Now that I have fixed that, I was testing the editor by clicking the radio buttons and I got several strange behaviors. The output is saying this:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/921a3ee2-b8ec-402a-890d-a4b5e80c9b15)

The editor doesn't seem to have this problem when it is open in tab form.
Cody will investigate more.

**Comment by codymccoy** [comment]
For example, clicking "fit to flows" is not selecting that radio button:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/cfc4166f-9eac-48a3-9bab-7d01fcb471a4)

**Comment by codymccoy** [comment]
I simplified the radio button bindings. I think the wires were getting crossed somehow. It seems to be working correctly now.
This is fixed in branch scenario_threshold_820

**Comment by rnugent3** [comment]
Thanks @codymccoy
