### ISSUE TITLE
Computed Stage Damage requires a terrain file?

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#907]
I am working on the computed stage damage editor and i was getting an exception when clicking the "Compute Curves" button. 
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/ac04a18a-6a48-4768-beea-7d48815c0fc0)

My study doesn't have a terrain file:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/5279bb16-4785-4eed-a629-72a3343820ec)

I think all we need to do is add a validation check for the terrain file before we try to compute.

**Comment by codymccoy** [comment]
@Brennan1994 Do we really need the terrainLayer for all inventories? Seems like we should only need it if the inventory uses this option:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/fca80857-fe99-4387-b061-e5e2de1e86b4)

**Comment by rnugent3** [comment]
I'm tracking this rule: if using hydraulics in HDF, a terrain must have been uploaded fora successful stage damage compute, independent of the source for terrain data.

**Comment by codymccoy** [comment]
I am not sure what HDF stands for, but it sounds like we should add to the existing validation when the user clicks the compute button that a terrain exists. This would only take me a few minutes.

**Comment by rnugent3** [comment]
HDF is the type of file. 

Sounds good, thanks.
