### ISSUE TITLE
problems with saving/viewing alternatives

### ISSUE THREAD

**Issue by rtle76** [HydrologicEngineeringCenter/HEC-FDA#926]
It appears that the option to Compute under Alternatives is not available

**Comment by rtle76** [comment]
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/67108837/6fa62f05-24f3-49dd-8669-6c4ad1abd67c)

**Comment by rtle76** [comment]
When I click View Results... instead, an error pops up

**Comment by rtle76** [comment]
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/67108837/e8522ba9-ee0e-4457-a4bf-773db34d5cec)

**Comment by rtle76** [comment]
The discounting parameters in the study properties shouldn't be the issue. I didn't change any of the study properties

**Comment by rtle76** [comment]
<img width="526" alt="image" src="https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/67108837/15c1aee1-e255-4129-b9a4-66ace6016fb4">

**Comment by rtle76** [comment]
I did that and they're consistent. However, the future year scenario in the Alternative editor keeps switching to the base year scenario after I save and close. See below

**Comment by rtle76** [comment]
<img width="1084" alt="image" src="https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/67108837/e1296435-1788-4d2b-9f75-61f3eb948e93">

**Comment by rtle76** [comment]
See above the correct years and scenarios are chosen for the alternative. Saved seconds ago in the bottom right corner. But then, when I close and reopen:

**Comment by rtle76** [comment]
<img width="1087" alt="image" src="https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/67108837/419b297e-f064-41a7-b507-c64c0a7d53c3">

**Comment by rtle76** [comment]
For some reason the future scenario copies the base year scenario, with the analysis year untouched. Still won't give the option to compute, and still gives the error about discounting parameters when I try View Results... Something funky seems to be going on with the Alternative Editor

**Comment by rnugent3** [comment]
oh interesting!

**Comment by rnugent3** [comment]
@rtle76 would you mind testing with a new build, please? I have not been able to replicate this behavior. I updated the latest portable package within the 2.0 subdirectory of the HEC-FDA folder on the USACE share drive.

**Comment by rnugent3** [comment]
I see the behavior. Troubleshooting now. Thanks, Jordan.

**Comment by rnugent3** [comment]
@Brennan1994 something is messed up here in the view or view model, it seems like the software is having trouble saving the user's selection of scenarios. Because scenarios are not saved for a given alternative, when we go to view results, there are not scenario results to process for alternative results. Would you mind taking a look?

**Comment by Brennan1994** [comment]
The broken saving was a simple copy paste error. The compute still fails though as a result of the difference between the years being greater than the period of analysis. The error message was not helpful. 
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/64556723/46907c35-55cc-4d46-823d-6827136f08c3)
