### ISSUE TITLE
Scenario Validation Bug

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#935]
The scenario validation tooltip does not give the correct message. In the screen shot below, the tool tip is messaging to the user that they need to select a damage category for the preview compute, but the real issue is with the stage damage functions. 
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/25163165/73135b3e-6b6f-45c1-a7ca-7ec3c292e6ce)
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/25163165/6a234936-b994-4688-b1bd-b93f16f29b74)

**Comment by rnugent3** [comment]
It also appears that the live updating is not working. When we fix stage-damage functions, the validation on scenarios still reflects bad stage-damage functions.

**Comment by codymccoy** [comment]
@rnugent3 You mention that "the real issue is with the stage damage functions", but I see in the pic that the stage damage is selected. The tooltip message seems correct to me. I do need to update that validation to include the new stage damage combo that I added if the user is modeling non-failure.

**Comment by rnugent3** [comment]
I see. I am not sure that requiring a selection of damage category for optional visualization is fatal enough to be worthy of a red exclamation mark.

**Comment by rnugent3** [comment]
Thank you for updating the validation for non failure.

**Comment by rnugent3** [comment]
I revisited the images. 

It looks to me like the red exclamation mark on the specific bank is signaling the same problem that the error signals in the study tree are catching and the same problem messages in red in the compute log, but the tooltip gives a message about the preview compute.

**Comment by codymccoy** [comment]
Yes, i see that too. I am on it. This is the message we want the tooltip in the editor showing. It should be consistent.
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/de41b33d-ac11-4ee8-8d96-ba63d2320e68)

**Comment by codymccoy** [comment]
I think that is what it ultimately was doing, but the wording should be the same:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/56da8f1a-e7d7-40cd-b2e0-1abbb258fe39)

If there is something to select then we select the first one automatically:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/6ff99191-eb20-4129-8f55-d4be74aef2ba)

**Comment by codymccoy** [comment]
tab validation is working better now:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/d5bc406e-43ce-4fac-9424-ac36b563d06d)

**Comment by codymccoy** [comment]
I added the validation for the non failure combo:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/aa36118e-348d-4045-8bdd-2e60133f561e)
