### ISSUE TITLE
Notify User of Stage Damage Errors

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#957]
stage-damage errors are being written to the log file, but the user is not being notified that there are fatal issues and that they should check the log file. @Brennan1994 do you have thoughts on how we could let the user know?

_Originally posted by @rnugent3 in https://github.com/HydrologicEngineeringCenter/HEC-FDA/issues/819#issuecomment-1724570878_

**Comment by rnugent3** [comment]
@codymccoy could you apply your validation labels in the UI (the checkmark, red !, and yellow thing) to the stage-damage functions?

**Comment by codymccoy** [comment]
Are you looking for these icons to be on the stage damage names in the main tree or on the curves in the editor?
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/a4e08a84-63ba-41e0-b4f2-d1641a90a844)
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/89f15167-c09b-41f1-86bc-7e847f6314af)

**Comment by codymccoy** [comment]
I am still trying to refresh on how this all works. When i try to compute i get this error mesage:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/6f362101-1527-4319-9162-8abd740c6163)
Do you have a project handy that is producing the errors that are not showing to the user that you can send my way? I am currently using the Muncie project.

**Comment by rnugent3** [comment]
> Are you looking for these icons to be on the stage damage names in the main tree or on the curves in the editor? ![image](https://user-images.githubusercontent.com/47757848/269429638-a4e08a84-63ba-41e0-b4f2-d1641a90a844.png) ![image](https://user-images.githubusercontent.com/47757848/269429969-89f15167-c09b-41f1-86bc-7e847f6314af.png)

hmmmm, COULD WE DO BOTH??

**Comment by rnugent3** [comment]
[WS6.zip](https://github.com/HydrologicEngineeringCenter/HEC-FDA/files/12677964/WS6.zip)
compute the existing future stage damage functions, the linked occ types are bad. you can see the error messages in the log file.

**Comment by codymccoy** [comment]
Maybe, I will look into it.

**Comment by rnugent3** [comment]
I don't think we can do the symbols at the function level - we're not tracking errors on each function

**Comment by rnugent3** [comment]
so just the set level in the study tree

**Comment by codymccoy** [comment]
Ok.

**Comment by codymccoy** [comment]
I am still trying to wrap my head around this one. Adding the icons to the tree elements is easy. The hard part is the when, where, and why. With the study that you posted above I cleared the log file and then computed the "Existing_Future" curves. It produced a single line in the log file:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/58bd9136-3420-4575-be36-6f5baf9d2d66)

What I need to determine is what event causes me to add the icon in the tree? The compute button or the save click? I am guessing the save button might be better. It seems like we should be showing the user errors when they happen. I am going to have to gather all the messages that happen during the compute anyway to display them on the tooltip of the new error icon or at least to determine their error level.

**Comment by codymccoy** [comment]
After talking with Brennan we decided that we should just early exit and let the user know that there is an error. The particular message that i posted above is coming from an occtype that has a fatal error. We are currently checking for the error but then returning a valid object:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/6cae56b1-228b-4224-a58f-a3b799490a65)

Since the Inventory knows the occtypes that it needs at the start of the compute, we can check all the occtypes to see if they are valid. We can then do a popup to the user that there are errors and the occtypes need fixing before computing. We are already validating other items before computing and displaying that to the user. This would just be one more check.

**Comment by rnugent3** [comment]
Sounds good

**Comment by codymccoy** [comment]
I now produce the following error message:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/459e6681-3576-43f0-b7b5-36dc5c38a4be)

**Comment by codymccoy** [comment]
I was going to produce the actual errors but message boxes can't scroll and the list can potentially be quite long as shown here:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/037521c1-b221-4bef-b8d1-a28f040f648c)

**Comment by rnugent3** [comment]
Perfect. Thanks for figuring that out!

**Comment by codymccoy** [comment]
@rnugent3 @Brennan1994  It occurs to me that I am checking every occtype in the inventories' occtype list. Is that correct, or is there a smaller subset of occtypes that only pertain to this compute? I don't really remember how this works.

**Comment by codymccoy** [comment]
There might be other items that have slipped through the validation before computing the occtypes. If we find more then we can add them to the validation check.

**Comment by codymccoy** [comment]
@rnugent3 This UI opens with these two sections completely collapsed. Is that what you want or do you want me to spread them out more?
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/45e1a307-45bb-4674-b48b-01db7c0fbff2)

**Comment by rnugent3** [comment]
all occ types is preferred, and please expand the sections a little, thank you

**Comment by codymccoy** [comment]
The sizing stuff is not simple. I thing this UI could use some attention but i think it will take up too much of my limited time right now. I want to attack as many priority issues as I can. I will log my thoughts on this as a separate github issue. I am thinking maybe something like a tab control would be better so that the user doesn't have to slide grid splitters up and down to view what they want.

**Comment by rnugent3** [comment]
understood, thanks for thinking it through

**Comment by Brennan1994** [comment]
Some of this issue was addressed in PR #970 The remaining is captured in a separate issue.
