### ISSUE TITLE
Changes to Scenarios Editor for Total Risk Calculation

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#963]
Let's use this issue to track the view changes for the total risk calculations. I have updated the screen shots to remove the possibility of using an exterior-interior function if modeling nonfail risk + fail risk. 

![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/25163165/f4c42b53-0a29-4337-91b8-912aa1269e1e)
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/25163165/4c52a4fa-5d5b-4d9a-95a3-4ca4d0870c21)

**Comment by rnugent3** [comment]
@codymccoy please disregard my note about not allowing use of the default system response. 

default system response is OK - total probability still applies

**Comment by codymccoy** [comment]
@rnugent3 How does this look? I don't have the checkbox logic plugged in yet. 
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/1fbaa01f-7c2a-43bf-a2c5-830ebaa023fb)

**Comment by codymccoy** [comment]
@rnugent3 Based on the pics above it looks like you want me to change the checkbox text depending on if it is selected or not. Is that correct?
if unselected: "Include Non-Breach Risk"
if selected: "Breach AND Non-Breach Conditions Uniquely Modeled"

**Comment by rnugent3** [comment]
Sorry for the confusing text. Let's have a static label "Non-Failure Scenario Modeled"

**Comment by rnugent3** [comment]
And please change "breach" and "no breach" to "Failure" and "Non-Failure"

**Comment by codymccoy** [comment]
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/c1eebb45-a43b-4870-af3a-8b4773cc5043)

**Comment by rnugent3** [comment]
Looks great. 

The validation on the requirement of a levee ... in case you haven't caught it already ... we should check that at least one impact area has a levee

**Comment by codymccoy** [comment]
I am refreshing on how validation works in this editor. Looks like we no longer validate before saving. We allow the users to save in an error state.
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/29973403-d4fc-402e-8aef-86b3ac7a5de2)

I have an icon on the tabs that also have a tooltip if in error:
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/f17cc805-ef3b-4622-b239-d523268ae649)

@rnugent3  I am not sure what you are wanting with the levee. We do not have the levee marked as required ( red star). Can you elaborate? Are you wanting me to remove the levee combo if the impact area has no levee?

**Comment by rnugent3** [comment]
I see. Ok. Please disregard any notion of levee validation, haha. I will handle it in the model.

**Comment by codymccoy** [comment]
I believe that all the UI updates and reading and writing to the database are completed.
Completed in branch 956_ui_updates

**Comment by rnugent3** [comment]
I think that the only thing that we'll need to do is set up a simulation correctly with the additional set of stage-damage functions. let's handle this on a separate issue after my model code is on main so that you can access the new constructor code

**Comment by codymccoy** [comment]
I forgot to remove the existing stage damage combo. I will remove that in my current branch.
![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/47757848/5d1d66e8-a821-45ff-870a-33035d0b7767)
