### ISSUE TITLE
Failure to Obtain Muncie Terrain Values

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#984]
I used the data here: \\share.hec.usace.army.mil\USACE\HEC-FDA\Version_2.0\QSGStudyData

Terrain: hdf
Inventory: base without 

![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/25163165/c61d939f-89ef-48c4-8745-30762ec2d0f4)

**Comment by Brennan1994** [comment]
Dean and I worked through an issue that looked just like this. Please test again and confirm this is still real. I suspect it's been fixed. I'm using the same dataset and cant replicate on my side.

**Comment by rnugent3** [comment]
not replicated with most recent build
