### ISSUE TITLE
structure inventory edit bug

### ISSUE THREAD

**Issue by rnugent3** [HydrologicEngineeringCenter/HEC-FDA#985]
I edited the structure inventory to use a different field for the foundation height, and cannot save, see error in the picture 

![image](https://github.com/HydrologicEngineeringCenter/HEC-FDA/assets/25163165/46c81611-ae66-4e7c-86d7-11a01f90b98c)

**Comment by Brennan1994** [comment]
@rnugent3  I'm forcing you to set a project projection before you import a structure inventory. Maybe you were able to import initially because you had an older build? I want to make sure your structures line up with your hydraulics, so I'm reprojecting.

**Comment by Brennan1994** [comment]
I need to add a prompt in the hydraulic importers to set that projection as well. I'll bring it up in priority
